export interface SeedAuthorItem {
  _id?: string;
  name: string;
  slug: string;
  alternateNames?: string[];
  biography: string;
  shortBiography: string;
  nationality: string;
  country: string;
  isIndian: boolean;
  birthYear?: number;
  deathYear?: number;
  profession: string[];
  fields: string[];
  notableWorks: string[];
  portrait: string;
  coverImage?: string;
  officialWebsite?: string;
  wikipediaUrl?: string;
  sources: Array<{ name: string; url: string }>;
  featured: boolean;
  popular: boolean;
  bookCount: number;
}

export const SEED_AUTHORS: SeedAuthorItem[] = [
  {
    name: 'David Thomas',
    slug: 'david-thomas',
    biography: 'David Thomas is an internationally recognized programmer, author, and one of the original 17 authors of the Agile Manifesto. Co-founder of Pragmatic Programmers publishing.',
    shortBiography: 'Pioneering software engineer, co-author of The Pragmatic Programmer, and Agile Manifesto signatory.',
    nationality: 'British',
    country: 'United Kingdom',
    isIndian: false,
    profession: ['Software Engineer', 'Author', 'Publisher'],
    fields: ['Computer Science', 'Software Engineering', 'Agile Methodologies'],
    notableWorks: ['The Pragmatic Programmer', 'Programming Ruby'],
    portrait: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Dave_Thomas_(programmer)',
    officialWebsite: 'https://pragprog.com',
    sources: [{ name: 'Pragmatic Bookshelf', url: 'https://pragprog.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Andrew Hunt',
    slug: 'andrew-hunt',
    biography: 'Andrew Hunt is a software designer, author, and Agile Manifesto co-creator who specializes in practical developer efficiency and systems thinking.',
    shortBiography: 'Software craftsman and co-author of The Pragmatic Programmer.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Software Architect', 'Author', 'Consultant'],
    fields: ['Software Design', 'Pragmatic Thinking', 'Agile'],
    notableWorks: ['The Pragmatic Programmer', 'Pragmatic Thinking and Learning'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Andy_Hunt_(author)',
    sources: [{ name: 'Andy Hunt Official', url: 'https://toolshed.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Martin Kleppmann',
    slug: 'martin-kleppmann',
    biography: 'Martin Kleppmann is an Associate Professor in the Department of Computer Science and Technology at the University of Cambridge, specializing in distributed systems, local-first software, and CRDTs.',
    shortBiography: 'Associate Professor at Cambridge University and author of Designing Data-Intensive Applications.',
    nationality: 'German',
    country: 'United Kingdom',
    isIndian: false,
    profession: ['Computer Scientist', 'Researcher', 'Author'],
    fields: ['Distributed Systems', 'Databases', 'Local-First Software', 'CRDTs'],
    notableWorks: ['Designing Data-Intensive Applications'],
    portrait: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://martin.kleppmann.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Martin_Kleppmann',
    sources: [{ name: 'Cambridge University', url: 'https://www.cl.cam.ac.uk/~mk428/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Robert C. Martin',
    slug: 'robert-c-martin',
    alternateNames: ['Uncle Bob'],
    biography: 'Robert Cecil Martin, colloquially known as Uncle Bob, is an American software engineer, author, and teacher. Founder of Uncle Bob Consulting and Clean Coder.',
    shortBiography: 'Renowned software craftsman, creator of SOLID principles, and author of Clean Code.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Software Engineer', 'Consultant', 'Speaker'],
    fields: ['Software Architecture', 'Clean Code', 'Object-Oriented Design'],
    notableWorks: ['Clean Code', 'Clean Architecture', 'The Clean Coder'],
    portrait: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'http://cleancoder.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Robert_C._Martin',
    sources: [{ name: 'Clean Coder', url: 'http://cleancoder.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Harold Abelson',
    slug: 'harold-abelson',
    biography: 'Harold "Hal" Abelson is the Class of 1922 Professor of Computer Science and Engineering in the EECS Department at MIT, a founding director of Creative Commons, and co-author of SICP.',
    shortBiography: 'MIT EECS Professor, founding director of Creative Commons, and co-author of SICP.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1947,
    profession: ['Computer Scientist', 'Professor', 'Educator'],
    fields: ['Computer Science Education', 'Artificial Intelligence', 'Information Policy'],
    notableWorks: ['Structure and Interpretation of Computer Programs (SICP)'],
    portrait: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.csail.mit.edu/person/hal-abelson',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Hal_Abelson',
    sources: [{ name: 'MIT CSAIL', url: 'https://www.csail.mit.edu' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Thomas H. Cormen',
    slug: 'thomas-h-cormen',
    biography: 'Thomas H. Cormen is Emeritus Professor of Computer Science at Dartmouth College and former Chair of the Dartmouth Writing Program. Co-author of the premier CLRS algorithm text.',
    shortBiography: 'Professor Emeritus at Dartmouth College and co-author of CLRS Algorithms.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Professor', 'Computer Scientist', 'Author'],
    fields: ['Algorithms', 'Parallel Computing', 'Computer Science Education'],
    notableWorks: ['Introduction to Algorithms (CLRS)', 'Algorithms Unlocked'],
    portrait: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.cs.dartmouth.edu/~thc/',
    sources: [{ name: 'Dartmouth College', url: 'https://www.cs.dartmouth.edu/~thc/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Stuart Russell',
    slug: 'stuart-russell',
    biography: 'Stuart J. Russell is a Professor of Computer Science at UC Berkeley and Adjunct Professor of Neurological Surgery at UCSF. Renowned globally for AI safety and autonomous systems.',
    shortBiography: 'Professor of Computer Science at UC Berkeley and co-author of the standard AI textbook.',
    nationality: 'British',
    country: 'United States',
    isIndian: false,
    profession: ['Computer Scientist', 'Professor', 'Author'],
    fields: ['Artificial Intelligence', 'Machine Learning', 'AI Safety'],
    notableWorks: ['Artificial Intelligence: A Modern Approach', 'Human Compatible'],
    portrait: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'http://people.eecs.berkeley.edu/~russell/',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Stuart_J._Russell',
    sources: [{ name: 'UC Berkeley EECS', url: 'http://people.eecs.berkeley.edu/~russell/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'James Clear',
    slug: 'james-clear',
    biography: 'James Clear is an author and speaker focused on habits, decision making, and continuous improvement. His newsletter 3-2-1 is read by millions weekly.',
    shortBiography: 'Bestselling author of Atomic Habits and behavioral systems specialist.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Author', 'Speaker', 'Behavioral Researcher'],
    fields: ['Habits', 'Productivity', 'Behavioral Psychology'],
    notableWorks: ['Atomic Habits'],
    portrait: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://jamesclear.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/James_Clear',
    sources: [{ name: 'James Clear Official', url: 'https://jamesclear.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Eric Ries',
    slug: 'eric-ries',
    biography: 'Eric Ries is an entrepreneur, author, and creator of the Lean Startup methodology. Founder of the Long-Term Stock Exchange (LTSE).',
    shortBiography: 'Pioneering entrepreneur and author of The Lean Startup.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Entrepreneur', 'Author', 'Adviser'],
    fields: ['Startups', 'Venture Creation', 'Lean Methodologies', 'Innovation'],
    notableWorks: ['The Lean Startup', 'The Startup Way'],
    portrait: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'http://www.theleanstartup.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Eric_Ries',
    sources: [{ name: 'The Lean Startup', url: 'http://www.theleanstartup.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Peter Thiel',
    slug: 'peter-thiel',
    biography: 'Peter Thiel is an entrepreneur and venture capitalist. Co-founder of PayPal, Palantir Technologies, and Founders Fund. First outside investor in Facebook.',
    shortBiography: 'Venture capitalist, PayPal co-founder, and author of Zero to One.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1967,
    profession: ['Venture Capitalist', 'Entrepreneur', 'Author'],
    fields: ['Venture Capital', 'Economics', 'Technology Philosophy'],
    notableWorks: ['Zero to One', 'The Diversity Myth'],
    portrait: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Peter_Thiel',
    sources: [{ name: 'Founders Fund', url: 'https://foundersfund.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Andrew S. Grove',
    slug: 'andrew-s-grove',
    alternateNames: ['Andy Grove'],
    biography: 'Andrew Stephen Grove was a Hungarian-born American businessman and engineer who served as the third CEO of Intel Corporation, transforming Intel into a global microprocessor powerhouse.',
    shortBiography: 'Legendary former CEO and Chairman of Intel Corporation, author of High Output Management.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1936,
    deathYear: 2016,
    profession: ['Executive', 'Engineer', 'Management Pioneer'],
    fields: ['Management Science', 'Semiconductors', 'Executive Leadership'],
    notableWorks: ['High Output Management', 'Only the Paranoid Survive'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Andy_Grove',
    sources: [{ name: 'Intel Corporation Archives', url: 'https://www.intel.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Ben Horowitz',
    slug: 'ben-horowitz',
    biography: 'Ben Horowitz is an American businessman, investor, and co-founder of the venture capital firm Andreessen Horowitz (a16z). Previously co-founder and CEO of Opsware.',
    shortBiography: 'Co-founder of Andreessen Horowitz (a16z) and author of The Hard Thing About Hard Things.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1966,
    profession: ['Venture Capitalist', 'Tech Executive', 'Author'],
    fields: ['Venture Capital', 'Startup Management', 'Executive Leadership'],
    notableWorks: ['The Hard Thing About Hard Things', 'What You Do Is Who You Are'],
    portrait: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://a16z.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Ben_Horowitz',
    sources: [{ name: 'Andreessen Horowitz', url: 'https://a16z.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Cal Newport',
    slug: 'cal-newport',
    biography: 'Cal Newport is a Professor of Computer Science at Georgetown University and a bestselling author who writes about the intersection of digital technology, culture, and deep focus.',
    shortBiography: 'Georgetown Computer Science Professor and bestselling author of Deep Work.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1982,
    profession: ['Computer Scientist', 'Professor', 'Author'],
    fields: ['Theoretical Computer Science', 'Distributed Algorithms', 'Productivity'],
    notableWorks: ['Deep Work', 'Digital Minimalism', 'So Good They Can’t Ignore You'],
    portrait: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://calnewport.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cal_Newport',
    sources: [{ name: 'Georgetown University', url: 'https://people.cs.georgetown.edu/~cnewport/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Carol S. Dweck',
    slug: 'carol-s-dweck',
    biography: 'Carol S. Dweck is the Lewis and Virginia Eaton Professor of Psychology at Stanford University. Known for her foundational research on implicit theories of intelligence and growth mindset.',
    shortBiography: 'Stanford Psychology Professor and pioneer of Growth Mindset research.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1946,
    profession: ['Psychologist', 'Professor', 'Author'],
    fields: ['Developmental Psychology', 'Growth Mindset', 'Motivation Science'],
    notableWorks: ['Mindset: The New Psychology of Success'],
    portrait: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://psychology.stanford.edu/people/carol-dweck',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Carol_Dweck',
    sources: [{ name: 'Stanford University', url: 'https://psychology.stanford.edu' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Charles Duhigg',
    slug: 'charles-duhigg',
    biography: 'Charles Duhigg is a Pulitzer Prize-winning investigative journalist and author. Graduate of Yale and Harvard Business School, former senior editor at The New York Times.',
    shortBiography: 'Pulitzer Prize-winning investigative journalist and author of The Power of Habit.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1974,
    profession: ['Journalist', 'Author', 'Podcast Host'],
    fields: ['Behavioral Science', 'Productivity', 'Habit Loops'],
    notableWorks: ['The Power of Habit', 'Smarter Faster Better', 'Supercommunicators'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://charlesduhigg.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Charles_Duhigg',
    sources: [{ name: 'Charles Duhigg Official', url: 'https://charlesduhigg.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Daniel Kahneman',
    slug: 'daniel-kahneman',
    biography: 'Daniel Kahneman was an Israeli-American psychologist and Nobel Memorial Prize laureate in Economic Sciences. Pioneer in behavioral economics and heuristics.',
    shortBiography: 'Nobel Laureate in Economics and author of Thinking, Fast and Slow.',
    nationality: 'Israeli-American',
    country: 'United States',
    isIndian: false,
    birthYear: 1934,
    deathYear: 2024,
    profession: ['Psychologist', 'Economist', 'Professor'],
    fields: ['Behavioral Economics', 'Cognitive Psychology', 'Decision Theory'],
    notableWorks: ['Thinking, Fast and Slow', 'Noise: A Flaw in Human Judgment'],
    portrait: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Daniel_Kahneman',
    sources: [{ name: 'Nobel Prize Official', url: 'https://www.nobelprize.org' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Robert B. Cialdini',
    slug: 'robert-b-cialdini',
    biography: 'Robert B. Cialdini is Regents’ Professor Emeritus of Psychology and Marketing at Arizona State University and the foremost global expert in the fields of persuasion and influence.',
    shortBiography: 'Regents’ Professor Emeritus at Arizona State University and author of Influence.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1945,
    profession: ['Psychologist', 'Professor', 'Author', 'Keynote Speaker'],
    fields: ['Social Psychology', 'Persuasion Science', 'Behavioral Influence'],
    notableWorks: ['Influence: The Psychology of Persuasion', 'Pre-Suasion'],
    portrait: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.influenceatwork.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Robert_Cialdini',
    sources: [{ name: 'Influence At Work', url: 'https://www.influenceatwork.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'A.P.J. Abdul Kalam',
    slug: 'apj-abdul-kalam',
    alternateNames: ['Avul Pakir Jainulabdeen Abdul Kalam', 'Dr. Kalam', 'Missile Man of India'],
    biography: 'Dr. A.P.J. Abdul Kalam was an Indian aerospace scientist and statesman who served as the 11th President of India from 2002 to 2007. Renowned for his role in India’s civilian space program and missile development.',
    shortBiography: '11th President of India, visionary scientist, Bharat Ratna recipient, and author of Wings of Fire.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1931,
    deathYear: 2015,
    profession: ['Aerospace Scientist', 'Statesman', 'Author', 'Educator'],
    fields: ['Aerospace Engineering', 'National Development', 'Education', 'Youth Motivation'],
    notableWorks: ['Wings of Fire', 'Ignited Minds', 'India 2020'],
    portrait: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/A._P._J._Abdul_Kalam',
    sources: [{ name: 'President of India Archive', url: 'https://presidentofindia.gov.in' }],
    featured: true,
    popular: true,
    bookCount: 2,
  },
  {
    name: 'Ramachandra Guha',
    slug: 'ramachandra-guha',
    biography: 'Ramachandra Guha is a leading Indian historian, environmentalist, and biographer. Known for his comprehensive histories of post-independence India and biographies of Mahatma Gandhi.',
    shortBiography: 'Eminent Indian historian and author of India After Gandhi.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1958,
    profession: ['Historian', 'Biographer', 'Essayist'],
    fields: ['Modern Indian History', 'Environmental Studies', 'Cricket History', 'Political Science'],
    notableWorks: ['India After Gandhi', 'Gandhi: The Years That Changed the World', 'A Corner of a Foreign Field'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'http://ramachandraguha.in',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Ramachandra_Guha',
    sources: [{ name: 'Ramachandra Guha Official', url: 'http://ramachandraguha.in' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Jawaharlal Nehru',
    slug: 'jawaharlal-nehru',
    alternateNames: ['Pandit Nehru'],
    biography: 'Jawaharlal Nehru was an Indian anti-colonial nationalist, secular humanist, social democrat, and author who was the first Prime Minister of India from 1947 until his death in 1964.',
    shortBiography: 'First Prime Minister of India, freedom fighter, and author of The Discovery of India.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1889,
    deathYear: 1964,
    profession: ['Statesman', 'Prime Minister', 'Historian', 'Author'],
    fields: ['Indian History', 'World History', 'Political Philosophy', 'International Diplomacy'],
    notableWorks: ['The Discovery of India', 'Glimpses of World History', 'An Autobiography'],
    portrait: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Jawaharlal_Nehru',
    sources: [{ name: 'Nehru Memorial Museum and Library', url: 'https://www.pmml.nic.in' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Mahatma Gandhi',
    slug: 'mahatma-gandhi',
    alternateNames: ['Mohandas Karamchand Gandhi', 'Bapu'],
    biography: 'Mohandas Karamchand Gandhi was an Indian lawyer, anti-colonial nationalist, and political ethicist who employed nonviolent resistance to lead the successful campaign for India’s independence from British rule.',
    shortBiography: 'Father of the Nation in India, pioneer of Satyagraha nonviolent resistance.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1869,
    deathYear: 1948,
    profession: ['Freedom Fighter', 'Lawyer', 'Ethicist', 'Author'],
    fields: ['Nonviolent Resistance', 'Ethics', 'Self-Reliance', 'Indian Independence'],
    notableWorks: ['The Story of My Experiments with Truth', 'Hind Swaraj', 'Satyagraha in South Africa'],
    portrait: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Mahatma_Gandhi',
    sources: [{ name: 'Gandhi Heritage Portal', url: 'https://www.gandhiheritageportal.org' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'A.L. Basham',
    slug: 'a-l-basham',
    biography: 'Arthur Llewellyn Basham was an indologist and historian of Indian culture. Professor of Asian Civilizations at the Australian National University and School of Oriental and African Studies (SOAS), London.',
    shortBiography: 'Eminent British indologist and author of The Wonder That Was India.',
    nationality: 'British',
    country: 'United Kingdom',
    isIndian: false,
    birthYear: 1914,
    deathYear: 1986,
    profession: ['Indologist', 'Historian', 'Professor'],
    fields: ['Ancient Indian History', 'Sanskrit Literature', 'South Asian Religions'],
    notableWorks: ['The Wonder That Was India', 'History and Doctrines of the Ajivikas'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Arthur_Llewellyn_Basham',
    sources: [{ name: 'SOAS University of London', url: 'https://www.soas.ac.uk' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Amartya Sen',
    slug: 'amartya-sen',
    biography: 'Amartya Sen is an Indian economist and philosopher. Thomas W. Lamont University Professor and Professor of Economics and Philosophy at Harvard University. Awarded the Nobel Memorial Prize in Economic Sciences in 1998.',
    shortBiography: 'Nobel Laureate in Economics, Bharat Ratna, Harvard Professor, and author of The Argumentative Indian.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1933,
    profession: ['Economist', 'Philosopher', 'Professor'],
    fields: ['Development Economics', 'Welfare Economics', 'Indian History', 'Social Choice Theory'],
    notableWorks: ['The Argumentative Indian', 'Development as Freedom', 'Idea of Justice'],
    portrait: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://scholar.harvard.edu/sen',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Amartya_Sen',
    sources: [{ name: 'Harvard University', url: 'https://scholar.harvard.edu/sen' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Yuval Noah Harari',
    slug: 'yuval-noah-harari',
    biography: 'Yuval Noah Harari is an Israeli historian, philosopher, and professor in the Department of History at the Hebrew University of Jerusalem. Author of international bestsellers Sapiens, Homo Deus, and 21 Lessons for the 21st Century.',
    shortBiography: 'Professor of History at Hebrew University of Jerusalem and author of Sapiens.',
    nationality: 'Israeli',
    country: 'Israel',
    isIndian: false,
    birthYear: 1976,
    profession: ['Historian', 'Professor', 'Author'],
    fields: ['World History', 'Macro-history', 'Evolutionary Anthropology'],
    notableWorks: ['Sapiens: A Brief History of Humankind', 'Homo Deus', '21 Lessons for the 21st Century'],
    portrait: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.ynharari.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Yuval_Noah_Harari',
    sources: [{ name: 'Yuval Noah Harari Official', url: 'https://www.ynharari.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Jared Diamond',
    slug: 'jared-diamond',
    biography: 'Jared Mason Diamond is an American geographer, historian, and author. Professor of Geography at UCLA, known for his interdisciplinary works combining ecology, geography, and evolutionary biology.',
    shortBiography: 'Pulitzer Prize-winning author and Professor of Geography at UCLA.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1937,
    profession: ['Geographer', 'Biologist', 'Author', 'Professor'],
    fields: ['Environmental Geography', 'Physiology', 'Evolutionary Biology'],
    notableWorks: ['Guns, Germs, and Steel', 'Collapse', 'The Third Chimpanzee'],
    portrait: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.geog.ucla.edu/person/jared-diamond/',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Jared_Diamond',
    sources: [{ name: 'UCLA Geography', url: 'https://www.geog.ucla.edu' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Peter Frankopan',
    slug: 'peter-frankopan',
    biography: 'Peter Frankopan is Professor of Global History at Oxford University, Director of the Oxford Centre for Byzantine Research, and Senior Research Fellow at Worcester College, Oxford.',
    shortBiography: 'Professor of Global History at Oxford University and author of The Silk Roads.',
    nationality: 'British',
    country: 'United Kingdom',
    isIndian: false,
    birthYear: 1972,
    profession: ['Historian', 'Professor', 'Author'],
    fields: ['Global History', 'Byzantine History', 'Silk Roads History'],
    notableWorks: ['The Silk Roads: A New History of the World', 'The New Silk Roads', 'The Earth Transformed'],
    portrait: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.peterfrankopan.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Peter_Frankopan',
    sources: [{ name: 'Oxford University', url: 'https://www.history.ox.ac.uk/people/professor-peter-frankopan' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Marcus Aurelius',
    slug: 'marcus-aurelius',
    biography: 'Marcus Aurelius Antoninus was Roman emperor from 161 to 180 AD and a Stoic philosopher. His personal journal, Meditations, remains one of antiquity’s greatest philosophical reflections.',
    shortBiography: 'Roman Emperor, Stoic philosopher, and author of Meditations.',
    nationality: 'Roman',
    country: 'Italy',
    isIndian: false,
    birthYear: 121,
    deathYear: 180,
    profession: ['Roman Emperor', 'Stoic Philosopher'],
    fields: ['Stoicism', 'Ancient Philosophy', 'Ethics', 'Self-Mastery'],
    notableWorks: ['Meditations'],
    portrait: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Marcus_Aurelius',
    sources: [{ name: 'Stanford Encyclopedia of Philosophy', url: 'https://plato.stanford.edu/entries/marcus-aurelius/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Viktor E. Frankl',
    slug: 'viktor-e-frankl',
    biography: 'Viktor Emil Frankl was an Austrian neurologist, psychiatrist, Holocaust survivor, and founder of logotherapy, a form of existential analysis focused on finding meaning.',
    shortBiography: 'Austrian psychiatrist, Holocaust survivor, and founder of Logotherapy.',
    nationality: 'Austrian',
    country: 'Austria',
    isIndian: false,
    birthYear: 1905,
    deathYear: 1997,
    profession: ['Neurologist', 'Psychiatrist', 'Author'],
    fields: ['Logotherapy', 'Existential Psychology', 'Psychoanalysis'],
    notableWorks: ['Man’s Search for Meaning', 'The Will to Meaning'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.viktorfrankl.org',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Viktor_Frankl',
    sources: [{ name: 'Viktor Frankl Institute', url: 'https://www.viktorfrankl.org' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Michael J. Sandel',
    slug: 'michael-j-sandel',
    biography: 'Michael J. Sandel is the Anne T. and Robert M. Bass Professor of Government Theory at Harvard University Law School and Harvard Faculty of Arts and Sciences.',
    shortBiography: 'Harvard University Political Philosophy Professor and author of Justice.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1953,
    profession: ['Philosopher', 'Professor', 'Author'],
    fields: ['Political Philosophy', 'Ethics', 'Public Reasoning'],
    notableWorks: ['Justice: What’s the Right Thing to Do?', 'What Money Can’t Buy', 'The Tyranny of Merit'],
    portrait: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://scholar.harvard.edu/sandel',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Michael_Sandel',
    sources: [{ name: 'Harvard University', url: 'https://scholar.harvard.edu/sandel' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Richard P. Feynman',
    slug: 'richard-p-feynman',
    alternateNames: ['Richard Feynman'],
    biography: 'Richard Phillips Feynman was an American theoretical physicist known for his work in quantum mechanics, quantum electrodynamics, and the physics of the superfluidity of supercooled liquid helium. Awarded the Nobel Prize in Physics in 1965.',
    shortBiography: 'Nobel Laureate in Physics, legendary Caltech professor, and author of Six Easy Pieces.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1918,
    deathYear: 1988,
    profession: ['Theoretical Physicist', 'Professor', 'Author'],
    fields: ['Quantum Electrodynamics', 'Particle Physics', 'Physics Pedagogy'],
    notableWorks: ['Six Easy Pieces', 'Surely You’re Joking, Mr. Feynman!', 'The Feynman Lectures on Physics'],
    portrait: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Richard_Feynman',
    sources: [{ name: 'Caltech Feynman Lectures', url: 'https://www.feynmanlectures.caltech.edu' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Stephen Hawking',
    slug: 'stephen-hawking',
    biography: 'Stephen William Hawking was an English theoretical physicist, cosmologist, and author who was Director of Research at the Centre for Theoretical Cosmology at the University of Cambridge and Lucasian Professor of Mathematics.',
    shortBiography: 'World-renowned theoretical physicist, Cambridge Professor, and author of A Brief History of Time.',
    nationality: 'British',
    country: 'United Kingdom',
    isIndian: false,
    birthYear: 1942,
    deathYear: 2018,
    profession: ['Theoretical Physicist', 'Cosmologist', 'Author'],
    fields: ['General Relativity', 'Quantum Gravity', 'Black Hole Thermodynamics'],
    notableWorks: ['A Brief History of Time', 'The Universe in a Nutshell', 'The Grand Design'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.hawking.org.uk',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Stephen_Hawking',
    sources: [{ name: 'Hawking Estate Archive', url: 'https://www.hawking.org.uk' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Siddhartha Mukherjee',
    slug: 'siddhartha-mukherjee',
    biography: 'Siddhartha Mukherjee is an Indian-American physician, biologist, and author. Associate Professor of Medicine at Columbia University and oncologist at Columbia University Irving Medical Center. Awarded the Pulitzer Prize for General Non-Fiction.',
    shortBiography: 'Pulitzer Prize-winning oncologist, Columbia University Professor, and author of The Gene.',
    nationality: 'Indian-American',
    country: 'United States',
    isIndian: true,
    birthYear: 1970,
    profession: ['Physician', 'Oncologist', 'Author', 'Biologist'],
    fields: ['Oncology', 'Genetics', 'Cell Biology', 'Medical History'],
    notableWorks: ['The Gene: An Intimate History', 'The Emperor of All Maladies', 'The Song of the Cell'],
    portrait: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'http://siddharthamukherjee.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Siddhartha_Mukherjee',
    sources: [{ name: 'Columbia University Medical Center', url: 'https://www.cancer.columbia.edu' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Morgan Housel',
    slug: 'morgan-housel',
    biography: 'Morgan Housel is a partner at Collaborative Fund, two-time winner of the Best in Business Award from the Society of American Business Editors and Writers, and author of The Psychology of Money.',
    shortBiography: 'Financial columnist and author of the global bestseller The Psychology of Money.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Author', 'Financial Columnist', 'Partner'],
    fields: ['Behavioral Finance', 'Economics', 'Decision Making'],
    notableWorks: ['The Psychology of Money', 'Same as Ever'],
    portrait: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://collabfund.com/blog/authors/morgan/',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Morgan_Housel',
    sources: [{ name: 'Collaborative Fund', url: 'https://collabfund.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Benjamin Graham',
    slug: 'benjamin-graham',
    biography: 'Benjamin Graham was a British-born American economist, professor, and investor. Widely known as the "father of value investing", mentor to Warren Buffett at Columbia Business School.',
    shortBiography: 'Father of Value Investing, Columbia Business School professor, and mentor to Warren Buffett.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1894,
    deathYear: 1976,
    profession: ['Economist', 'Investor', 'Professor', 'Author'],
    fields: ['Value Investing', 'Security Analysis', 'Financial Economics'],
    notableWorks: ['The Intelligent Investor', 'Security Analysis'],
    portrait: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Benjamin_Graham',
    sources: [{ name: 'Columbia Business School Archive', url: 'https://business.columbia.edu' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'George Orwell',
    slug: 'george-orwell',
    alternateNames: ['Eric Arthur Blair'],
    biography: 'Eric Arthur Blair, known by his pen name George Orwell, was an English novelist, essayist, journalist, and critic whose work is characterized by lucid prose, biting social criticism, and opposition to totalitarianism.',
    shortBiography: 'Legendary English author of 1984 and Animal Farm.',
    nationality: 'British',
    country: 'United Kingdom',
    isIndian: false,
    birthYear: 1903,
    deathYear: 1950,
    profession: ['Novelist', 'Journalist', 'Critic'],
    fields: ['Literary Fiction', 'Dystopian Fiction', 'Political Satire'],
    notableWorks: ['1984', 'Animal Farm', 'Homage to Catalonia'],
    portrait: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/George_Orwell',
    sources: [{ name: 'The Orwell Foundation', url: 'https://www.orwellfoundation.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'R.K. Narayan',
    slug: 'r-k-narayan',
    alternateNames: ['Rasipuram Krishnaswami Iyer Narayanaswami'],
    biography: 'Rasipuram Krishnaswami Iyer Narayanaswami was an Indian writer known for his work set in the fictional South Indian town of Malgudi. Leading figure of early Indian literature in English alongside Mulk Raj Anand and Raja Rao.',
    shortBiography: 'Iconic Indian novelist, creator of the fictional world of Malgudi.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1906,
    deathYear: 2001,
    profession: ['Writer', 'Novelist', 'Short Story Author'],
    fields: ['Indian English Literature', 'Fiction', 'Cultural Commentary'],
    notableWorks: ['Malgudi Days', 'Swami and Friends', 'The Guide'],
    portrait: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/R._K._Narayan',
    sources: [{ name: 'Sahitya Akademi Archive', url: 'https://sahitya-akademi.gov.in' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Arundhati Roy',
    slug: 'arundhati-roy',
    biography: 'Suzanna Arundhati Roy is an Indian author best known for her novel The God of Small Things, which won the Man Booker Prize for Fiction in 1997. Also a political activist involved in human rights and environmental causes.',
    shortBiography: 'Man Booker Prize-winning Indian author of The God of Small Things.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1961,
    profession: ['Author', 'Essayist', 'Activist'],
    fields: ['Literary Fiction', 'Political Essays', 'Human Rights'],
    notableWorks: ['The God of Small Things', 'The Ministry of Utmost Happiness'],
    portrait: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Arundhati_Roy',
    sources: [{ name: 'Booker Prize Archive', url: 'https://thebookerprizes.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Walter Isaacson',
    slug: 'walter-isaacson',
    biography: 'Walter Isaacson is an American author, journalist, and professor of history at Tulane University. Former Chairman and CEO of CNN and managing editor of Time magazine.',
    shortBiography: 'Distinguished biographer of Steve Jobs, Leonardo da Vinci, and Albert Einstein.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1952,
    profession: ['Biographer', 'Journalist', 'Professor'],
    fields: ['Biography', 'History of Innovation', 'Journalism'],
    notableWorks: ['Steve Jobs', 'Leonardo da Vinci', 'Einstein: His Life and Universe', 'The Innovators'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.walterisaacson.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Walter_Isaacson',
    sources: [{ name: 'Tulane University', url: 'https://liberalarts.tulane.edu/departments/history/people/walter-isaacson' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
];
