import { SeedBookItem } from './booksData';

export const BOOKS_PART_2: SeedBookItem[] = [
  {
    title: 'Wings of Fire',
    subtitle: 'An Autobiography of APJ Abdul Kalam',
    slug: 'wings-of-fire',
    authors: ['A.P.J. Abdul Kalam', 'Arun Tiwari'],
    primaryAuthor: 'A.P.J. Abdul Kalam',
    description: 'Wings of Fire is an inspiring autobiography of Dr. A.P.J. Abdul Kalam, covering his early life in Rameswaram, his struggles against financial adversity, his role in establishing India’s space program at ISRO, and his leadership in indigenous missile defense at DRDO.',
    shortDescription: 'The iconic, deeply inspiring autobiography of Dr. APJ Abdul Kalam, from Rameswaram to the presidency.',
    summary: 'Chronicles Kalam’s childhood, education at MIT Chennai, early rocket launches in Thumba, the SLV-3 mission, and the development of the Agni and Prithvi missiles with profound spiritual reflections.',
    keyIdeas: [
      'Resilience Through Adversity: How humble beginnings and resource scarcity forge extraordinary scientific ingenuity.',
      'Team Leadership in Science: Empowering multidisciplinary scientists through trust, autonomy, and shared national purpose.',
      'Spiritual Integration with Technology: Harmonizing deep spiritual faith with rational scientific inquiry.',
    ],
    whyRead: 'A foundational Indian memoir that ignites scientific curiosity, moral integrity, and relentless optimism in youth and professionals.',
    importance: 'One of the best-selling autobiographies in Indian publishing history, translated into over 18 languages.',
    whoShouldRead: ['Students and engineers', 'Civil services aspirants', 'Anyone seeking inspiration in overcoming hardship'],
    bestFor: ['Inspiration', 'Indian science history', 'Leadership', 'Youth motivation'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '5-6 hours',
    pageCount: 180,
    publicationYear: 1999,
    publisher: 'Universities Press (India)',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: 'Special Illustrated Edition',
    latestEditionYear: 2015,
    editionPublisher: 'Universities Press (India)',
    editionVerified: true,
    isbn10: '8173711461',
    isbn13: '978-8173711466',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-science-technology',
    subjects: ['Biography', 'Indian Space Program', 'Missile Technology', 'Inspirational'],
    topics: ['Dr APJ Abdul Kalam', 'ISRO', 'DRDO', 'Scientific Leadership', 'Rameswaram'],
    genres: ['Autobiography', 'Non-Fiction', 'Science & Technology'],
    tags: ['kalam', 'wings-of-fire', 'isro', 'inspirational', 'indian-biography', 'drdo'],
    bookTypes: ['Autobiography', 'Biography', 'Non Fiction', 'Inspirational'],
    readingPurposes: ['understand-indian-society', 'develop-leadership'],
    careers: ['college-student', 'software-engineer', 'civil-services-aspirant'],
    goals: ['understand-indian-society'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 99,
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL18193858W/Wings_of_Fire',
    legitimatePurchaseLinks: [{ label: 'Universities Press India', url: 'https://www.universitiespress.com', storeOrPlatform: 'Universities Press' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL18193858W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Universities Press (India)',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Discovery of India',
    subtitle: 'From the Indus Valley Civilization to the Freedom Movement',
    slug: 'the-discovery-of-india',
    authors: ['Jawaharlal Nehru'],
    primaryAuthor: 'Jawaharlal Nehru',
    description: 'Written during his four years of imprisonment at Ahmednagar Fort (1942–1946) for participating in the Quit India Movement, Jawaharlal Nehru’s The Discovery of India is an intimate and comprehensive exploration of the Indian subcontinent’s history, philosophy, arts, and civilisational ethos.',
    shortDescription: 'Nehru’s monumental exploration of Indian civilisational identity, written from prison during the freedom struggle.',
    summary: 'Traces the synthesis of Indian culture from the Indus Valley and Vedic periods, through the Mauryan and Mughal empires, British colonial exploitation, and the resurgence of the freedom struggle.',
    keyIdeas: [
      'Unity in Diversity: The idea that India is an ancient palimpsest where layer upon layer of cultures and religions have coexisted.',
      'Scientific Temper: The necessity of combining scientific rationalism with moral and civilisational values.',
      'Critique of Colonial De-industrialization: How colonial economic policies dismantled traditional Indian arts and industry.',
    ],
    whyRead: 'A masterwork of historical literature that reveals the philosophical foundation of modern, secular, democratic India.',
    importance: 'Adapted into the legendary TV series Bharat Ek Khoj by Shyam Benegal; an indelible cultural touchstone.',
    whoShouldRead: ['Anyone seeking to understand Indian history and unity', 'Civil services and humanities scholars'],
    bestFor: ['Indian history', 'Indian civilization', 'Cultural synthesis', 'Freedom movement'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Basic awareness of Indian history'],
    estimatedReadingTime: '18-22 hours',
    pageCount: 650,
    publicationYear: 1946,
    publisher: 'Signet Press / Oxford University Press India',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: 'Oxford University Press Centennial Edition',
    latestEditionYear: 1989,
    editionPublisher: 'Oxford University Press',
    editionVerified: true,
    isbn10: '0195623592',
    isbn13: '978-0195623598',
    format: ['Paperback', 'Hardcover', 'Ebook'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-history-civilisation',
    subjects: ['Indian History', 'Civilization', 'Freedom Struggle', 'Indian Philosophy'],
    topics: ['Ancient India', 'Mughal Era', 'Freedom Movement', 'Indian Civilisation'],
    genres: ['History', 'Classic', 'Non-Fiction'],
    tags: ['indian-history', 'nehru', 'classic', 'discovery-of-india', 'freedom-struggle'],
    bookTypes: ['History', 'Classic', 'Non Fiction'],
    readingPurposes: ['understand-indian-society', 'learn-history'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['understand-indian-society', 'learn-history'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 94,
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL15848245W/The_Discovery_of_India',
    legitimatePurchaseLinks: [{ label: 'Oxford University Press India', url: 'https://india.oup.com', storeOrPlatform: 'OUP India' }],
    legitimateDigitalLinks: [{ label: 'Internet Archive Public Record', url: 'https://archive.org/details/TheDiscoveryOfIndia-JawaharlalNehru', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Oxford University Press',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'India After Gandhi',
    subtitle: 'The History of the World’s Largest Democracy',
    slug: 'india-after-gandhi',
    authors: ['Ramachandra Guha'],
    primaryAuthor: 'Ramachandra Guha',
    description: 'Born against the backdrop of partition and bloodshed, post-colonial India faced seemingly insurmountable odds. Ramachandra Guha’s India After Gandhi provides a breathtaking, magisterial narrative of modern India’s triumphs, internal conflicts, linguistic reorganizations, wars, and enduring democratic resilience.',
    shortDescription: 'The definitive, monumental historical narrative of post-independence India.',
    summary: 'Covers the accession of princely states, the drafting of the Constitution, the Nehruvian era, the Emergency, linguistic politics, religious tensions, and economic liberalization.',
    keyIdeas: [
      'A Republic of Unlikely Survival: How India defied Western predictions that it would splinter or descend into dictatorship.',
      'The Constitution as a Living Anchor: Dr. B.R. Ambedkar and the constituent assembly’s vision of civic nationalism.',
      'Language and Identity: Resolving the linguistic reorganization of states while preserving national unity.',
      'Electoral Democracy: How universal adult franchise created profound political empowerment for subaltern citizens.',
    ],
    whyRead: 'Widely celebrated as the single best book to understand modern democratic India and its complex institutional evolution.',
    importance: 'Standard reference for Indian political history, university curriculums, and civil services preparation.',
    whoShouldRead: ['Anyone seeking an in-depth understanding of post-1947 Indian history and politics', 'UPSC and civil services aspirants'],
    bestFor: ['Modern Indian history', 'Indian politics', 'Constitutional history', 'Democratic studies'],
    readingLevel: 'ADVANCED',
    prerequisites: ['Basic familiarity with 20th-century world history and Indian independence'],
    estimatedReadingTime: '30-35 hours',
    pageCount: 960,
    publicationYear: 2007,
    publisher: 'Picador / Ecco (HarperCollins)',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: '10th Anniversary Revised & Expanded Edition',
    latestEditionYear: 2017,
    editionPublisher: 'Picador India',
    editionVerified: true,
    isbn10: '0330505548',
    isbn13: '978-0330505543',
    format: ['Hardcover', 'Paperback', 'Ebook'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-history-civilisation',
    subjects: ['Indian History', 'Post-Independence History', 'Political Science', 'Democracy'],
    topics: ['Indian History', 'Democracy in India', 'Constitution of India', 'Nehruvian Era'],
    genres: ['History', 'Non-Fiction', 'Academic'],
    tags: ['india-history', 'ramachandra-guha', 'modern-india', 'democracy', 'upsc-essential'],
    bookTypes: ['History', 'Academic', 'Non Fiction'],
    readingPurposes: ['understand-indian-society', 'learn-history'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['understand-indian-society', 'learn-history'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 95,
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'http://ramachandraguha.in',
    publisherUrl: 'https://www.panmacmillan.co.in',
    libraryUrl: 'https://openlibrary.org/works/OL8160074W/India_After_Gandhi',
    legitimatePurchaseLinks: [{ label: 'Pan Macmillan India', url: 'https://www.panmacmillan.co.in', storeOrPlatform: 'Pan Macmillan' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL8160074W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Pan Macmillan / Picador',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Argumentative Indian',
    subtitle: 'Writings on Indian History, Culture and Identity',
    slug: 'the-argumentative-indian',
    authors: ['Amartya Sen'],
    primaryAuthor: 'Amartya Sen',
    description: 'Nobel Prize-winning economist Amartya Sen argues that India has a long and robust tradition of intellectual pluralism, public debate, rational skepticism, and heterodoxy that dates back millennia and serves as the bedrock of modern Indian democracy.',
    shortDescription: 'Amartya Sen’s seminal exploration of India’s long traditions of pluralism, debate, and rationalism.',
    summary: 'A collection of essays examining ancient debates between Krishna and Arjuna, Emperor Ashoka and Akbar’s religious tolerance, secularism, calendar systems, and India’s global contributions.',
    keyIdeas: [
      'The Tradition of Public Debate: Democracy in India is deeply rooted in ancient traditions of argumentative dialogue.',
      'Skepticism and Rationality: Ancient Indian philosophy includes rich non-religious and atheistic traditions (Lokāyata).',
      'Pluralist Identity: The danger of reducing a person’s multi-faceted identity to a single label.',
    ],
    whyRead: 'Provides a deeply erudite, historically grounded rebuttal to monocultural or sectarian interpretations of Indian identity.',
    importance: 'Winner of international acclaim for its celebration of democratic dialogue and heterodoxy.',
    whoShouldRead: ['Students of political philosophy, economics, and Indian society', 'Civil services aspirants'],
    bestFor: ['Indian philosophy', 'Democratic debate', 'Secularism', 'Intellectual history'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Basic familiarity with Indian history'],
    estimatedReadingTime: '8-10 hours',
    pageCount: 432,
    publicationYear: 2005,
    publisher: 'Farrar, Straus and Giroux / Penguin Books India',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: 'Penguin India Edition',
    latestEditionYear: 2006,
    editionPublisher: 'Penguin India',
    editionVerified: true,
    isbn10: '0141012110',
    isbn13: '978-0141012117',
    format: ['Paperback', 'Hardcover', 'Ebook'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-philosophy-epics',
    subjects: ['Indian Philosophy', 'Culture', 'Political Theory', 'History'],
    topics: ['Indian Philosophy', 'Indian Society', 'Democracy in India', 'Modern Indian Thinkers'],
    genres: ['Non-Fiction', 'Philosophy', 'Essays'],
    tags: ['amartya-sen', 'indian-culture', 'pluralism', 'nobel-laureate', 'philosophy'],
    bookTypes: ['Essay', 'Philosophy', 'Non Fiction', 'Academic'],
    readingPurposes: ['understand-indian-society', 'learn-philosophy'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['understand-indian-society', 'learn-philosophy'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: false,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 92,
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&auto=format&fit=crop&q=80',
    publisherUrl: 'https://www.penguinrandomhouse.in',
    libraryUrl: 'https://openlibrary.org/works/OL8160072W/The_Argumentative_Indian',
    legitimatePurchaseLinks: [{ label: 'Penguin India', url: 'https://www.penguinrandomhouse.in', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL8160072W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Penguin Books India',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Story of My Experiments with Truth',
    subtitle: 'An Autobiography',
    slug: 'my-experiments-with-truth',
    authors: ['Mahatma Gandhi'],
    primaryAuthor: 'Mahatma Gandhi',
    description: 'The Story of My Experiments with Truth is the autobiography of Mohandas K. Gandhi, covering his life from early childhood through to 1921. It describes his moral experiments with truth (satya), nonviolence (ahimsa), diet, and self-restraint.',
    shortDescription: 'Mahatma Gandhi’s classic autobiography detailing his spiritual, moral, and political experiments.',
    summary: 'Recounts Gandhi’s student days in London, his transformative 21 years in South Africa developing Satyagraha, and his return to lead the Indian national movement.',
    keyIdeas: [
      'Ahimsa as Active Love: Nonviolence is not passive resignation, but the active moral courage of truth.',
      'Satyagraha (Soul Force): Standing firm on truth and justice without hatred toward the adversary.',
      'Self-Purification: True political leadership begins with internal moral discipline and humility.',
    ],
    whyRead: 'A profound, intimate record of one of history’s greatest moral and spiritual figures testing ethics in the crucible of real struggle.',
    importance: 'Recognized as one of the "100 Best Spiritual Books of the 20th Century" by HarperCollins.',
    whoShouldRead: ['Students of history and ethics', 'Civil rights and public leadership enthusiasts'],
    bestFor: ['Nonviolence', 'Moral philosophy', 'Indian freedom movement', 'Ethics'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '12-14 hours',
    pageCount: 528,
    publicationYear: 1927,
    publisher: 'Navajivan Publishing House',
    countryOfOrigin: 'India',
    language: 'English (Translated from Gujarati)',
    latestKnownEdition: 'Navajivan Trust Standard Edition',
    latestEditionYear: 2008,
    editionPublisher: 'Navajivan Publishing House',
    editionVerified: true,
    isbn10: '817229008X',
    isbn13: '978-8172290085',
    format: ['Paperback', 'Public Domain Digital'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-philosophy-epics',
    subjects: ['Autobiography', 'Indian History', 'Ethics', 'Nonviolent Resistance'],
    topics: ['Mahatma Gandhi', 'Satyagraha', 'Ahimsa', 'Moral Philosophy', 'Freedom Struggle'],
    genres: ['Autobiography', 'Classic', 'Non-Fiction'],
    tags: ['gandhi', 'satyagraha', 'freedom-struggle', 'autobiography', 'public-domain'],
    bookTypes: ['Autobiography', 'Classic', 'Public Domain'],
    readingPurposes: ['understand-indian-society', 'learn-philosophy'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['understand-indian-society'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 96,
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL107872W/My_Experiments_with_Truth',
    legitimatePurchaseLinks: [{ label: 'Navajivan Trust', url: 'https://www.navajivantrust.org', storeOrPlatform: 'Navajivan Trust' }],
    legitimateDigitalLinks: [{ label: 'Gandhi Heritage Portal Text', url: 'https://www.gandhiheritageportal.org', type: 'PUBLIC_DOMAIN' }],
    isPublicDomain: true,
    source: 'Navajivan Publishing House / Gandhi Heritage Portal',
    sourceType: 'PUBLIC_DOMAIN',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Public Domain Verified',
    status: 'PUBLISHED',
  },
  {
    title: 'The Wonder That Was India',
    subtitle: 'A Survey of the History and Culture of the Indian Sub-Continent',
    slug: 'the-wonder-that-was-india',
    authors: ['A.L. Basham'],
    primaryAuthor: 'A.L. Basham',
    description: 'A classic work on Indian history and culture, A.L. Basham’s The Wonder That Was India is an authoritative and empathetic survey of the civilization of the subcontinent from prehistory and the Harappan culture to the coming of the Muslims.',
    shortDescription: 'The landmark, authoritative survey of ancient Indian civilization, arts, religion, and social life.',
    summary: 'Detailed examination of ancient Indian statecraft, society, religion, philosophy, literature, art, music, science, and everyday life.',
    keyIdeas: [
      'Vibrant Secular & Material Culture: Ancient India was marked by immense joy in living, art, drama, and scientific innovation alongside spiritual inquiry.',
      'Philosophical Heterodoxy: The rich co-existence of Vedic, Buddhist, Jain, and materialist traditions.',
      'Scientific Contributions: Indian advances in mathematics (zero, decimal system), metallurgy, and medicine (Ayurveda).',
    ],
    whyRead: 'The standard single-volume reference for anyone studying the roots of ancient Indian civilization and cultural glory.',
    importance: 'Essential reading for Indian history students and UPSC civil services aspirants for decades.',
    whoShouldRead: ['History students', 'Civil services aspirants', 'Indology enthusiasts'],
    bestFor: ['Ancient Indian history', 'Indian art and architecture', 'Sanskrit literature'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Interest in ancient history'],
    estimatedReadingTime: '20-25 hours',
    pageCount: 572,
    publicationYear: 1954,
    publisher: 'Sidgwick & Jackson / Picador India',
    countryOfOrigin: 'United Kingdom',
    language: 'English',
    latestKnownEdition: 'Picador India Revised Edition',
    latestEditionYear: 2004,
    editionPublisher: 'Picador India',
    editionVerified: true,
    isbn10: '033043909X',
    isbn13: '978-0330439091',
    format: ['Paperback', 'Hardcover'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-history-civilisation',
    subjects: ['Ancient India', 'Civilization', 'Indology', 'Indian Philosophy'],
    topics: ['Ancient India', 'Vedic Culture', 'Mauryan Empire', 'Gupta Golden Age'],
    genres: ['History', 'Academic Reference', 'Non-Fiction'],
    tags: ['ancient-india', 'basham', 'indology', 'upsc-history', 'civilization'],
    bookTypes: ['History', 'Textbook', 'Reference'],
    readingPurposes: ['understand-indian-society', 'learn-history'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['understand-indian-society', 'learn-history'],
    country: 'United Kingdom',
    isIndianAuthor: false,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 93,
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL18193861W/The_Wonder_That_Was_India',
    legitimatePurchaseLinks: [{ label: 'Pan Macmillan India', url: 'https://www.panmacmillan.co.in', storeOrPlatform: 'Pan Macmillan' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL18193861W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Picador India',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    subtitle: 'From the Stone Age to the Silicon Age',
    slug: 'sapiens-a-brief-history-of-humankind',
    authors: ['Yuval Noah Harari'],
    primaryAuthor: 'Yuval Noah Harari',
    description: 'One hundred thousand years ago, at least six different species of humans inhabited Earth. Yet today there is only one—Homo sapiens. How did our species succeed in the battle for dominance? Yuval Noah Harari spans the whole of human history to explore how biology and history have defined us.',
    shortDescription: 'Yuval Noah Harari’s tour de force on how cognitive, agricultural, and scientific revolutions shaped humankind.',
    summary: 'Explores the Cognitive Revolution (fictional mythmaking), Agricultural Revolution (the luxury trap), the unification of humankind (money, empires, religions), and the Scientific Revolution.',
    keyIdeas: [
      'Shared Fictions: The unique ability of Sapiens to create and believe in imagined orders (money, corporations, nations) enables large-scale flexible cooperation.',
      'The Agricultural Trap: Farming yielded more food but also resulted in more labor, poorer nutrition, and social inequality.',
      'The Scientific Marriage with Imperialism: Admitting ignorance and seeking empirical data propelled unprecedented technological power.',
    ],
    whyRead: 'A breathtaking macro-historical perspective that challenges core assumptions about human progress and happiness.',
    importance: 'Over 25 million copies sold globally; recommended by Barack Obama, Bill Gates, and Mark Zuckerberg.',
    whoShouldRead: ['General readers curious about human evolution', 'Students of history and anthropology'],
    bestFor: ['World history', 'Anthropology', 'Big history', 'Human evolution'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '10-12 hours',
    pageCount: 464,
    publicationYear: 2011,
    publisher: 'Harper / Harvill Secker',
    countryOfOrigin: 'Israel',
    language: 'English (Translated from Hebrew)',
    latestKnownEdition: '10th Anniversary Edition',
    latestEditionYear: 2021,
    editionPublisher: 'Harper',
    editionVerified: true,
    isbn10: '0062316095',
    isbn13: '978-0062316097',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'history-civilizations',
    subcategory: 'world-history-anthropology',
    subjects: ['World History', 'Anthropology', 'Evolutionary Biology', 'Sociology'],
    topics: ['Cognitive Revolution', 'Agricultural Revolution', 'Imagined Orders', 'Scientific Revolution'],
    genres: ['Non-Fiction', 'History', 'Popular Science'],
    tags: ['sapiens', 'yuval-noah-harari', 'history', 'anthropology', 'bestseller'],
    bookTypes: ['Popular Science', 'History', 'Non Fiction'],
    readingPurposes: ['learn-history', 'understand-society'],
    careers: ['college-student', 'software-engineer', 'civil-services-aspirant'],
    goals: ['learn-history'],
    country: 'Israel',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 98,
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.ynharari.com/book/sapiens/',
    libraryUrl: 'https://openlibrary.org/works/OL17075678W/Sapiens',
    legitimatePurchaseLinks: [{ label: 'HarperCollins Store', url: 'https://www.harpercollins.com', storeOrPlatform: 'HarperCollins' }],
    legitimateDigitalLinks: [{ label: 'Author Book Website', url: 'https://www.ynharari.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Harper',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Guns, Germs, and Steel',
    subtitle: 'The Fates of Human Societies',
    slug: 'guns-germs-and-steel',
    authors: ['Jared Diamond'],
    primaryAuthor: 'Jared Diamond',
    description: 'Why did Eurasians conquer, displace, or decimate Native Americans, Africans, and Aboriginal Australians, rather than vice versa? Jared Diamond convincingly argues that geographical and environmental factors, not genetic superiorities, shaped the modern world.',
    shortDescription: 'Pulitzer Prize-winning environmental history explaining global inequality through geographic and ecological determinism.',
    summary: 'Details how biogeography, domesticable animal and plant species, and continental axes (East-West vs North-South) created early food surpluses and technological advantages.',
    keyIdeas: [
      'Environmental Determinism: History followed different courses for different peoples because of differences among peoples’ environments, not because of biological differences.',
      'East-West Axis Advantage: Eurasian crops and animals spread easily along similar latitudes and climates.',
      'Lethal Microbes: Farming populations living near domesticated livestock developed epidemic immunity that proved devastating to isolated populations.',
    ],
    whyRead: 'A foundational, rigorous antidote to racial and cultural supremacism in historical explanation.',
    importance: 'Winner of the Pulitzer Prize for General Non-Fiction and the Phi Beta Kappa Award in Science.',
    whoShouldRead: ['Students of world history, geography, and anthropology', 'UPSC aspirants'],
    bestFor: ['Geographical history', 'Ecology', 'World inequality', 'Anthropology'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['None'],
    estimatedReadingTime: '14-16 hours',
    pageCount: 480,
    publicationYear: 1997,
    publisher: 'W.W. Norton & Company',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '20th Anniversary Edition',
    latestEditionYear: 2017,
    editionPublisher: 'W.W. Norton & Company',
    editionVerified: true,
    isbn10: '0393354326',
    isbn13: '978-0393354324',
    format: ['Paperback', 'Hardcover', 'Ebook'],
    category: 'history-civilizations',
    subcategory: 'world-history-anthropology',
    subjects: ['World History', 'Geography', 'Ecology', 'Anthropology'],
    topics: ['Geographic Determinism', 'Domestication', 'Continental Axes', 'Infectious Disease History'],
    genres: ['Non-Fiction', 'History', 'Science'],
    tags: ['guns-germs-steel', 'jared-diamond', 'pulitzer-prize', 'history', 'geography'],
    bookTypes: ['Academic', 'History', 'Non Fiction'],
    readingPurposes: ['learn-history', 'understand-society'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['learn-history'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 94,
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL18193862W/Guns_Germs_and_Steel',
    legitimatePurchaseLinks: [{ label: 'W.W. Norton Store', url: 'https://wwnorton.com', storeOrPlatform: 'W.W. Norton' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL18193862W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'W.W. Norton',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Silk Roads: A New History of the World',
    subtitle: 'The Major Forces That Forged Global Civilisation',
    slug: 'the-silk-roads',
    authors: ['Peter Frankopan'],
    primaryAuthor: 'Peter Frankopan',
    description: 'For centuries, fame and fortune were to be found in the West—in the New World of the Americas. Today, it is the East which is calling those with ambition. Peter Frankopan reorients world history around the ancient trade corridors that connected the Mediterranean to China.',
    shortDescription: 'Peter Frankopan’s sweeping global history that recenters world civilization on the East and Central Asia.',
    summary: 'Traces the rise and fall of empires along the Silk Roads, examining the Silk Road, the Slave Road, the Gold Road, and the Petroleum Road.',
    keyIdeas: [
      'East-Centric World History: Central Asia and the Middle East were the true crossroads and intellectual engines of civilization for millennia.',
      'Trade as Culture Conduit: Ideas, religions, sciences, and plagues moved in tandem with silk and spices.',
    ],
    whyRead: 'Essential for understanding contemporary geopolitics, China’s Belt and Road Initiative, and Eurasian integration.',
    importance: 'International number one bestseller; translated into over 30 languages.',
    whoShouldRead: ['International relations students', 'World history enthusiasts', 'Geopolitics analysts'],
    bestFor: ['Global history', 'Geopolitics', 'Silk road trade', 'Central Asia'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['None'],
    estimatedReadingTime: '15-18 hours',
    pageCount: 656,
    publicationYear: 2015,
    publisher: 'Bloomsbury Publishing',
    countryOfOrigin: 'United Kingdom',
    language: 'English',
    latestKnownEdition: 'Illustrated Edition',
    latestEditionYear: 2018,
    editionPublisher: 'Bloomsbury',
    editionVerified: true,
    isbn10: '1408839997',
    isbn13: '978-1408839997',
    format: ['Paperback', 'Hardcover', 'Ebook'],
    category: 'history-civilizations',
    subcategory: 'world-history-anthropology',
    subjects: ['World History', 'Geopolitics', 'Trade Routes', 'Silk Road'],
    topics: ['Silk Road', 'Central Asia', 'Global Trade', 'Eurasian Empires'],
    genres: ['History', 'Non-Fiction'],
    tags: ['silk-roads', 'peter-frankopan', 'world-history', 'geopolitics', 'eurasia'],
    bookTypes: ['History', 'Academic', 'Non Fiction'],
    readingPurposes: ['learn-history', 'understand-society'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['learn-history'],
    country: 'United Kingdom',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 93,
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL17377599W/The_Silk_Roads',
    legitimatePurchaseLinks: [{ label: 'Bloomsbury Store', url: 'https://www.bloomsbury.com', storeOrPlatform: 'Bloomsbury' }],
    legitimateDigitalLinks: [{ label: 'Peter Frankopan Official', url: 'https://www.peterfrankopan.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Bloomsbury',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Meditations',
    subtitle: 'A New Translation and Philosophical Reflections',
    slug: 'meditations-marcus-aurelius',
    authors: ['Marcus Aurelius'],
    primaryAuthor: 'Marcus Aurelius',
    description: 'Written in Greek without any intention of publication, the Meditations of Marcus Aurelius offer a remarkable series of challenging spiritual reflections and exercises developed as the emperor struggled to understand himself and make sense of the universe while governing the Roman Empire.',
    shortDescription: 'The private spiritual journal of the Roman Emperor Marcus Aurelius on Stoic duty and tranquility.',
    summary: 'Timeless reflections on the dichotomy of control, accepting mortality (memento mori), overcoming resentment, performing civic duty without ego, and finding peace amidst turmoil.',
    keyIdeas: [
      'Dichotomy of Control: Focus entirely on your own thoughts, actions, and judgments; external events are beyond your control.',
      'Perception Shapes Reality: "You have power over your mind - not outside events. Realize this, and you will find strength."',
      'Memento Mori: Keep your inevitable mortality in mind to prioritize what genuinely matters each day.',
    ],
    whyRead: 'The gold standard of ancient Stoic wisdom. It is not an abstract theory book, but the raw daily therapy of the most powerful man in the ancient world.',
    importance: 'Preserved across two millennia, inspiring philosophers, world leaders, and modern cognitive-behavioral therapy (CBT).',
    whoShouldRead: ['Anyone dealing with anxiety or pressure', 'Leaders navigating chaos', 'Philosophy students'],
    bestFor: ['Stoicism', 'Emotional resilience', 'Mental discipline', 'Ancient philosophy'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '4-5 hours',
    pageCount: 200,
    publicationYear: 180,
    publisher: 'Public Domain / Modern Translations (Penguin Classics)',
    countryOfOrigin: 'Roman Empire',
    language: 'English (Translated from Ancient Greek)',
    originalLanguage: 'Ancient Greek',
    latestKnownEdition: 'Penguin Classics Translation (Gregory Hays)',
    latestEditionYear: 2002,
    editionPublisher: 'Modern Library / Penguin',
    editionVerified: true,
    isbn10: '0812968255',
    isbn13: '978-0812968255',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Public Domain Text'],
    category: 'philosophy-ethics',
    subcategory: 'stoicism-ancient-philosophy',
    subjects: ['Stoicism', 'Ancient Philosophy', 'Ethics', 'Self-Mastery'],
    topics: ['Marcus Aurelius', 'Stoic Discipline', 'Mental Toughness', 'Good Life'],
    genres: ['Philosophy', 'Classics', 'Non-Fiction'],
    tags: ['stoicism', 'philosophy', 'marcus-aurelius', 'classics', 'resilience', 'public-domain'],
    bookTypes: ['Philosophy', 'Classic', 'Public Domain', 'Non Fiction'],
    readingPurposes: ['learn-philosophy', 'build-habits'],
    careers: ['software-engineer', 'entrepreneur', 'college-student'],
    goals: ['learn-philosophy'],
    country: 'Italy',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 97,
    coverImage: 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL107871W/Meditations',
    legitimatePurchaseLinks: [{ label: 'Penguin Classics', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [
      { label: 'Project Gutenberg Free Public Domain Text', url: 'https://www.gutenberg.org/ebooks/2680', type: 'PUBLIC_DOMAIN' },
      { label: 'MIT Internet Classics Archive', url: 'http://classics.mit.edu/Antoninus/meditations.html', type: 'PUBLIC_DOMAIN' },
    ],
    isPublicDomain: true,
    publicDomainSourceUrl: 'https://www.gutenberg.org/ebooks/2680',
    source: 'Project Gutenberg / Open Library',
    sourceType: 'PUBLIC_DOMAIN',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Public Domain Verified',
    status: 'PUBLISHED',
  },
  {
    title: 'Man’s Search for Meaning',
    subtitle: 'The Classic Tribute to Hope from the Holocaust',
    slug: 'mans-search-for-meaning',
    authors: ['Viktor E. Frankl'],
    primaryAuthor: 'Viktor E. Frankl',
    description: 'Psychiatrist Viktor Frankl’s memoir has riveted generations of readers with its descriptions of life in Nazi death camps and its lessons for spiritual survival. Frankl argues that we cannot avoid suffering, but we can choose how to cope with it, find meaning in it, and move forward.',
    shortDescription: 'Viktor Frankl’s harrowing memoir and psychotherapeutic theory on finding purpose even in immense suffering.',
    summary: 'Chronicles Frankl’s experiences in Auschwitz and Dachau, followed by the introduction of Logotherapy—the belief that striving to find meaning in life is the primary human motivational force.',
    keyIdeas: [
      'The Last Human Freedom: "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances."',
      'Meaning in Suffering: Suffering ceases to be suffering the moment it finds a meaning.',
      'Responsibility to Life: It did not really matter what we expected from life, but rather what life expected from us.',
    ],
    whyRead: 'One of the most life-altering books ever written, providing unbreakable psychological endurance and perspective.',
    importance: 'Selected by the Library of Congress as one of the ten most influential books in America.',
    whoShouldRead: ['Anyone experiencing existential crisis, grief, or adversity', 'Psychology and philosophy students'],
    bestFor: ['Existential meaning', 'Logotherapy', 'Resilience', 'Overcoming trauma'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '4-5 hours',
    pageCount: 165,
    publicationYear: 1946,
    publisher: 'Beacon Press',
    countryOfOrigin: 'Austria',
    language: 'English (Translated from German)',
    latestKnownEdition: 'Beacon Press Gift Edition',
    latestEditionYear: 2006,
    editionPublisher: 'Beacon Press',
    editionVerified: true,
    isbn10: '080701429X',
    isbn13: '978-0807014295',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'philosophy-ethics',
    subcategory: 'existentialism-meaning',
    subjects: ['Existentialism', 'Psychotherapy', 'Logotherapy', 'Holocaust Memoir'],
    topics: ['Viktor Frankl', 'Meaning of Life', 'Logotherapy', 'Existential Resilience'],
    genres: ['Memoir', 'Philosophy', 'Psychology', 'Classic'],
    tags: ['viktor-frankl', 'meaning', 'logotherapy', 'philosophy', 'resilience'],
    bookTypes: ['Memoir', 'Philosophy', 'Classic', 'Non Fiction'],
    readingPurposes: ['learn-philosophy', 'learn-psychology'],
    careers: ['college-student', 'software-engineer', 'entrepreneur'],
    goals: ['learn-philosophy'],
    country: 'Austria',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 98,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL18193863W/Mans_Search_for_Meaning',
    legitimatePurchaseLinks: [{ label: 'Beacon Press Store', url: 'https://www.beacon.org', storeOrPlatform: 'Beacon Press' }],
    legitimateDigitalLinks: [{ label: 'Viktor Frankl Institute Portal', url: 'https://www.viktorfrankl.org', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Beacon Press',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Justice: What’s the Right Thing to Do?',
    subtitle: 'A Masterclass in Moral and Political Philosophy',
    slug: 'justice-whats-the-right-thing-to-do',
    authors: ['Michael J. Sandel'],
    primaryAuthor: 'Michael J. Sandel',
    description: 'Harvard professor Michael J. Sandel tests moral dilemmas against the greatest philosophical ideas of utilitarianism, Kantian ethics, libertarianism, Aristotle’s teleology, and civic virtue in this engaging exploration of justice.',
    shortDescription: 'Michael Sandel’s famous Harvard course in book form, probing moral philosophy, markets, and the common good.',
    summary: 'Compares Jeremy Bentham’s utilitarianism, Immanuel Kant’s categorical imperative, John Rawls’ veil of ignorance, and Aristotle’s purpose-driven ethics on real-world dilemmas.',
    keyIdeas: [
      'Utilitarianism vs Individual Rights: The moral flaws in measuring human lives strictly by aggregate utility.',
      'The Veil of Ignorance (Rawls): Fair social contracts are those chosen when nobody knows their social standing, wealth, or talents.',
      'Civic Virtue & The Common Good: A just society cannot be achieved solely through maximizing utility or securing freedom of choice; it must reason together about the good life.',
    ],
    whyRead: 'Sharpens ethical reasoning and equips citizens to debate hot-button public policies with intellectual rigor.',
    importance: 'Adapted from Harvard’s most popular undergraduate course with tens of millions of viewers worldwide.',
    whoShouldRead: ['Law and political philosophy students', 'Policy makers and civil servants', 'Debaters'],
    bestFor: ['Moral philosophy', 'Political theory', 'Ethical dilemmas', 'Civic justice'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['None'],
    estimatedReadingTime: '8-10 hours',
    pageCount: 320,
    publicationYear: 2009,
    publisher: 'Farrar, Straus and Giroux',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2009,
    editionPublisher: 'Farrar, Straus and Giroux',
    editionVerified: true,
    isbn10: '0374532508',
    isbn13: '978-0374532505',
    format: ['Paperback', 'Hardcover', 'Ebook'],
    category: 'philosophy-ethics',
    subcategory: 'moral-philosophy-justice',
    subjects: ['Moral Philosophy', 'Political Philosophy', 'Ethics', 'Justice'],
    topics: ['Utilitarianism', 'Kant Ethics', 'John Rawls', 'Veil of Ignorance', 'Civic Virtue'],
    genres: ['Philosophy', 'Non-Fiction', 'Academic'],
    tags: ['justice', 'michael-sandel', 'harvard', 'ethics', 'moral-philosophy'],
    bookTypes: ['Philosophy', 'Academic', 'Non Fiction'],
    readingPurposes: ['learn-philosophy', 'understand-society'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['learn-philosophy'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 93,
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL15848246W/Justice',
    legitimatePurchaseLinks: [{ label: 'Macmillan Store', url: 'https://us.macmillan.com', storeOrPlatform: 'Macmillan' }],
    legitimateDigitalLinks: [{ label: 'Harvard Justice Course Portal', url: 'http://justiceharvard.org', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Farrar, Straus and Giroux',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Six Easy Pieces: Essentials of Physics',
    subtitle: 'Explained by Its Most Brilliant Teacher',
    slug: 'six-easy-pieces-richard-feynman',
    authors: ['Richard P. Feynman'],
    primaryAuthor: 'Richard P. Feynman',
    description: 'Learn physics from the Nobel Prize-winning master. Six Easy Pieces is a compilation of the six most accessible chapters from Richard Feynman’s landmark Lectures on Physics, introducing atoms, basic physics, the relation of physics to other sciences, conservation of energy, gravity, and quantum behavior.',
    shortDescription: 'Nobel laureate Richard Feynman’s brilliant, intuitive introduction to the core principles of physics.',
    summary: 'Explains atoms in motion, basic conservation laws, gravitation, and the enigmatic dual nature of quantum mechanics without requiring advanced calculus.',
    keyIdeas: [
      'The Atomic Hypothesis: All things are made of atoms—little particles that move around in perpetual motion, attracting each other when a little distance apart, but repelling upon being squeezed.',
      'Conservation of Energy: There is a numerical quantity that does not change in the manifold changes which nature undergoes.',
      'Quantum Paradox: Quantum behavior is fundamentally strange, yet obeys precise mathematical rules.',
    ],
    whyRead: 'A breathtakingly clear, joyful introduction to physics that strips away tedious rote mechanics.',
    importance: 'Drawn from the legendary Caltech lectures that revolutionized science education worldwide.',
    whoShouldRead: ['High school and college students', 'Engineers wanting physics intuition', 'Science enthusiasts'],
    bestFor: ['Physics intuition', 'Quantum basics', 'Scientific mindset', 'Feynman pedagogy'],
    readingLevel: 'BEGINNER',
    prerequisites: ['Basic high-school science curiosity'],
    estimatedReadingTime: '4-5 hours',
    pageCount: 176,
    publicationYear: 1994,
    publisher: 'Basic Books',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: 'Basic Books 20th Anniversary Edition',
    latestEditionYear: 2011,
    editionPublisher: 'Basic Books',
    editionVerified: true,
    isbn10: '0465025277',
    isbn13: '978-0465025275',
    format: ['Paperback', 'Ebook', 'Audiobook'],
    category: 'science-physics-nature',
    subcategory: 'physics-quantum-mechanics',
    subjects: ['Physics', 'Quantum Mechanics', 'Science Education', 'Thermodynamics'],
    topics: ['Atomic Theory', 'Conservation of Energy', 'Gravitation', 'Quantum Behavior', 'Feynman'],
    genres: ['Science', 'Non-Fiction', 'Classic'],
    tags: ['feynman', 'physics', 'science', 'quantum', 'caltech'],
    bookTypes: ['Popular Science', 'Classic', 'Non Fiction'],
    readingPurposes: ['learn-science', 'learn-physics'],
    careers: ['software-engineer', 'college-student', 'data-scientist'],
    goals: ['learn-science'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 94,
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL18193864W/Six_Easy_Pieces',
    legitimatePurchaseLinks: [{ label: 'Basic Books Store', url: 'https://www.hachettebookgroup.com', storeOrPlatform: 'Basic Books' }],
    legitimateDigitalLinks: [{ label: 'Caltech Feynman Lectures Online', url: 'https://www.feynmanlectures.caltech.edu', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Basic Books / Perseus',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'A Brief History of Time',
    subtitle: 'From the Big Bang to Black Holes',
    slug: 'a-brief-history-of-time',
    authors: ['Stephen Hawking'],
    primaryAuthor: 'Stephen Hawking',
    description: 'A landmark volume in science writing by one of the great minds of our time, Stephen Hawking’s book explores the most profound questions of existence: How did the universe begin? Can time run backward? Is there an ultimate theory of everything?',
    shortDescription: 'Stephen Hawking’s world-famous guide to cosmology, black holes, space-time, and the universe.',
    summary: 'Explains special and general relativity, the expanding universe, black holes, Hawking radiation, the arrow of time, and the quest to unify general relativity with quantum mechanics.',
    keyIdeas: [
      'The Expanding Universe & The Big Bang: Space itself is expanding from a singular point in the past.',
      'Black Holes & Hawking Radiation: Black holes are not completely black, but emit thermal radiation due to quantum vacuum effects.',
      'The Arrow of Time: Thermodynamic, psychological, and cosmological arrows all align toward increasing entropy.',
    ],
    whyRead: 'Brought theoretical physics and cosmological wonders to tens of millions of ordinary readers with warmth and wit.',
    importance: 'Sold over 25 million copies worldwide; spent 237 weeks on the Sunday Times bestseller list.',
    whoShouldRead: ['Anyone curious about the cosmos, physics, and the universe', 'Students of astronomy and mathematics'],
    bestFor: ['Cosmology', 'Black holes', 'General relativity', 'Theoretical physics'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '6-7 hours',
    pageCount: 212,
    publicationYear: 1988,
    publisher: 'Bantam Books',
    countryOfOrigin: 'United Kingdom',
    language: 'English',
    latestKnownEdition: 'Updated and Expanded Edition',
    latestEditionYear: 2017,
    editionPublisher: 'Bantam Books',
    editionVerified: true,
    isbn10: '0553380168',
    isbn13: '978-0553380163',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'science-physics-nature',
    subcategory: 'astronomy-cosmology',
    subjects: ['Cosmology', 'Theoretical Physics', 'Black Holes', 'Astrophysics'],
    topics: ['Big Bang', 'Black Holes', 'Hawking Radiation', 'General Relativity', 'Quantum Mechanics'],
    genres: ['Science', 'Non-Fiction', 'Bestseller'],
    tags: ['hawking', 'cosmology', 'physics', 'universe', 'black-holes'],
    bookTypes: ['Popular Science', 'Classic', 'Non Fiction'],
    readingPurposes: ['learn-science', 'learn-physics'],
    careers: ['college-student', 'software-engineer', 'data-scientist'],
    goals: ['learn-science'],
    country: 'United Kingdom',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 97,
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.hawking.org.uk',
    libraryUrl: 'https://openlibrary.org/works/OL18193865W/A_Brief_History_of_Time',
    legitimatePurchaseLinks: [{ label: 'Bantam Store', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'Stephen Hawking Official Archive', url: 'https://www.hawking.org.uk', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Bantam Books',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Gene: An Intimate History',
    subtitle: 'The Story of the Master Molecule of Life',
    slug: 'the-gene-an-intimate-history',
    authors: ['Siddhartha Mukherjee'],
    primaryAuthor: 'Siddhartha Mukherjee',
    description: 'Dr. Siddhartha Mukherjee weaves science, social history, and personal memoir to tell the story of the birth, growth, and future of one of the most powerful and dangerous ideas in the history of science: the gene, the fundamental unit of heredity.',
    shortDescription: 'Pulitzer Prize-winner Siddhartha Mukherjee’s masterwork on the history, science, and moral frontier of genetics.',
    summary: 'Chronicles the journey of genetics from Gregor Mendel’s pea plants and Darwinian natural selection, through the double helix discovery, the Human Genome Project, CRISPR gene editing, and the future of human biology.',
    keyIdeas: [
      'The Gene as the Code of Life: The gene is to biology what the atom is to physics and the byte to computer science.',
      'Epigenetics & Environment: Genes provide the blueprint, but cellular and environmental interactions determine how those genes express.',
      'The Ethics of Human Gene Editing: CRISPR gives humanity the godlike power to rewrite our own code; we must exercise moral wisdom.',
    ],
    whyRead: 'A masterpiece of scientific storytelling that explains the molecular code defining who we are and what our future holds.',
    importance: 'Number one New York Times bestseller; adapted into a major PBS documentary by Ken Burns.',
    whoShouldRead: ['Biology and medical students', 'Science readers', 'Anyone interested in DNA and biotechnology'],
    bestFor: ['Genetics', 'Biotechnology', 'Medical history', 'CRISPR ethics'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['None'],
    estimatedReadingTime: '16-18 hours',
    pageCount: 608,
    publicationYear: 2016,
    publisher: 'Scribner (Simon & Schuster)',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2016,
    editionPublisher: 'Scribner',
    editionVerified: true,
    isbn10: '1476733523',
    isbn13: '978-1476733524',
    format: ['Hardcover', 'Paperback', 'Ebook', 'Audiobook'],
    category: 'science-physics-nature',
    subcategory: 'biology-genetics',
    subjects: ['Genetics', 'Biology', 'Biotechnology', 'History of Science'],
    topics: ['DNA', 'CRISPR', 'Human Genome Project', 'Gregor Mendel', 'Epigenetics'],
    genres: ['Science', 'History', 'Non-Fiction'],
    tags: ['siddhartha-mukherjee', 'the-gene', 'genetics', 'dna', 'biology', 'crispr'],
    bookTypes: ['Popular Science', 'History', 'Non Fiction'],
    readingPurposes: ['learn-science', 'understand-society'],
    careers: ['data-scientist', 'college-student'],
    goals: ['learn-science'],
    country: 'United States',
    isIndianAuthor: true,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 96,
    coverImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL17377600W/The_Gene',
    legitimatePurchaseLinks: [{ label: 'Simon & Schuster Store', url: 'https://www.simonandschuster.com', storeOrPlatform: 'Simon & Schuster' }],
    legitimateDigitalLinks: [{ label: 'Siddhartha Mukherjee Portal', url: 'http://siddharthamukherjee.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Scribner / Simon & Schuster',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Psychology of Money',
    subtitle: 'Timeless lessons on wealth, greed, and happiness',
    slug: 'the-psychology-of-money',
    authors: ['Morgan Housel'],
    primaryAuthor: 'Morgan Housel',
    description: 'Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. Morgan Housel shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life’s most important topics.',
    shortDescription: '19 insightful stories demonstrating that financial success is driven by behavioral discipline, not spreadsheet math.',
    summary: 'Focuses on the distinction between being rich vs wealthy, the power of compounding time, understanding what is "enough", and managing risk without succumbing to ego.',
    keyIdeas: [
      'Behavior Over Intelligence: Financial outcomes are determined by emotional control rather than technical finance degrees.',
      'Compounding & Time Horizon: Warren Buffett’s real secret is that he started investing at age 10 and never interrupted compounding.',
      'Getting Wealthy vs Staying Wealthy: Staying wealthy requires paranoia, frugality, and surviving down cycles.',
      'The Value of Freedom: The highest dividend money pays is the ability to control your own time.',
      'Room for Error: Always maintain a margin of safety for things you cannot foresee.',
    ],
    whyRead: 'A refreshing, highly readable antidote to get-rich-quick schemes that establishes healthy lifelong financial habits.',
    importance: 'Global bestseller translated into over 50 languages with millions of readers across world financial capitals.',
    whoShouldRead: ['Anyone starting their personal investment or career journey', 'Investors seeking behavioral discipline'],
    bestFor: ['Personal finance', 'Money mindset', 'Behavioral economics', 'Long-term investing'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '4-5 hours',
    pageCount: 256,
    publicationYear: 2020,
    publisher: 'Harriman House',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2020,
    editionPublisher: 'Harriman House',
    editionVerified: true,
    isbn10: '0857197681',
    isbn13: '978-0857197689',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'finance-investing',
    subcategory: 'personal-finance-wealth-creation',
    subjects: ['Personal Finance', 'Behavioral Economics', 'Wealth Management'],
    topics: ['Psychology of Money', 'Financial Independence', 'Compounding', 'Budgeting'],
    genres: ['Non-Fiction', 'Finance', 'Psychology'],
    tags: ['money', 'finance', 'investing', 'bestseller', 'wealth'],
    bookTypes: ['Business', 'Self Help', 'Non Fiction'],
    readingPurposes: ['improve-financial-knowledge', 'build-habits'],
    careers: ['investor-finance', 'software-engineer', 'entrepreneur', 'college-student'],
    goals: ['improve-financial-knowledge'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 97,
    coverImage: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    publisherUrl: 'https://harriman-house.com/psychologyofmoney',
    libraryUrl: 'https://openlibrary.org/works/OL21867807W/The_Psychology_of_Money',
    legitimatePurchaseLinks: [{ label: 'Harriman House Publisher', url: 'https://harriman-house.com', storeOrPlatform: 'Harriman House' }],
    legitimateDigitalLinks: [{ label: 'Collaborative Fund Blog', url: 'https://collabfund.com/blog', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Harriman House',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Intelligent Investor',
    subtitle: 'The Definitive Book on Value Investing',
    slug: 'the-intelligent-investor',
    authors: ['Benjamin Graham'],
    primaryAuthor: 'Benjamin Graham',
    description: 'The greatest investment advisor of the twentieth century, Benjamin Graham, taught and inspired people worldwide. Graham’s philosophy of "value investing"—which shields investors from substantial error and teaches them to develop long-term strategies—has made The Intelligent Investor the stock market bible.',
    shortDescription: 'Benjamin Graham’s timeless guide on margin of safety, Mr. Market, and value investing.',
    summary: 'Distinguishes between investment vs speculation, introduces the allegory of Mr. Market, and establishes the essential concept of Margin of Safety.',
    keyIdeas: [
      'Margin of Safety: Always purchase securities at a substantial discount to their conservative intrinsic value.',
      'Mr. Market: The market is a manic-depressive business partner whose daily quotations should be exploited, not feared.',
      'Defensive vs Enterprising Investor: Match your investment strategy to the amount of time and effort you are willing to commit.',
    ],
    whyRead: 'Warren Buffett called it "by far the best book on investing ever written." It provides the emotional ballast needed to invest safely.',
    importance: 'The foundational text of modern value investing and security analysis since 1949.',
    whoShouldRead: ['Stock investors', 'Finance students', 'Anyone building a retirement portfolio'],
    bestFor: ['Value investing', 'Margin of safety', 'Fundamental analysis', 'Stock market discipline'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Basic financial numeracy'],
    estimatedReadingTime: '15-18 hours',
    pageCount: 640,
    publicationYear: 1949,
    publisher: 'Harper Business',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: 'Revised Edition with Commentary by Jason Zweig',
    latestEditionYear: 2006,
    editionPublisher: 'Harper Business',
    editionVerified: true,
    isbn10: '0060555661',
    isbn13: '978-0060555665',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'finance-investing',
    subcategory: 'value-investing-markets',
    subjects: ['Value Investing', 'Stock Market', 'Security Analysis', 'Personal Finance'],
    topics: ['Margin of Safety', 'Mr Market', 'Intrinsic Value', 'Defensive Investor'],
    genres: ['Finance', 'Business', 'Classic'],
    tags: ['benjamin-graham', 'warren-buffett', 'value-investing', 'stocks', 'investing-bible'],
    bookTypes: ['Business', 'Classic', 'Reference'],
    readingPurposes: ['improve-financial-knowledge'],
    careers: ['investor-finance', 'entrepreneur'],
    goals: ['improve-financial-knowledge'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 96,
    coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL18193866W/The_Intelligent_Investor',
    legitimatePurchaseLinks: [{ label: 'HarperCollins Store', url: 'https://www.harpercollins.com', storeOrPlatform: 'HarperCollins' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL18193866W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Harper Business',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: '1984',
    subtitle: 'A Dystopian Masterpiece',
    slug: '1984-george-orwell',
    authors: ['George Orwell'],
    primaryAuthor: 'George Orwell',
    description: 'Written in 1948, 1984 was George Orwell’s chilling prophecy about the future. And while 1984 has come and gone, his dystopian vision of a government that will do anything to control narrative, thought, and reality is timelier than ever.',
    shortDescription: 'George Orwell’s definitive dystopian classic on totalitarianism, Big Brother, and truth control.',
    summary: 'Follows Winston Smith in the totalitarian superstate of Oceania as he wrestles with the Ministry of Truth, Newspeak, doublethink, and rebellion against the Party.',
    keyIdeas: [
      'Control of History: "Who controls the past controls the future. Who controls the present controls the past."',
      'Newspeak: The deliberate simplification of language to make dissident thought literally impossible.',
      'Doublethink: The power of holding two contradictory beliefs in one’s mind simultaneously, and accepting both of them.',
    ],
    whyRead: 'A piercing literary defense of objective truth, free thought, and individual privacy against surveillance states.',
    importance: 'Coined terms that define modern political discourse: Big Brother, Orwellian, Thought Police, Doublethink.',
    whoShouldRead: ['Readers of literature', 'Students of political theory and humanities'],
    bestFor: ['Dystopian fiction', 'Political literature', 'Totalitarianism critique', 'Literary prose'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '6-8 hours',
    pageCount: 328,
    publicationYear: 1949,
    publisher: 'Secker & Warburg / Penguin Classics',
    countryOfOrigin: 'United Kingdom',
    language: 'English',
    latestKnownEdition: 'Penguin Classics Centennial Edition',
    latestEditionYear: 2021,
    editionPublisher: 'Penguin Classics',
    editionVerified: true,
    isbn10: '0141036141',
    isbn13: '978-0141036144',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Public Domain (in select jurisdictions)'],
    category: 'literature-classics',
    subcategory: 'dystopian-philosophical-fiction',
    subjects: ['Dystopian Fiction', 'Political Satire', 'Classic Literature', 'Surveillance'],
    topics: ['Big Brother', 'Totalitarianism', 'Newspeak', 'Doublethink', 'Winston Smith'],
    genres: ['Fiction', 'Dystopian', 'Classic'],
    tags: ['george-orwell', '1984', 'dystopian', 'classic', 'political-fiction'],
    bookTypes: ['Fiction', 'Classic', 'Novel'],
    readingPurposes: ['read-great-fiction', 'understand-society'],
    careers: ['college-student'],
    goals: ['read-great-fiction'],
    country: 'United Kingdom',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 98,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL1168007W/1984',
    legitimatePurchaseLinks: [{ label: 'Penguin Classics Store', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'The Orwell Foundation', url: 'https://www.orwellfoundation.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Secker & Warburg / Penguin',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Malgudi Days',
    subtitle: 'Classic Stories from South India',
    slug: 'malgudi-days',
    authors: ['R.K. Narayan'],
    primaryAuthor: 'R.K. Narayan',
    description: 'Malgudi Days is a collection of 32 charming, perceptive short stories by R.K. Narayan set in the fictional South Indian town of Malgudi. With gentle irony and affectionate humor, Narayan portrays the daily lives, aspirations, and quirks of ordinary people.',
    shortDescription: 'R.K. Narayan’s timeless, heartwarming short story collection set in the iconic fictional town of Malgudi.',
    summary: 'Features beloved tales including "An Astrologer’s Day", "The Missing Mail", "Swami and Friends", and "The Blind Dog", capturing universal human nature through simple Indian life.',
    keyIdeas: [
      'The Magic of the Everyday: Finding deep philosophical humor, tragedy, and charm in the most ordinary daily occurrences.',
      'Compassionate Irony: Narayan never mocks his characters; he observes their quirks with profound human warmth.',
    ],
    whyRead: 'The quintessence of Indian English literature; evocative, gentle, and utterly unforgettable.',
    importance: 'Adapted into the legendary TV series directed by Shankar Nag; celebrated worldwide by Graham Greene.',
    whoShouldRead: ['All readers of literature and short stories', 'Students of Indian writing in English'],
    bestFor: ['Indian fiction', 'Short stories', 'Humor and satire', 'South Indian life'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '5-7 hours',
    pageCount: 272,
    publicationYear: 1943,
    publisher: 'Indian Thought Publications / Penguin Classics',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: 'Penguin Classics Edition',
    latestEditionYear: 2006,
    editionPublisher: 'Penguin Classics',
    editionVerified: true,
    isbn10: '0143039652',
    isbn13: '978-0143039655',
    format: ['Paperback', 'Ebook', 'Audiobook'],
    category: 'literature-classics',
    subcategory: 'indian-literature-english',
    subjects: ['Short Stories', 'Indian Literature', 'Fiction', 'South India'],
    topics: ['Malgudi', 'An Astrologer Day', 'Swami and Friends', 'Indian English Literature'],
    genres: ['Fiction', 'Short Stories', 'Classic'],
    tags: ['rk-narayan', 'malgudi-days', 'indian-literature', 'classics', 'short-stories'],
    bookTypes: ['Fiction', 'Short Stories', 'Classic'],
    readingPurposes: ['read-great-fiction', 'understand-indian-society'],
    careers: ['college-student'],
    goals: ['read-great-fiction'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 95,
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL18193867W/Malgudi_Days',
    legitimatePurchaseLinks: [{ label: 'Penguin India Store', url: 'https://www.penguinrandomhouse.in', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL18193867W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Penguin India / Indian Thought Publications',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The God of Small Things',
    subtitle: 'A Novel of Family, Caste, and Love in Kerala',
    slug: 'the-god-of-small-things',
    authors: ['Arundhati Roy'],
    primaryAuthor: 'Arundhati Roy',
    description: 'Set in Ayemenem, Kerala, The God of Small Things is the story of fraternal twins Rahel and Estha, whose lives are shattered by the "Love Laws" that lay down who should be loved, and how, and how much. Won the 1997 Booker Prize.',
    shortDescription: 'Arundhati Roy’s Booker Prize-winning lyrical masterpiece on caste, forbidden love, and childhood in Kerala.',
    summary: 'A non-linear narrative exploring family secrets, the tragic fate of Velutha the untouchable carpenter, political communism, and the vulnerability of children.',
    keyIdeas: [
      'The Power of Small Things: Small moments, casual words, and unnoticed gestures often alter the trajectory of human lives forever.',
      'The Cruelty of the Love Laws: How entrenched societal caste norms violently enforce conformity.',
      'Sensory Prose: Roy’s rich, tactile language brings the lush landscapes and river life of Kerala vividly to life.',
    ],
    whyRead: 'A breathtakingly original novel that showcases the linguistic virtuosity of Indian English literature.',
    importance: 'Won the Man Booker Prize in 1997 and became the biggest-selling book by a non-expatriate Indian author.',
    whoShouldRead: ['Lovers of literary fiction', 'Students of postcolonial and Indian literature'],
    bestFor: ['Literary fiction', 'Kerala culture', 'Social commentary', 'Lyrical prose'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['None'],
    estimatedReadingTime: '8-10 hours',
    pageCount: 336,
    publicationYear: 1997,
    publisher: 'IndiaInk / Random House',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: '20th Anniversary Edition',
    latestEditionYear: 2017,
    editionPublisher: 'Penguin Random House India',
    editionVerified: true,
    isbn10: '0812979656',
    isbn13: '978-0812979657',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'literature-classics',
    subcategory: 'indian-literature-english',
    subjects: ['Indian Literature', 'Booker Prize', 'Caste Society', 'Family Saga'],
    topics: ['Kerala', 'Ayemenem', 'Love Laws', 'Twins', 'Indian Fiction'],
    genres: ['Fiction', 'Literary Fiction', 'Contemporary Classic'],
    tags: ['arundhati-roy', 'booker-prize', 'god-of-small-things', 'kerala', 'indian-novel'],
    bookTypes: ['Fiction', 'Novel', 'Classic'],
    readingPurposes: ['read-great-fiction', 'understand-indian-society'],
    careers: ['college-student'],
    goals: ['read-great-fiction'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 96,
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL8160079W/The_God_of_Small_Things',
    legitimatePurchaseLinks: [{ label: 'Penguin India Store', url: 'https://www.penguinrandomhouse.in', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'Booker Prize Official Record', url: 'https://thebookerprizes.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Penguin Random House India',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Steve Jobs',
    subtitle: 'The Exclusive Biography',
    slug: 'steve-jobs-walter-isaacson',
    authors: ['Walter Isaacson'],
    primaryAuthor: 'Walter Isaacson',
    description: 'Based on more than forty interviews with Steve Jobs conducted over two years—as well as interviews with more than a hundred family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries.',
    shortDescription: 'Walter Isaacson’s definitive, unvarnished biography of Apple co-founder Steve Jobs.',
    summary: 'Details Jobs’ early life, the founding of Apple in a garage, NeXT, Pixar, his return to rescue Apple, and the creation of iMac, iPod, iPhone, and iPad.',
    keyIdeas: [
      'Intersection of Humanities and Technology: Real innovation occurs at the intersection of liberal arts and high technology.',
      'Reality Distortion Field: An uncanny ability to convince team members that the impossible could be achieved.',
      'Simplicity & End-to-End Control: Designing unified ecosystems where hardware, software, and services integrate seamlessly.',
    ],
    whyRead: 'The quintessential biography of modern creative entrepreneurship and uncompromising product design.',
    importance: 'Global number one bestseller with millions of copies sold across world tech hubs.',
    whoShouldRead: ['Entrepreneurs and designers', 'Software and hardware builders', 'Tech enthusiasts'],
    bestFor: ['Tech innovation', 'Product design', 'Apple history', 'Executive leadership'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '18-22 hours',
    pageCount: 656,
    publicationYear: 2011,
    publisher: 'Simon & Schuster',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2011,
    editionPublisher: 'Simon & Schuster',
    editionVerified: true,
    isbn10: '1451648537',
    isbn13: '978-1451648539',
    format: ['Hardcover', 'Paperback', 'Ebook', 'Audiobook'],
    category: 'biography-memoir',
    subcategory: 'innovators-entrepreneurs',
    subjects: ['Biography', 'Apple Inc', 'Technology History', 'Silicon Valley'],
    topics: ['Steve Jobs', 'Apple', 'Pixar', 'Product Design', 'Innovation'],
    genres: ['Biography', 'Technology', 'Non-Fiction'],
    tags: ['steve-jobs', 'walter-isaacson', 'apple', 'biography', 'design', 'silicon-valley'],
    bookTypes: ['Biography', 'Business', 'Non Fiction'],
    readingPurposes: ['become-entrepreneur', 'develop-leadership'],
    careers: ['entrepreneur', 'product-manager', 'software-engineer'],
    goals: ['become-entrepreneur'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 98,
    coverImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.walterisaacson.com',
    libraryUrl: 'https://openlibrary.org/works/OL16067758W/Steve_Jobs',
    legitimatePurchaseLinks: [{ label: 'Simon & Schuster Store', url: 'https://www.simonandschuster.com', storeOrPlatform: 'Simon & Schuster' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL16067758W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Simon & Schuster',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Ignited Minds: Unleashing the Power Within India',
    subtitle: 'A Vision for the Youth of the Nation',
    slug: 'ignited-minds',
    authors: ['A.P.J. Abdul Kalam'],
    primaryAuthor: 'A.P.J. Abdul Kalam',
    description: 'Dr. A.P.J. Abdul Kalam writes directly to the children and youth of India, challenging them to dream big and overcome cynicism. Ignited Minds is a powerful manifesto on how scientific temper, moral education, and self-belief can transform India into a developed nation.',
    shortDescription: 'Dr. APJ Abdul Kalam’s passionate manifesto inspiring Indian students to dream big and build the nation.',
    summary: 'Examines youth aspirations, role models, interfaith harmony, scientific ambition, and the critical need for indigenous national development.',
    keyIdeas: [
      'Ignited Minds as the Greatest Asset: The ignited mind of the youth is the most powerful resource on the earth, above the earth, and under the earth.',
      'Small Aim is a Crime: Dream high, work hard with integrity, and refuse to accept mediocrity.',
      'Self-Reliant India: Developing indigenous technological capability across defense, agriculture, and healthcare.',
    ],
    whyRead: 'A concise, stirring call to action that instills deep pride, purpose, and energy in Indian students.',
    importance: 'One of Dr. Kalam’s most influential works, read by millions of school and college students across India.',
    whoShouldRead: ['School and college students', 'Teachers and educators', 'Youth seeking career direction'],
    bestFor: ['Youth motivation', 'Nation building', 'Scientific temper', 'Character development'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '3-4 hours',
    pageCount: 205,
    publicationYear: 2002,
    publisher: 'Penguin Books India',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: 'Penguin India Edition',
    latestEditionYear: 2003,
    editionPublisher: 'Penguin India',
    editionVerified: true,
    isbn10: '0143029827',
    isbn13: '978-0143029823',
    format: ['Paperback', 'Ebook', 'Audiobook'],
    category: 'biography-memoir',
    subcategory: 'inspirational-statesmen',
    subjects: ['Inspirational', 'Youth Education', 'Indian Development', 'National Vision'],
    topics: ['Dr APJ Abdul Kalam', 'Ignited Minds', 'Youth Motivation', 'Scientific Temper'],
    genres: ['Non-Fiction', 'Inspirational', 'Essays'],
    tags: ['kalam', 'ignited-minds', 'youth', 'inspirational', 'india-vision'],
    bookTypes: ['Inspirational', 'Essay', 'Non Fiction'],
    readingPurposes: ['understand-indian-society', 'develop-leadership'],
    careers: ['college-student', 'civil-services-aspirant'],
    goals: ['understand-indian-society'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 95,
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL8160080W/Ignited_Minds',
    legitimatePurchaseLinks: [{ label: 'Penguin India Store', url: 'https://www.penguinrandomhouse.in', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'President of India Kalam Archive', url: 'https://presidentofindia.gov.in', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Penguin Books India',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
];
