export interface SeedAuthorItem {
  _id?: string;
  name: string;
  slug: string;
  alternateNames?: string[];
  biography: string;
  shortBiography: string;
  nationality: string;
  country: string;
  isIndian: boolean;
  birthYear?: number;
  deathYear?: number;
  profession: string[];
  fields: string[];
  notableWorks: string[];
  portrait: string;
  coverImage?: string;
  officialWebsite?: string;
  wikipediaUrl?: string;
  sources: Array<{ name: string; url: string }>;
  featured: boolean;
  popular: boolean;
  bookCount: number;
}

export interface SeedBookItem {
  _id?: string;
  title: string;
  subtitle?: string;
  slug: string;
  alternateTitles?: string[];
  authors: string[];
  primaryAuthor: string;
  description: string;
  shortDescription: string;
  summary?: string;
  keyIdeas: string[];
  whyRead: string;
  importance?: string;
  whoShouldRead: string[];
  whoShouldNotRead?: string[];
  bestFor: string[];
  readingLevel: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED' | 'ALL_LEVELS';
  prerequisites: string[];
  estimatedReadingTime: string;
  pageCount?: number;
  originalPublicationDate?: Date;
  publicationYear: number;
  publisher: string;
  countryOfOrigin: string;
  language: string;
  originalLanguage?: string;
  latestKnownEdition?: string;
  latestEditionYear?: number;
  editionPublisher?: string;
  editionVerified: boolean;
  isbn10?: string;
  isbn13?: string;
  format: string[];
  category: string;
  subcategory?: string;
  subjects: string[];
  topics: string[];
  genres: string[];
  tags: string[];
  bookTypes: string[];
  readingPurposes: string[];
  careers: string[];
  goals: string[];
  country: string;
  region?: string;
  IndianState?: string;
  isIndianAuthor: boolean;
  isIndianPublication: boolean;
  featured: boolean;
  editorPick: boolean;
  recommended: boolean;
  trending: boolean;
  popularityScore: number;
  coverImage: string;
  officialWebsite?: string;
  publisherUrl?: string;
  libraryUrl?: string;
  legitimatePurchaseLinks: Array<{ label: string; url: string; storeOrPlatform: string }>;
  legitimateDigitalLinks: Array<{ label: string; url: string; type: 'PURCHASE' | 'LIBRARY' | 'OFFICIAL' | 'DIGITAL' | 'PUBLIC_DOMAIN' }>;
  isPublicDomain: boolean;
  publicDomainSourceUrl?: string;
  source: string;
  sourceType: 'PUBLISHER' | 'OFFICIAL' | 'LIBRARY' | 'ISBN_DATABASE' | 'MANUAL' | 'EDITORIAL' | 'PUBLIC_DOMAIN';
  lastVerified: Date;
  freshnessStatus: string;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: string[];
  status: 'PUBLISHED' | 'DRAFT' | 'ARCHIVED';
}

export const SEED_AUTHORS: SeedAuthorItem[] = [
  {
    name: 'David Thomas',
    slug: 'david-thomas',
    biography: 'David Thomas is an internationally recognized programmer, author, and one of the original 17 authors of the Agile Manifesto. Co-founder of Pragmatic Programmers publishing.',
    shortBiography: 'Pioneering software engineer, co-author of The Pragmatic Programmer, and Agile Manifesto signatory.',
    nationality: 'British',
    country: 'United Kingdom',
    isIndian: false,
    profession: ['Software Engineer', 'Author', 'Publisher'],
    fields: ['Computer Science', 'Software Engineering', 'Agile Methodologies'],
    notableWorks: ['The Pragmatic Programmer', 'Programming Ruby'],
    portrait: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Dave_Thomas_(programmer)',
    officialWebsite: 'https://pragprog.com',
    sources: [{ name: 'Pragmatic Bookshelf', url: 'https://pragprog.com' }],
    featured: true,
    popular: true,
    bookCount: 2,
  },
  {
    name: 'Andrew Hunt',
    slug: 'andrew-hunt',
    biography: 'Andrew Hunt is a software designer, author, and Agile Manifesto co-creator who specializes in practical developer efficiency and systems thinking.',
    shortBiography: 'Software craftsman and co-author of The Pragmatic Programmer.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Software Architect', 'Author', 'Consultant'],
    fields: ['Software Design', 'Pragmatic Thinking', 'Agile'],
    notableWorks: ['The Pragmatic Programmer', 'Pragmatic Thinking and Learning'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Andy_Hunt_(author)',
    sources: [{ name: 'Andy Hunt Official', url: 'https://toolshed.com' }],
    featured: true,
    popular: true,
    bookCount: 2,
  },
  {
    name: 'Martin Kleppmann',
    slug: 'martin-kleppmann',
    biography: 'Martin Kleppmann is a researcher in distributed systems at the University of Cambridge and author of Designing Data-Intensive Applications. Previously worked on scalable systems at LinkedIn.',
    shortBiography: 'Associate Professor at Cambridge University and author of Designing Data-Intensive Applications.',
    nationality: 'German',
    country: 'United Kingdom',
    isIndian: false,
    profession: ['Computer Scientist', 'Researcher', 'Author'],
    fields: ['Distributed Systems', 'Databases', 'Local-First Software', 'CRDTs'],
    notableWorks: ['Designing Data-Intensive Applications'],
    portrait: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://martin.kleppmann.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Martin_Kleppmann',
    sources: [{ name: 'Cambridge University', url: 'https://www.cl.cam.ac.uk/~mk428/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Robert C. Martin',
    slug: 'robert-c-martin',
    alternateNames: ['Uncle Bob'],
    biography: 'Robert Cecil Martin, colloquially known as Uncle Bob, is an American software engineer, author, and teacher. Founder of Uncle Bob Consulting and Clean Coder.',
    shortBiography: 'Renowned software craftsman, creator of SOLID principles, and author of Clean Code.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Software Engineer', 'Consultant', 'Speaker'],
    fields: ['Software Architecture', 'Clean Code', 'Object-Oriented Design'],
    notableWorks: ['Clean Code', 'Clean Architecture', 'The Clean Coder'],
    portrait: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'http://cleancoder.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Robert_C._Martin',
    sources: [{ name: 'Clean Coder', url: 'http://cleancoder.com' }],
    featured: true,
    popular: true,
    bookCount: 2,
  },
  {
    name: 'Thomas H. Cormen',
    slug: 'thomas-h-cormen',
    biography: 'Thomas H. Cormen is Emeritus Professor of Computer Science at Dartmouth College and former Chair of the Dartmouth Writing Program. Co-author of the premier CLRS algorithm text.',
    shortBiography: 'Professor Emeritus at Dartmouth College and co-author of CLRS Algorithms.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Professor', 'Computer Scientist', 'Author'],
    fields: ['Algorithms', 'Parallel Computing', 'Computer Science Education'],
    notableWorks: ['Introduction to Algorithms (CLRS)', 'Algorithms Unlocked'],
    portrait: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.cs.dartmouth.edu/~thc/',
    sources: [{ name: 'Dartmouth College', url: 'https://www.cs.dartmouth.edu/~thc/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Stuart Russell',
    slug: 'stuart-russell',
    biography: 'Stuart J. Russell is a Professor of Computer Science at UC Berkeley and Adjunct Professor of Neurological Surgery at UCSF. Renowned globally for AI safety and autonomous systems.',
    shortBiography: 'Professor of Computer Science at UC Berkeley and co-author of the standard AI textbook.',
    nationality: 'British',
    country: 'United States',
    isIndian: false,
    profession: ['Computer Scientist', 'Professor', 'Author'],
    fields: ['Artificial Intelligence', 'Machine Learning', 'AI Safety'],
    notableWorks: ['Artificial Intelligence: A Modern Approach', 'Human Compatible'],
    portrait: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'http://people.eecs.berkeley.edu/~russell/',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Stuart_J._Russell',
    sources: [{ name: 'UC Berkeley EECS', url: 'http://people.eecs.berkeley.edu/~russell/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'James Clear',
    slug: 'james-clear',
    biography: 'James Clear is an author and speaker focused on habits, decision making, and continuous improvement. His newsletter 3-2-1 is read by millions weekly.',
    shortBiography: 'Bestselling author of Atomic Habits and behavioral systems specialist.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Author', 'Speaker', 'Behavioral Researcher'],
    fields: ['Habits', 'Productivity', 'Behavioral Psychology'],
    notableWorks: ['Atomic Habits'],
    portrait: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://jamesclear.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/James_Clear',
    sources: [{ name: 'James Clear Official', url: 'https://jamesclear.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Eric Ries',
    slug: 'eric-ries',
    biography: 'Eric Ries is an entrepreneur, author, and creator of the Lean Startup methodology. Founder of the Long-Term Stock Exchange (LTSE).',
    shortBiography: 'Pioneering entrepreneur and author of The Lean Startup.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Entrepreneur', 'Author', 'Adviser'],
    fields: ['Startups', 'Venture Creation', 'Lean Methodologies', 'Innovation'],
    notableWorks: ['The Lean Startup', 'The Startup Way'],
    portrait: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'http://www.theleanstartup.com',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Eric_Ries',
    sources: [{ name: 'The Lean Startup', url: 'http://www.theleanstartup.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Peter Thiel',
    slug: 'peter-thiel',
    biography: 'Peter Thiel is an entrepreneur and venture capitalist. Co-founder of PayPal, Palantir Technologies, and Founders Fund. First outside investor in Facebook.',
    shortBiography: 'Venture capitalist, PayPal co-founder, and author of Zero to One.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    birthYear: 1967,
    profession: ['Venture Capitalist', 'Entrepreneur', 'Author'],
    fields: ['Venture Capital', 'Economics', 'Technology Philosophy'],
    notableWorks: ['Zero to One', 'The Diversity Myth'],
    portrait: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Peter_Thiel',
    sources: [{ name: 'Founders Fund', url: 'https://foundersfund.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Daniel Kahneman',
    slug: 'daniel-kahneman',
    biography: 'Daniel Kahneman was an Israeli-American psychologist and Nobel Memorial Prize laureate in Economic Sciences. Pioneer in behavioral economics and heuristics.',
    shortBiography: 'Nobel Laureate in Economics and author of Thinking, Fast and Slow.',
    nationality: 'Israeli-American',
    country: 'United States',
    isIndian: false,
    birthYear: 1934,
    deathYear: 2024,
    profession: ['Psychologist', 'Economist', 'Professor'],
    fields: ['Behavioral Economics', 'Cognitive Psychology', 'Decision Theory'],
    notableWorks: ['Thinking, Fast and Slow', 'Noise: A Flaw in Human Judgment'],
    portrait: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Daniel_Kahneman',
    sources: [{ name: 'Nobel Prize Official', url: 'https://www.nobelprize.org/prizes/economic-sciences/2002/kahneman/biographical/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'A.P.J. Abdul Kalam',
    slug: 'apj-abdul-kalam',
    alternateNames: ['Avul Pakir Jainulabdeen Abdul Kalam', 'Dr. Kalam', 'Missile Man of India'],
    biography: 'Dr. A.P.J. Abdul Kalam was an Indian aerospace scientist and statesman who served as the 11th President of India from 2002 to 2007. Renowned for his role in India’s civilian space program and missile development.',
    shortBiography: '11th President of India, visionary scientist, Bharat Ratna recipient, and author of Wings of Fire.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1931,
    deathYear: 2015,
    profession: ['Aerospace Scientist', 'Statesman', 'Author', 'Educator'],
    fields: ['Aerospace Engineering', 'National Development', 'Education', 'Youth Motivation'],
    notableWorks: ['Wings of Fire', 'Ignited Minds', 'India 2020'],
    portrait: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/A._P._J._Abdul_Kalam',
    sources: [{ name: 'President of India Archive', url: 'https://presidentofindia.gov.in' }],
    featured: true,
    popular: true,
    bookCount: 2,
  },
  {
    name: 'Ramachandra Guha',
    slug: 'ramachandra-guha',
    biography: 'Ramachandra Guha is a leading Indian historian, environmentalist, and biographer. Known for his comprehensive histories of post-independence India and biographies of Mahatma Gandhi.',
    shortBiography: 'Eminent Indian historian and author of India After Gandhi.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1958,
    profession: ['Historian', 'Biographer', 'Essayist'],
    fields: ['Modern Indian History', 'Environmental Studies', 'Cricket History', 'Political Science'],
    notableWorks: ['India After Gandhi', 'Gandhi: The Years That Changed the World', 'A Corner of a Foreign Field'],
    portrait: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'http://ramachandraguha.in',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Ramachandra_Guha',
    sources: [{ name: 'Ramachandra Guha Official', url: 'http://ramachandraguha.in' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Jawaharlal Nehru',
    slug: 'jawaharlal-nehru',
    alternateNames: ['Pandit Nehru'],
    biography: 'Jawaharlal Nehru was an Indian anti-colonial nationalist, secular humanist, social democrat, and author who was the first Prime Minister of India from 1947 until his death in 1964.',
    shortBiography: 'First Prime Minister of India, freedom fighter, and author of The Discovery of India.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1889,
    deathYear: 1964,
    profession: ['Statesman', 'Prime Minister', 'Historian', 'Author'],
    fields: ['Indian History', 'World History', 'Political Philosophy', 'International Diplomacy'],
    notableWorks: ['The Discovery of India', 'Glimpses of World History', 'An Autobiography'],
    portrait: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Jawaharlal_Nehru',
    sources: [{ name: 'Nehru Memorial Museum and Library', url: 'https://www.pmml.nic.in' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Morgan Housel',
    slug: 'morgan-housel',
    biography: 'Morgan Housel is a partner at Collaborative Fund, two-time winner of the Best in Business Award from the Society of American Business Editors and Writers, and author of The Psychology of Money.',
    shortBiography: 'Financial columnist and author of the global bestseller The Psychology of Money.',
    nationality: 'American',
    country: 'United States',
    isIndian: false,
    profession: ['Author', 'Financial Columnist', 'Partner'],
    fields: ['Behavioral Finance', 'Economics', 'Decision Making'],
    notableWorks: ['The Psychology of Money', 'Same as Ever'],
    portrait: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://collabfund.com/blog/authors/morgan/',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Morgan_Housel',
    sources: [{ name: 'Collaborative Fund', url: 'https://collabfund.com' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Marcus Aurelius',
    slug: 'marcus-aurelius',
    biography: 'Marcus Aurelius Antoninus was Roman emperor from 161 to 180 AD and a Stoic philosopher. His personal journal, Meditations, remains one of antiquity’s greatest philosophical reflections.',
    shortBiography: 'Roman Emperor, Stoic philosopher, and author of Meditations.',
    nationality: 'Roman',
    country: 'Italy',
    isIndian: false,
    birthYear: 121,
    deathYear: 180,
    profession: ['Roman Emperor', 'Stoic Philosopher'],
    fields: ['Stoicism', 'Ancient Philosophy', 'Ethics', 'Self-Mastery'],
    notableWorks: ['Meditations'],
    portrait: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=500&auto=format&fit=crop&q=80',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Marcus_Aurelius',
    sources: [{ name: 'Stanford Encyclopedia of Philosophy', url: 'https://plato.stanford.edu/entries/marcus-aurelius/' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
  {
    name: 'Amartya Sen',
    slug: 'amartya-sen',
    biography: 'Amartya Sen is an Indian economist and philosopher. Thomas W. Lamont University Professor and Professor of Economics and Philosophy at Harvard University. Awarded the Nobel Memorial Prize in Economic Sciences in 1998.',
    shortBiography: 'Nobel Laureate in Economics, Bharat Ratna, Harvard Professor, and author of The Argumentative Indian.',
    nationality: 'Indian',
    country: 'India',
    isIndian: true,
    birthYear: 1933,
    profession: ['Economist', 'Philosopher', 'Professor'],
    fields: ['Development Economics', 'Welfare Economics', 'Indian History', 'Social Choice Theory'],
    notableWorks: ['The Argumentative Indian', 'Development as Freedom', 'Idea of Justice'],
    portrait: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80',
    officialWebsite: 'https://scholar.harvard.edu/sen',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Amartya_Sen',
    sources: [{ name: 'Harvard University', url: 'https://scholar.harvard.edu/sen' }],
    featured: true,
    popular: true,
    bookCount: 1,
  },
];

export const SEED_BOOKS: SeedBookItem[] = [
  {
    title: 'The Pragmatic Programmer',
    subtitle: 'Your Journey To Mastery (20th Anniversary Edition)',
    slug: 'the-pragmatic-programmer',
    authors: ['David Thomas', 'Andrew Hunt'],
    primaryAuthor: 'David Thomas',
    description: 'The Pragmatic Programmer is one of the most influential software development books ever written. Across decades of computing shifts, this text offers enduring principles on software craftsmanship, defensive coding, decoupling, orthogonality, domain languages, and career agency.',
    shortDescription: 'The definitive guide to software craftsmanship, engineering mindset, and building resilient code.',
    summary: 'A comprehensive collection of practical advice, analogies, and technical guidelines covering everything from personal responsibility in engineering to modular architecture, testing automation, and pragmatic team culture.',
    keyIdeas: [
      'Care About Your Craft: Always take pride in the quality and longevity of your code.',
      'DRY (Don’t Repeat Yourself): Every piece of knowledge must have a single, unambiguous representation in a system.',
      'Orthogonality & Decoupling: Design components that change independently to reduce ripple effects.',
      'Tracer Bullets vs Prototyping: Build end-to-end thin functional slices to validate real architectural constraints early.',
      'Broken Windows Theory: Never leave bad designs, wrong decisions, or poor code unrepaired.',
    ],
    whyRead: 'Unlike language-specific tutorials that expire in a few years, The Pragmatic Programmer teaches you how to think, dissect complex problems, communicate with stakeholders, and continuously refine your technical judgment throughout your entire engineering career.',
    importance: 'Shaped modern Agile engineering discipline, clean code practices, and the mindset of professional software artisans worldwide.',
    whoShouldRead: [
      'Junior and mid-level software developers looking to level up their engineering mindset.',
      'Senior engineers and tech leads aiming to establish strong engineering team norms.',
      'Computer science students transitioning from academia to real-world production code.',
    ],
    whoShouldNotRead: [
      'Complete beginners who have never written a single line of code (start with an introductory language primer first).',
    ],
    bestFor: ['Software craftsmanship', 'Code architecture', 'Engineering habits', 'Career growth in tech'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Familiarity with at least one programming language (JavaScript, Python, Java, C++, or Go)'],
    estimatedReadingTime: '8-10 hours',
    pageCount: 352,
    originalPublicationDate: new Date('1999-10-30'),
    publicationYear: 1999,
    publisher: 'Addison-Wesley Professional',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '20th Anniversary Edition (2nd Edition)',
    latestEditionYear: 2019,
    editionPublisher: 'Addison-Wesley Professional',
    editionVerified: true,
    isbn10: '0135957052',
    isbn13: '978-0135957059',
    format: ['Hardcover', 'Paperback', 'Ebook', 'Audiobook'],
    category: 'computer-science-technology',
    subcategory: 'programming-software-engineering',
    subjects: ['Software Engineering', 'Programming Best Practices', 'Agile Architecture'],
    topics: ['Clean Code', 'Design Patterns', 'Refactoring', 'Testing', 'Pragmatic Mindset'],
    genres: ['Technology', 'Non-Fiction', 'Professional Guide'],
    tags: ['classic', 'must-read', 'software-engineering', 'craftsmanship', 'agile'],
    bookTypes: ['Professional', 'Technical', 'Non Fiction', 'Classic'],
    readingPurposes: ['become-better-developer', 'learn-programming'],
    careers: ['software-engineer', 'product-manager', 'college-student'],
    goals: ['become-better-developer', 'learn-programming'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 98,
    coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/',
    publisherUrl: 'https://www.pearson.com/en-us/subject-catalog/p/pragmatic-programmer-the-your-journey-to-mastery-20th-anniversary-edition/P200000009477',
    libraryUrl: 'https://openlibrary.org/works/OL18193859W/The_Pragmatic_Programmer',
    legitimatePurchaseLinks: [
      { label: 'Publisher (Pearson)', url: 'https://www.pearson.com', storeOrPlatform: 'Pearson' },
      { label: 'Pragmatic Bookshelf', url: 'https://pragprog.com', storeOrPlatform: 'Pragmatic Bookshelf' },
    ],
    legitimateDigitalLinks: [
      { label: 'Open Library Record', url: 'https://openlibrary.org/works/OL18193859W', type: 'LIBRARY' },
    ],
    isPublicDomain: false,
    source: 'Addison-Wesley / Pearson',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'The Pragmatic Programmer — Book Guide, Editions & Summary | SpotPicx',
    seoDescription: 'Discover why The Pragmatic Programmer by David Thomas and Andrew Hunt is essential reading for software engineers. Key ideas, editions, and prerequisites.',
    seoKeywords: ['The Pragmatic Programmer', 'David Thomas', 'Andrew Hunt', 'Software Engineering', 'Clean Code'],
    status: 'PUBLISHED',
  },
  {
    title: 'Designing Data-Intensive Applications',
    subtitle: 'The Big Ideas Behind Reliable, Scalable, and Maintainable Systems',
    slug: 'designing-data-intensive-applications',
    authors: ['Martin Kleppmann'],
    primaryAuthor: 'Martin Kleppmann',
    description: 'Data is at the center of many challenges in system design today. Difficult issues need to be figured out, such as scalability, consistency, reliability, efficiency, and maintainability. Martin Kleppmann helps you navigate this diverse and fast-changing landscape by exploring the fundamental principles of data systems.',
    shortDescription: 'The quintessential masterwork on distributed systems, databases, consensus, and storage engines.',
    summary: 'A deep, objective dive into storage internals, encoding protocols, replication topologies, partition strategies, ACID transactions, distributed consensus, and streaming data pipelines.',
    keyIdeas: [
      'Reliability, Scalability, Maintainability: The three pillars of production data architecture.',
      'Storage Engines & Indexes: How LSM-Trees, B-Trees, and WALs balance read vs write amplification.',
      'Replication & Partitioning: Single-leader, multi-leader, and leaderless trade-offs with quorum reads.',
      'Distributed Consensus: CAP Theorem realities, Paxos, Raft, and handling Byzantine faults.',
      'Stream & Batch Processing: Unifying event logs with change-data-capture and derived state views.',
    ],
    whyRead: 'Regarded across Silicon Valley and Bengaluru as the single most comprehensive and lucid book on distributed databases and system design. It demystifies buzzwords and grounds architectures in mechanical sympathy.',
    importance: 'The definitive standard text for senior engineering interviews, backend architecture, and distributed database engineering.',
    whoShouldRead: [
      'Backend developers building high-traffic cloud applications.',
      'System design and distributed systems engineers.',
      'Data engineers and database architects.',
    ],
    whoShouldNotRead: [
      'Beginners with no experience in databases or basic client-server networking.',
    ],
    bestFor: ['Distributed systems', 'System design', 'Databases', 'High scale engineering'],
    readingLevel: 'ADVANCED',
    prerequisites: ['Understanding of SQL/NoSQL databases, networking basics, and multi-threaded programming'],
    estimatedReadingTime: '20-25 hours',
    pageCount: 616,
    originalPublicationDate: new Date('2017-03-16'),
    publicationYear: 2017,
    publisher: "O'Reilly Media",
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2017,
    editionPublisher: "O'Reilly Media",
    editionVerified: true,
    isbn10: '1449373321',
    isbn13: '978-1449373320',
    format: ['Paperback', 'Ebook'],
    category: 'computer-science-technology',
    subcategory: 'systems-networks-distributed-systems',
    subjects: ['Distributed Systems', 'Database Internals', 'System Design', 'Cloud Architecture'],
    topics: ['Distributed Systems', 'Databases', 'System Design', 'Replication', 'Consensus'],
    genres: ['Technology', 'Engineering', 'Academic Reference'],
    tags: ['system-design', 'distributed-systems', 'oreilly', 'databases', 'masterpiece'],
    bookTypes: ['Textbook', 'Technical', 'Reference', 'Professional'],
    readingPurposes: ['learn-data-science', 'become-better-developer'],
    careers: ['software-engineer', 'data-scientist'],
    goals: ['become-better-developer'],
    country: 'United Kingdom',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 99,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://dataintensive.net',
    publisherUrl: 'https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/',
    libraryUrl: 'https://openlibrary.org/works/OL17377595W/Designing_Data-Intensive_Applications',
    legitimatePurchaseLinks: [
      { label: "O'Reilly Media Store", url: 'https://www.oreilly.com', storeOrPlatform: "O'Reilly" },
    ],
    legitimateDigitalLinks: [
      { label: 'Official Book Companion Website', url: 'https://dataintensive.net', type: 'OFFICIAL' },
    ],
    isPublicDomain: false,
    source: "O'Reilly Media",
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'Designing Data-Intensive Applications — Martin Kleppmann Guide | SpotPicx',
    seoDescription: 'Master distributed systems and databases with Designing Data-Intensive Applications by Martin Kleppmann. Key concepts, architecture summaries, and reading level.',
    seoKeywords: ['Designing Data-Intensive Applications', 'Martin Kleppmann', 'Distributed Systems', 'System Design'],
    status: 'PUBLISHED',
  },
  {
    title: 'Atomic Habits',
    subtitle: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones',
    slug: 'atomic-habits',
    authors: ['James Clear'],
    primaryAuthor: 'James Clear',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear, one of the world’s leading experts on habit formation, reveals practical strategies that teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
    shortDescription: 'The global phenomenon on the science of tiny micro-changes and compounding behavioral systems.',
    summary: 'A pragmatic framework based on biology, psychology, and neuroscience that breaks habit loops into Four Laws: Make it Obvious, Make it Attractive, Make it Easy, and Make it Satisfying.',
    keyIdeas: [
      '1% Better Every Day: Habits are the compound interest of self-improvement.',
      'Systems Over Goals: You do not rise to the level of your goals; you fall to the level of your systems.',
      'Identity-Based Habits: True behavior change is identity change; focus on who you wish to become.',
      'The 4 Laws of Behavior Change: Cue (Obvious), Craving (Attractive), Response (Easy), Reward (Satisfying).',
      'Environment Architecture: Design your physical and digital space so cues of good habits are obvious and bad habits friction-heavy.',
    ],
    whyRead: 'A no-nonsense, actionable guide that bypasses fleeting motivation and provides concrete behavioral architecture that anyone can implement immediately.',
    importance: 'Over 15 million copies sold globally, setting the modern benchmark for self-regulation, productivity, and organizational behavior.',
    whoShouldRead: [
      'Students looking to build consistent study and learning habits.',
      'Professionals aiming to overcome procrastination and optimize daily workflows.',
      'Anyone struggling with sustaining New Year resolutions or lifestyle changes.',
    ],
    bestFor: ['Habit formation', 'Personal productivity', 'Behavioral psychology', 'Daily routines'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None — accessible to all readers'],
    estimatedReadingTime: '5-6 hours',
    pageCount: 320,
    originalPublicationDate: new Date('2018-10-16'),
    publicationYear: 2018,
    publisher: 'Avery (Penguin Random House)',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2018,
    editionPublisher: 'Penguin Random House',
    editionVerified: true,
    isbn10: '0735211299',
    isbn13: '978-0735211292',
    format: ['Hardcover', 'Paperback', 'Ebook', 'Audiobook'],
    category: 'habits-behavioral-science',
    subcategory: 'habit-formation-system-design',
    subjects: ['Self-Improvement', 'Behavioral Psychology', 'Productivity'],
    topics: ['Atomic Habits', 'Cue-Routine-Reward', 'Identity-Based Habits', 'Environment Architecture'],
    genres: ['Non-Fiction', 'Self Help', 'Psychology'],
    tags: ['habits', 'productivity', 'bestseller', 'psychology', 'discipline'],
    bookTypes: ['Self Help', 'Non Fiction', 'Popular Science'],
    readingPurposes: ['build-habits', 'become-productive'],
    careers: ['software-engineer', 'entrepreneur', 'college-student'],
    goals: ['build-habits', 'become-productive'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 97,
    coverImage: 'https://images.unsplash.com/photo-1544717302-de2939b7ef71?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://jamesclear.com/atomic-habits',
    publisherUrl: 'https://www.penguinrandomhouse.com/books/560844/atomic-habits-by-james-clear/',
    libraryUrl: 'https://openlibrary.org/works/OL17930368W/Atomic_Habits',
    legitimatePurchaseLinks: [
      { label: 'Penguin Random House Store', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' },
    ],
    legitimateDigitalLinks: [
      { label: 'Author Habit Resources', url: 'https://jamesclear.com', type: 'OFFICIAL' },
    ],
    isPublicDomain: false,
    source: 'Penguin Random House',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'Atomic Habits by James Clear — Summary, Key Ideas & Review | SpotPicx',
    seoDescription: 'Read the comprehensive guide to Atomic Habits by James Clear. Learn the 4 laws of behavior change, identity systems, and key takeaways.',
    seoKeywords: ['Atomic Habits', 'James Clear', 'Habits', 'Productivity', 'Self Improvement'],
    status: 'PUBLISHED',
  },
  {
    title: 'Zero to One',
    subtitle: 'Notes on Startups, or How to Build the Future',
    slug: 'zero-to-one',
    authors: ['Peter Thiel'],
    primaryAuthor: 'Peter Thiel',
    description: 'The great secret of our time is that there are still uncharted frontiers to explore and new inventions to create. In Zero to One, legendary entrepreneur and investor Peter Thiel shows how we can find singular ways to create those new things, moving from 0 to 1 rather than copying what already exists (1 to n).',
    shortDescription: 'Peter Thiel’s contrarian manifesto on monopolies, technology secrets, and building groundbreaking companies.',
    summary: 'Explores why competition is for losers, how to discover technological secrets, the power law of venture capital, sales and distribution dynamics, and the seven questions every startup must answer.',
    keyIdeas: [
      '0 to 1 vs 1 to n: Creating something genuinely new (vertical progress) vs copying what works (horizontal progress).',
      'Monopoly vs Perfect Competition: Creative monopolists give customers more choices and fund future innovation.',
      'The Power Law: A small fraction of companies or investments generate almost all the returns.',
      'Secrets: Every great business is built on a secret that is true but that almost nobody agrees with you on.',
      'Distribution Matters: Poor distribution—not product deficiency—is the number one cause of startup failure.',
    ],
    whyRead: 'A masterclass in contrarian business philosophy that forces you to challenge conventional startup wisdom and aim for defensible, enduring moats.',
    importance: 'Required reading across global startup accelerators, VC firms, and product leadership programs.',
    whoShouldRead: [
      'Entrepreneurs, startup founders, and early-stage builders.',
      'Product managers and technology strategists.',
      'Investors and business students.',
    ],
    bestFor: ['Startup strategy', 'Contrarian thinking', 'Venture capital', 'Product differentiation'],
    readingLevel: 'BEGINNER',
    prerequisites: ['Basic interest in business and technology'],
    estimatedReadingTime: '4-5 hours',
    pageCount: 224,
    originalPublicationDate: new Date('2014-09-16'),
    publicationYear: 2014,
    publisher: 'Crown Business (Penguin Random House)',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2014,
    editionPublisher: 'Crown Business',
    editionVerified: true,
    isbn10: '0804139296',
    isbn13: '978-0804139298',
    format: ['Hardcover', 'Paperback', 'Ebook'],
    category: 'entrepreneurship-business',
    subcategory: 'startups-venture-creation',
    subjects: ['Startups', 'Venture Capital', 'Business Strategy', 'Innovation'],
    topics: ['Startup Building', 'Business Models', 'Decision Making', 'Positioning'],
    genres: ['Non-Fiction', 'Business', 'Economics'],
    tags: ['startups', 'entrepreneurship', 'peter-thiel', 'venture-capital', 'strategy'],
    bookTypes: ['Business', 'Non Fiction', 'Professional'],
    readingPurposes: ['start-startup', 'learn-business'],
    careers: ['entrepreneur', 'product-manager', 'investor-finance'],
    goals: ['start-startup', 'learn-business'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 96,
    coverImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://zerotoonebook.com',
    publisherUrl: 'https://www.penguinrandomhouse.com/books/239707/zero-to-one-by-peter-thiel-with-blake-masters/',
    libraryUrl: 'https://openlibrary.org/works/OL17070776W/Zero_to_One',
    legitimatePurchaseLinks: [
      { label: 'Crown / Penguin Store', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' },
    ],
    legitimateDigitalLinks: [
      { label: 'Official Book Site', url: 'https://zerotoonebook.com', type: 'OFFICIAL' },
    ],
    isPublicDomain: false,
    source: 'Crown Publishing',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'Zero to One by Peter Thiel — Startup Insights & Key Ideas | SpotPicx',
    seoDescription: 'Explore Zero to One by Peter Thiel. Discover contrarian startup thinking, building technological monopolies, and the power law of VC.',
    seoKeywords: ['Zero to One', 'Peter Thiel', 'Startups', 'Venture Capital', 'Business Strategy'],
    status: 'PUBLISHED',
  },
  {
    title: 'Wings of Fire',
    subtitle: 'An Autobiography of A P J Abdul Kalam',
    slug: 'wings-of-fire',
    authors: ['A.P.J. Abdul Kalam'],
    primaryAuthor: 'A.P.J. Abdul Kalam',
    description: 'Wings of Fire is the deeply inspirational autobiography of Dr. A.P.J. Abdul Kalam, covering his humble beginnings in Rameswaram, his education at MIT Madras, and his extraordinary leadership in developing India’s satellite launch vehicles (SLV-3) and indigenous missile systems (Agni, Prithvi).',
    shortDescription: 'The timeless autobiography of Dr. A.P.J. Abdul Kalam—from humble coastal village to the pinnacle of Indian science.',
    summary: 'A chronicle of scientific dedication, national self-reliance, leadership during setbacks, team empowerment, and deep spiritual humility in the pursuit of technological progress.',
    keyIdeas: [
      'Perseverance Through Failure: How the SLV-3 initial failure paved the way for historic success.',
      'Indigenous Capability: Building critical aerospace and defense technology despite international embargoes.',
      'Transformational Leadership: Taking personal blame for team failures and giving full credit for triumphs.',
      'Dream with Commitment: Dreams are not what you see in sleep, but that which does not let you sleep.',
    ],
    whyRead: 'An essential Indian classic that provides invaluable lessons in leadership, ethics, scientific vision, and selfless nation-building.',
    importance: 'Inspired millions of Indian youth, engineers, and students across generations.',
    whoShouldRead: [
      'Students and young aspirants across India preparing for engineering, science, or civil services.',
      'Leaders looking for authentic models of empathetic and mission-driven governance.',
      'Anyone seeking inspiration to overcome socio-economic hurdles through merit and discipline.',
    ],
    bestFor: ['Inspiration', 'Leadership', 'Indian science history', 'Youth motivation'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '4-5 hours',
    pageCount: 180,
    originalPublicationDate: new Date('1999-01-01'),
    publicationYear: 1999,
    publisher: 'Universities Press (India)',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: 'Universities Press Edition',
    latestEditionYear: 2004,
    editionPublisher: 'Universities Press',
    editionVerified: true,
    isbn10: '8173711461',
    isbn13: '978-8173711466',
    format: ['Paperback', 'Ebook', 'Audiobook'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-history-civilisation',
    subjects: ['Autobiography', 'Indian Science', 'Aerospace Engineering', 'Leadership'],
    topics: ['A.P.J. Abdul Kalam', 'Indian Space Program', 'Youth Leadership', 'National Development'],
    genres: ['Biography', 'Memoir', 'Inspirational'],
    tags: ['abdul-kalam', 'indian-classic', 'inspirational', 'biography', 'dr-kalam'],
    bookTypes: ['Biography', 'Memoir', 'Non Fiction', 'Classic'],
    readingPurposes: ['understand-indian-society', 'learn-leadership'],
    careers: ['software-engineer', 'civil-services-aspirant', 'college-student'],
    goals: ['understand-indian-society', 'learn-leadership'],
    country: 'India',
    region: 'Tamil Nadu',
    IndianState: 'Tamil Nadu',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 98,
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    publisherUrl: 'https://www.universitiespress.com',
    libraryUrl: 'https://openlibrary.org/works/OL18047910W/Wings_of_Fire',
    legitimatePurchaseLinks: [
      { label: 'Universities Press India', url: 'https://www.universitiespress.com', storeOrPlatform: 'Universities Press' },
    ],
    legitimateDigitalLinks: [
      { label: 'Open Library Catalog', url: 'https://openlibrary.org/works/OL18047910W', type: 'LIBRARY' },
    ],
    isPublicDomain: false,
    source: 'Universities Press (India)',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'Wings of Fire by APJ Abdul Kalam — Summary & Guide | SpotPicx',
    seoDescription: 'Discover Wings of Fire by Dr. APJ Abdul Kalam. Read key takeaways, leadership lessons, and biographical background on SpotPicx.',
    seoKeywords: ['Wings of Fire', 'APJ Abdul Kalam', 'Dr Kalam Autobiography', 'Indian Science'],
    status: 'PUBLISHED',
  },
  {
    title: 'India After Gandhi',
    subtitle: 'The History of the World’s Largest Democracy',
    slug: 'india-after-gandhi',
    authors: ['Ramachandra Guha'],
    primaryAuthor: 'Ramachandra Guha',
    description: 'Born against the backdrop of partition and bloodshed, post-colonial India faced seemingly insurmountable odds. Ramachandra Guha’s India After Gandhi provides a breathtaking, magisterial narrative of modern India’s triumphs, internal conflicts, linguistic reorganizations, wars, and enduring democratic resilience.',
    shortDescription: 'The definitive, monumental historical narrative of post-independence India.',
    summary: 'Covers the accession of princely states, the drafting of the Constitution, the Nehruvian era, the Emergency, linguistic politics, religious tensions, and economic liberalization.',
    keyIdeas: [
      'A Republic of Unlikely Survival: How India defied Western predictions that it would splinter or descend into dictatorship.',
      'The Constitution as a Living Anchor: Dr. B.R. Ambedkar and the constituent assembly’s vision of civic nationalism.',
      'Language and Identity: Resolving the linguistic reorganization of states while preserving national unity.',
      'Electoral Democracy: How universal adult franchise created profound political empowerment for subaltern citizens.',
    ],
    whyRead: 'Widely celebrated as the single best book to understand modern democratic India and its complex institutional evolution.',
    importance: 'Standard reference for Indian political history, university curriculums, and civil services preparation.',
    whoShouldRead: [
      'Anyone seeking an in-depth understanding of post-1947 Indian history and politics.',
      'UPSC and civil services aspirants.',
      'Journalists, diplomats, and social science students.',
    ],
    bestFor: ['Modern Indian history', 'Indian politics', 'Constitutional history', 'Democratic studies'],
    readingLevel: 'ADVANCED',
    prerequisites: ['Basic familiarity with 20th-century world history and Indian independence'],
    estimatedReadingTime: '30-35 hours',
    pageCount: 960,
    originalPublicationDate: new Date('2007-05-01'),
    publicationYear: 2007,
    publisher: 'Picador / Ecco (HarperCollins)',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: '10th Anniversary Revised & Expanded Edition',
    latestEditionYear: 2017,
    editionPublisher: 'Picador India',
    editionVerified: true,
    isbn10: '0330505548',
    isbn13: '978-0330505543',
    format: ['Hardcover', 'Paperback', 'Ebook'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-history-civilisation',
    subjects: ['Indian History', 'Post-Independence History', 'Political Science', 'Democracy'],
    topics: ['Indian History', 'Democracy in India', 'Constitution of India', 'Nehruvian Era'],
    genres: ['History', 'Non-Fiction', 'Academic'],
    tags: ['india-history', 'ramachandra-guha', 'modern-india', 'democracy', 'upsc-essential'],
    bookTypes: ['History', 'Academic', 'Non Fiction'],
    readingPurposes: ['understand-indian-society', 'learn-history'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['understand-indian-society', 'learn-history'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 95,
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'http://ramachandraguha.in',
    publisherUrl: 'https://www.panmacmillan.co.in',
    libraryUrl: 'https://openlibrary.org/works/OL8160074W/India_After_Gandhi',
    legitimatePurchaseLinks: [
      { label: 'Pan Macmillan India', url: 'https://www.panmacmillan.co.in', storeOrPlatform: 'Pan Macmillan' },
    ],
    legitimateDigitalLinks: [
      { label: 'Open Library Record', url: 'https://openlibrary.org/works/OL8160074W', type: 'LIBRARY' },
    ],
    isPublicDomain: false,
    source: 'Pan Macmillan / Picador',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'India After Gandhi by Ramachandra Guha — Book Guide | SpotPicx',
    seoDescription: 'Explore India After Gandhi by Ramachandra Guha. Understand modern Indian democratic history, partition aftermath, and key historical milestones.',
    seoKeywords: ['India After Gandhi', 'Ramachandra Guha', 'Indian History', 'Democracy in India'],
    status: 'PUBLISHED',
  },
  {
    title: 'The Psychology of Money',
    subtitle: 'Timeless lessons on wealth, greed, and happiness',
    slug: 'the-psychology-of-money',
    authors: ['Morgan Housel'],
    primaryAuthor: 'Morgan Housel',
    description: 'Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. Morgan Housel shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life’s most important topics.',
    shortDescription: '19 insightful stories demonstrating that financial success is driven by behavioral discipline, not spreadsheet math.',
    summary: 'Focuses on the distinction between being rich vs wealthy, the power of compounding time, understanding what is "enough", and managing risk without succumbing to ego.',
    keyIdeas: [
      'Behavior Over Intelligence: Financial outcomes are determined by emotional control rather than technical finance degrees.',
      'Compounding & Time Horizon: Warren Buffett’s real secret is that he started investing at age 10 and never interrupted compounding.',
      'Getting Wealthy vs Staying Wealthy: Staying wealthy requires paranoia, frugality, and surviving down cycles.',
      'The Value of Freedom: The highest dividend money pays is the ability to control your own time.',
      'Room for Error: Always maintain a margin of safety for things you cannot foresee.',
    ],
    whyRead: 'A refreshing, highly readable antidote to get-rich-quick schemes that establishes healthy lifelong financial habits.',
    importance: 'Global bestseller translated into over 50 languages with millions of readers across world financial capitals.',
    whoShouldRead: [
      'Anyone starting their personal investment or career journey.',
      'Professionals wanting to develop a sound relationship with wealth and consumption.',
      'Investors seeking behavioral discipline during market volatility.',
    ],
    bestFor: ['Personal finance', 'Money mindset', 'Behavioral economics', 'Long-term investing'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '4-5 hours',
    pageCount: 256,
    originalPublicationDate: new Date('2020-09-08'),
    publicationYear: 2020,
    publisher: 'Harriman House',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2020,
    editionPublisher: 'Harriman House',
    editionVerified: true,
    isbn10: '0857197681',
    isbn13: '978-0857197689',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'finance-investing',
    subcategory: 'personal-finance-wealth-creation',
    subjects: ['Personal Finance', 'Behavioral Economics', 'Wealth Management'],
    topics: ['Psychology of Money', 'Financial Independence', 'Compounding', 'Budgeting'],
    genres: ['Non-Fiction', 'Finance', 'Psychology'],
    tags: ['money', 'finance', 'investing', 'bestseller', 'wealth'],
    bookTypes: ['Business', 'Self Help', 'Non Fiction'],
    readingPurposes: ['improve-financial-knowledge', 'build-habits'],
    careers: ['investor-finance', 'software-engineer', 'entrepreneur', 'college-student'],
    goals: ['improve-financial-knowledge'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 97,
    coverImage: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    publisherUrl: 'https://harriman-house.com/psychologyofmoney',
    libraryUrl: 'https://openlibrary.org/works/OL21867807W/The_Psychology_of_Money',
    legitimatePurchaseLinks: [
      { label: 'Harriman House Publisher', url: 'https://harriman-house.com', storeOrPlatform: 'Harriman House' },
    ],
    legitimateDigitalLinks: [
      { label: 'Collaborative Fund Blog', url: 'https://collabfund.com/blog', type: 'OFFICIAL' },
    ],
    isPublicDomain: false,
    source: 'Harriman House',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'The Psychology of Money by Morgan Housel — Key Ideas & Guide | SpotPicx',
    seoDescription: 'Read the summary and core lessons of The Psychology of Money by Morgan Housel. Master personal finance, compounding, and money psychology.',
    seoKeywords: ['The Psychology of Money', 'Morgan Housel', 'Personal Finance', 'Investing', 'Wealth'],
    status: 'PUBLISHED',
  },
  {
    title: 'Meditations',
    subtitle: 'A New Translation and Philosophical Reflections',
    slug: 'meditations-marcus-aurelius',
    authors: ['Marcus Aurelius'],
    primaryAuthor: 'Marcus Aurelius',
    description: 'Written in Greek without any intention of publication, the Meditations of Marcus Aurelius offer a remarkable series of challenging spiritual reflections and exercises developed as the emperor struggled to understand himself and make sense of the universe while governing the Roman Empire.',
    shortDescription: 'The private spiritual journal of the Roman Emperor Marcus Aurelius on Stoic duty and tranquility.',
    summary: 'Timeless reflections on the dichotomy of control, accepting mortality (memento mori), overcoming resentment, performing civic duty without ego, and finding peace amidst turmoil.',
    keyIdeas: [
      'Dichotomy of Control: Focus entirely on your own thoughts, actions, and judgments; external events are beyond your control.',
      'Perception Shapes Reality: "You have power over your mind - not outside events. Realize this, and you will find strength."',
      'Memento Mori: Keep your inevitable mortality in mind to prioritize what genuinely matters each day.',
      'Service to Society: Humans are made to cooperate with one another like feet, hands, and the rows of the upper and lower teeth.',
    ],
    whyRead: 'The gold standard of ancient Stoic wisdom. It is not an abstract theory book, but the raw daily therapy of the most powerful man in the ancient world.',
    importance: 'Preserved across two millennia, inspiring philosophers, world leaders, and modern cognitive-behavioral therapy (CBT).',
    whoShouldRead: [
      'Anyone dealing with anxiety, high-pressure responsibilities, or emotional reactivity.',
      'Leaders and founders navigating intense external chaos.',
      'Readers interested in ancient philosophy and ethics.',
    ],
    bestFor: ['Stoicism', 'Emotional resilience', 'Mental discipline', 'Ancient philosophy'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '4-5 hours',
    pageCount: 200,
    originalPublicationDate: new Date('0180-01-01'),
    publicationYear: 180,
    publisher: 'Public Domain / Modern Translations (Penguin Classics)',
    countryOfOrigin: 'Roman Empire',
    language: 'English (Translated from Ancient Greek)',
    originalLanguage: 'Ancient Greek',
    latestKnownEdition: 'Penguin Classics Translation (Gregory Hays)',
    latestEditionYear: 2002,
    editionPublisher: 'Modern Library / Penguin',
    editionVerified: true,
    isbn10: '0812968255',
    isbn13: '978-0812968255',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Public Domain Text'],
    category: 'philosophy-ethics',
    subcategory: 'stoicism-ancient-philosophy',
    subjects: ['Stoicism', 'Ancient Philosophy', 'Ethics', 'Self-Mastery'],
    topics: ['Marcus Aurelius', 'Stoic Discipline', 'Mental Toughness', 'Good Life'],
    genres: ['Philosophy', 'Classics', 'Non-Fiction'],
    tags: ['stoicism', 'philosophy', 'marcus-aurelius', 'classics', 'resilience', 'public-domain'],
    bookTypes: ['Philosophy', 'Classic', 'Public Domain', 'Non Fiction'],
    readingPurposes: ['learn-philosophy', 'build-habits'],
    careers: ['software-engineer', 'entrepreneur', 'college-student'],
    goals: ['learn-philosophy'],
    country: 'Italy',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 97,
    coverImage: 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL107871W/Meditations',
    legitimatePurchaseLinks: [
      { label: 'Penguin Classics', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' },
    ],
    legitimateDigitalLinks: [
      { label: 'Project Gutenberg Free Public Domain Text', url: 'https://www.gutenberg.org/ebooks/2680', type: 'PUBLIC_DOMAIN' },
      { label: 'MIT Internet Classics Archive', url: 'http://classics.mit.edu/Antoninus/meditations.html', type: 'PUBLIC_DOMAIN' },
    ],
    isPublicDomain: true,
    publicDomainSourceUrl: 'https://www.gutenberg.org/ebooks/2680',
    source: 'Project Gutenberg / Open Library',
    sourceType: 'PUBLIC_DOMAIN',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Public Domain Verified',
    seoTitle: 'Meditations by Marcus Aurelius — Stoic Guide & Summary | SpotPicx',
    seoDescription: 'Read the comprehensive guide to Meditations by Marcus Aurelius. Stoic principles, dichotomy of control, and free public domain translations.',
    seoKeywords: ['Meditations', 'Marcus Aurelius', 'Stoicism', 'Philosophy', 'Public Domain Books'],
    status: 'PUBLISHED',
  },
  {
    title: 'The Discovery of India',
    subtitle: 'From the Indus Valley Civilization to the Freedom Movement',
    slug: 'the-discovery-of-india',
    authors: ['Jawaharlal Nehru'],
    primaryAuthor: 'Jawaharlal Nehru',
    description: 'Written during his four years of imprisonment at Ahmednagar Fort (1942–1946) for participating in the Quit India Movement, Jawaharlal Nehru’s The Discovery of India is an intimate and comprehensive exploration of the Indian subcontinent’s history, philosophy, arts, and civilisational ethos.',
    shortDescription: 'Nehru’s monumental exploration of Indian civilisational identity, written from prison during the freedom struggle.',
    summary: 'Traces the synthesis of Indian culture from the Indus Valley and Vedic periods, through the Mauryan and Mughal empires, British colonial exploitation, and the resurgence of the freedom struggle.',
    keyIdeas: [
      'Unity in Diversity: The idea that India is an ancient palimpsest where layer upon layer of cultures and religions have coexisted without erasing previous identities.',
      'Scientific Temper: The necessity of combining scientific rationalism with moral and civilisational values.',
      'Critique of Colonial De-industrialization: How colonial economic policies dismantled traditional Indian textiles and agriculture.',
    ],
    whyRead: 'A masterwork of historical literature that reveals the philosophical foundation of modern, secular, democratic India.',
    importance: 'Adapted into the legendary TV series Bharat Ek Khoj by Shyam Benegal; an indelible cultural touchstone.',
    whoShouldRead: [
      'Anyone seeking to understand the historical roots of Indian culture and unity.',
      'Students of Indian history, politics, and literature.',
      'Civil services and humanities scholars.',
    ],
    bestFor: ['Indian history', 'Indian civilization', 'Cultural synthesis', 'Freedom movement'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Basic awareness of Indian history'],
    estimatedReadingTime: '18-22 hours',
    pageCount: 650,
    originalPublicationDate: new Date('1946-01-01'),
    publicationYear: 1946,
    publisher: 'Signet Press / Oxford University Press India',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: 'Oxford University Press Centennial Edition',
    latestEditionYear: 1989,
    editionPublisher: 'Oxford University Press',
    editionVerified: true,
    isbn10: '0195623592',
    isbn13: '978-0195623598',
    format: ['Paperback', 'Hardcover', 'Ebook'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-history-civilisation',
    subjects: ['Indian History', 'Civilization', 'Freedom Struggle', 'Indian Philosophy'],
    topics: ['Ancient India', 'Mughal Era', 'Freedom Movement', 'Indian Civilisation'],
    genres: ['History', 'Classic', 'Non-Fiction'],
    tags: ['indian-history', 'nehru', 'classic', 'discovery-of-india', 'freedom-struggle'],
    bookTypes: ['History', 'Classic', 'Non Fiction'],
    readingPurposes: ['understand-indian-society', 'learn-history'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['understand-indian-society', 'learn-history'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 94,
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL15848245W/The_Discovery_of_India',
    legitimatePurchaseLinks: [
      { label: 'Oxford University Press India', url: 'https://india.oup.com', storeOrPlatform: 'OUP India' },
    ],
    legitimateDigitalLinks: [
      { label: 'Internet Archive Public Record', url: 'https://archive.org/details/TheDiscoveryOfIndia-JawaharlalNehru', type: 'LIBRARY' },
    ],
    isPublicDomain: false,
    source: 'Oxford University Press',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'The Discovery of India by Jawaharlal Nehru — Guide & Overview | SpotPicx',
    seoDescription: 'Explore The Discovery of India by Jawaharlal Nehru. Tracing Indian history from the Indus Valley to the freedom struggle.',
    seoKeywords: ['The Discovery of India', 'Jawaharlal Nehru', 'Indian History', 'Indus Valley'],
    status: 'PUBLISHED',
  },
  {
    title: 'The Argumentative Indian',
    subtitle: 'Writings on Indian History, Culture and Identity',
    slug: 'the-argumentative-indian',
    authors: ['Amartya Sen'],
    primaryAuthor: 'Amartya Sen',
    description: 'Nobel Prize-winning economist Amartya Sen argues that India has a long and robust tradition of intellectual pluralism, public debate, rational skepticism, and heterodoxy that dates back millennia and serves as the bedrock of modern Indian democracy.',
    shortDescription: 'Amartya Sen’s seminal exploration of India’s long traditions of pluralism, debate, and rationalism.',
    summary: 'A collection of essays examining ancient debates between Krishna and Arjuna, Emperor Ashoka and Akbar’s religious tolerance, secularism, calendar systems, and India’s global contributions.',
    keyIdeas: [
      'The Tradition of Public Debate: Democracy in India is not a foreign imposition but deeply rooted in ancient traditions of argumentative dialogue.',
      'Skepticism and Rationality: Ancient Indian philosophy includes rich non-religious and atheistic traditions (Lokāyata).',
      'Pluralist Identity: The danger of reducing a person’s multi-faceted identity to a single religious label.',
    ],
    whyRead: 'Provides a deeply erudite, historically grounded rebuttal to monocultural or sectarian interpretations of Indian identity.',
    importance: 'Winner of international acclaim for its celebration of democratic dialogue and heterodoxy.',
    whoShouldRead: [
      'Students of political philosophy, economics, and Indian society.',
      'Anyone curious about the philosophical origins of Indian secularism and pluralism.',
    ],
    bestFor: ['Indian philosophy', 'Democratic debate', 'Secularism', 'Intellectual history'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Basic familiarity with Indian epics and history'],
    estimatedReadingTime: '8-10 hours',
    pageCount: 432,
    originalPublicationDate: new Date('2005-06-01'),
    publicationYear: 2005,
    publisher: 'Farrar, Straus and Giroux / Penguin Books India',
    countryOfOrigin: 'India',
    language: 'English',
    latestKnownEdition: 'Penguin India Edition',
    latestEditionYear: 2006,
    editionPublisher: 'Penguin India',
    editionVerified: true,
    isbn10: '0141012110',
    isbn13: '978-0141012117',
    format: ['Paperback', 'Hardcover', 'Ebook'],
    category: 'indian-knowledge-society',
    subcategory: 'indian-philosophy-epics',
    subjects: ['Indian Philosophy', 'Culture', 'Political Theory', 'History'],
    topics: ['Indian Philosophy', 'Indian Society', 'Democracy in India', 'Modern Indian Thinkers'],
    genres: ['Non-Fiction', 'Philosophy', 'Essays'],
    tags: ['amartya-sen', 'indian-culture', 'pluralism', 'nobel-laureate', 'philosophy'],
    bookTypes: ['Essay', 'Philosophy', 'Non Fiction', 'Academic'],
    readingPurposes: ['understand-indian-society', 'learn-philosophy'],
    careers: ['civil-services-aspirant', 'college-student'],
    goals: ['understand-indian-society', 'learn-philosophy'],
    country: 'India',
    isIndianAuthor: true,
    isIndianPublication: true,
    featured: false,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 92,
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&auto=format&fit=crop&q=80',
    publisherUrl: 'https://www.penguinrandomhouse.in',
    libraryUrl: 'https://openlibrary.org/works/OL8160072W/The_Argumentative_Indian',
    legitimatePurchaseLinks: [
      { label: 'Penguin India', url: 'https://www.penguinrandomhouse.in', storeOrPlatform: 'Penguin' },
    ],
    legitimateDigitalLinks: [
      { label: 'Open Library Record', url: 'https://openlibrary.org/works/OL8160072W', type: 'LIBRARY' },
    ],
    isPublicDomain: false,
    source: 'Penguin Books India',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'The Argumentative Indian by Amartya Sen — Summary & Review | SpotPicx',
    seoDescription: 'Read the overview of The Argumentative Indian by Nobel laureate Amartya Sen. Discover the intellectual pluralism and debate traditions of India.',
    seoKeywords: ['The Argumentative Indian', 'Amartya Sen', 'Indian Pluralism', 'Indian Philosophy'],
    status: 'PUBLISHED',
  },
];
