import { BOOKS_PART_1 } from './booksList1';
import { BOOKS_PART_2 } from './booksList2';
import { SEED_AUTHORS } from './authorsData';

export interface SeedBookItem {
  title: string;
  subtitle?: string;
  slug: string;
  authors: string[];
  primaryAuthor: string;
  description: string;
  shortDescription: string;
  summary: string;
  keyIdeas: string[];
  whyRead: string;
  importance?: string;
  whoShouldRead: string[];
  whoShouldNotRead?: string[];
  bestFor: string[];
  readingLevel: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  prerequisites?: string[];
  estimatedReadingTime: string;
  pageCount: number;
  originalPublicationDate?: Date;
  publicationYear: number;
  publisher: string;
  countryOfOrigin?: string;
  language: string;
  originalLanguage?: string;
  latestKnownEdition?: string;
  latestEditionYear?: number;
  editionPublisher?: string;
  editionVerified: boolean;
  isbn10?: string;
  isbn13?: string;
  asin?: string;
  format: string[];
  category: string;
  subcategory: string;
  subjects: string[];
  topics: string[];
  genres: string[];
  tags: string[];
  bookTypes: string[];
  readingPurposes: string[];
  careers: string[];
  goals: string[];
  country?: string;
  isIndianAuthor: boolean;
  isIndianPublication: boolean;
  featured: boolean;
  editorPick: boolean;
  recommended: boolean;
  trending: boolean;
  popularityScore: number;
  coverImage?: string;
  officialWebsite?: string;
  publisherUrl?: string;
  libraryUrl?: string;
  legitimatePurchaseLinks: Array<{ label: string; url: string; storeOrPlatform?: string }>;
  legitimateDigitalLinks: Array<{ label: string; url: string; type: string }>;
  isPublicDomain: boolean;
  publicDomainSourceUrl?: string;
  source: string;
  sourceType: 'PUBLISHER' | 'OFFICIAL' | 'PUBLIC_DOMAIN' | 'LIBRARY';
  lastVerified: Date;
  freshnessStatus: string;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: string[];
  status: 'PUBLISHED' | 'DRAFT' | 'ARCHIVED';
}

export const SEED_BOOKS: SeedBookItem[] = [...BOOKS_PART_1, ...BOOKS_PART_2];

export { SEED_AUTHORS };
