import { SeedBookItem } from './booksData';

export const BOOKS_PART_1: SeedBookItem[] = [
  {
    title: 'The Pragmatic Programmer',
    subtitle: 'Your Journey To Mastery (20th Anniversary Edition)',
    slug: 'the-pragmatic-programmer',
    authors: ['David Thomas', 'Andrew Hunt'],
    primaryAuthor: 'David Thomas',
    description: 'The Pragmatic Programmer is one of the most influential software development books ever written. Across decades of computing shifts, this text offers enduring principles on software craftsmanship, defensive coding, decoupling, orthogonality, domain languages, and career agency.',
    shortDescription: 'The definitive guide to software craftsmanship, engineering mindset, and building resilient code.',
    summary: 'A comprehensive collection of practical advice, analogies, and technical guidelines covering everything from personal responsibility in engineering to modular architecture, testing automation, and pragmatic team culture.',
    keyIdeas: [
      'Care About Your Craft: Always take pride in the quality and longevity of your code.',
      'DRY (Don’t Repeat Yourself): Every piece of knowledge must have a single, unambiguous representation in a system.',
      'Orthogonality & Decoupling: Design components that change independently to reduce ripple effects.',
      'Tracer Bullets vs Prototyping: Build end-to-end thin functional slices to validate real architectural constraints early.',
      'Broken Windows Theory: Never leave bad designs, wrong decisions, or poor code unrepaired.',
    ],
    whyRead: 'Unlike language-specific tutorials that expire in a few years, The Pragmatic Programmer teaches you how to think, dissect complex problems, communicate with stakeholders, and continuously refine your technical judgment throughout your entire engineering career.',
    importance: 'Shaped modern Agile engineering discipline, clean code practices, and the mindset of professional software artisans worldwide.',
    whoShouldRead: [
      'Junior and mid-level software developers looking to level up their engineering mindset.',
      'Senior engineers and tech leads aiming to establish strong engineering team norms.',
      'Computer science students transitioning from academia to real-world production code.',
    ],
    whoShouldNotRead: [
      'Complete beginners who have never written a single line of code (start with an introductory language primer first).',
    ],
    bestFor: ['Software craftsmanship', 'Code architecture', 'Engineering habits', 'Career growth in tech'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Familiarity with at least one programming language (JavaScript, Python, Java, C++, or Go)'],
    estimatedReadingTime: '8-10 hours',
    pageCount: 352,
    originalPublicationDate: new Date('1999-10-30'),
    publicationYear: 1999,
    publisher: 'Addison-Wesley Professional',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '20th Anniversary Edition (2nd Edition)',
    latestEditionYear: 2019,
    editionPublisher: 'Addison-Wesley Professional',
    editionVerified: true,
    isbn10: '0135957052',
    isbn13: '978-0135957059',
    format: ['Hardcover', 'Paperback', 'Ebook', 'Audiobook'],
    category: 'computer-science-technology',
    subcategory: 'programming-software-engineering',
    subjects: ['Software Engineering', 'Programming Best Practices', 'Agile Architecture'],
    topics: ['Clean Code', 'Design Patterns', 'Refactoring', 'Testing', 'Pragmatic Mindset'],
    genres: ['Technology', 'Non-Fiction', 'Professional Guide'],
    tags: ['classic', 'must-read', 'software-engineering', 'craftsmanship', 'agile'],
    bookTypes: ['Professional', 'Technical', 'Non Fiction', 'Classic'],
    readingPurposes: ['become-better-developer', 'learn-programming'],
    careers: ['software-engineer', 'product-manager', 'college-student'],
    goals: ['become-better-developer', 'learn-programming'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 98,
    coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/',
    publisherUrl: 'https://www.pearson.com/en-us/subject-catalog/p/pragmatic-programmer-the-your-journey-to-mastery-20th-anniversary-edition/P200000009477',
    libraryUrl: 'https://openlibrary.org/works/OL18193859W/The_Pragmatic_Programmer',
    legitimatePurchaseLinks: [
      { label: 'Publisher (Pearson)', url: 'https://www.pearson.com', storeOrPlatform: 'Pearson' },
      { label: 'Pragmatic Bookshelf', url: 'https://pragprog.com', storeOrPlatform: 'Pragmatic Bookshelf' },
    ],
    legitimateDigitalLinks: [
      { label: 'Open Library Record', url: 'https://openlibrary.org/works/OL18193859W', type: 'LIBRARY' },
    ],
    isPublicDomain: false,
    source: 'Addison-Wesley / Pearson',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'The Pragmatic Programmer — Book Guide, Editions & Summary | SpotPicx',
    seoDescription: 'Discover why The Pragmatic Programmer by David Thomas and Andrew Hunt is essential reading for software engineers. Key ideas, editions, and prerequisites.',
    seoKeywords: ['The Pragmatic Programmer', 'David Thomas', 'Andrew Hunt', 'Software Engineering', 'Clean Code'],
    status: 'PUBLISHED',
  },
  {
    title: 'Designing Data-Intensive Applications',
    subtitle: 'The Big Ideas Behind Reliable, Scalable, and Maintainable Systems',
    slug: 'designing-data-intensive-applications',
    authors: ['Martin Kleppmann'],
    primaryAuthor: 'Martin Kleppmann',
    description: 'Data is at the center of many challenges in system design today. Difficult issues need to be figured out, such as scalability, consistency, reliability, efficiency, and maintainability. Martin Kleppmann helps you navigate this diverse and fast-changing landscape by exploring the fundamental principles of data systems.',
    shortDescription: 'The quintessential masterwork on distributed systems, databases, consensus, and storage engines.',
    summary: 'A deep, objective dive into storage internals, encoding protocols, replication topologies, partition strategies, ACID transactions, distributed consensus, and streaming data pipelines.',
    keyIdeas: [
      'Reliability, Scalability, Maintainability: The three pillars of production data architecture.',
      'Storage Engines & Indexes: How LSM-Trees, B-Trees, and WALs balance read vs write amplification.',
      'Replication & Partitioning: Single-leader, multi-leader, and leaderless trade-offs with quorum reads.',
      'Distributed Consensus: CAP Theorem realities, Paxos, Raft, and handling Byzantine faults.',
      'Stream & Batch Processing: Unifying event logs with change-data-capture and derived state views.',
    ],
    whyRead: 'Regarded across Silicon Valley and Bengaluru as the single most comprehensive and lucid book on distributed databases and system design. It demystifies buzzwords and grounds architectures in mechanical sympathy.',
    importance: 'The definitive standard text for senior engineering interviews, backend architecture, and distributed database engineering.',
    whoShouldRead: [
      'Backend developers building high-traffic cloud applications.',
      'System design and distributed systems engineers.',
      'Data engineers and database architects.',
    ],
    whoShouldNotRead: [
      'Beginners with no experience in databases or basic client-server networking.',
    ],
    bestFor: ['Distributed systems', 'System design', 'Databases', 'High scale engineering'],
    readingLevel: 'ADVANCED',
    prerequisites: ['Understanding of SQL/NoSQL databases, networking basics, and multi-threaded programming'],
    estimatedReadingTime: '20-25 hours',
    pageCount: 616,
    originalPublicationDate: new Date('2017-03-16'),
    publicationYear: 2017,
    publisher: "O'Reilly Media",
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2017,
    editionPublisher: "O'Reilly Media",
    editionVerified: true,
    isbn10: '1449373321',
    isbn13: '978-1449373320',
    format: ['Paperback', 'Ebook'],
    category: 'computer-science-technology',
    subcategory: 'systems-networks-distributed-systems',
    subjects: ['Distributed Systems', 'Database Internals', 'System Design', 'Cloud Architecture'],
    topics: ['Distributed Systems', 'Databases', 'System Design', 'Replication', 'Consensus'],
    genres: ['Technology', 'Engineering', 'Academic Reference'],
    tags: ['system-design', 'distributed-systems', 'oreilly', 'databases', 'masterpiece'],
    bookTypes: ['Textbook', 'Technical', 'Reference', 'Professional'],
    readingPurposes: ['learn-data-science', 'become-better-developer'],
    careers: ['software-engineer', 'data-scientist'],
    goals: ['become-better-developer'],
    country: 'United Kingdom',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 99,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://dataintensive.net',
    publisherUrl: 'https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/',
    libraryUrl: 'https://openlibrary.org/works/OL17377595W/Designing_Data-Intensive_Applications',
    legitimatePurchaseLinks: [
      { label: "O'Reilly Media Store", url: 'https://www.oreilly.com', storeOrPlatform: "O'Reilly" },
    ],
    legitimateDigitalLinks: [
      { label: 'Official Book Companion Website', url: 'https://dataintensive.net', type: 'OFFICIAL' },
    ],
    isPublicDomain: false,
    source: "O'Reilly Media",
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    seoTitle: 'Designing Data-Intensive Applications — Martin Kleppmann Guide | SpotPicx',
    seoDescription: 'Master distributed systems and databases with Designing Data-Intensive Applications by Martin Kleppmann. Key concepts, architecture summaries, and reading level.',
    seoKeywords: ['Designing Data-Intensive Applications', 'Martin Kleppmann', 'Distributed Systems', 'System Design'],
    status: 'PUBLISHED',
  },
  {
    title: 'Clean Code',
    subtitle: 'A Handbook of Agile Software Craftsmanship',
    slug: 'clean-code',
    authors: ['Robert C. Martin'],
    primaryAuthor: 'Robert C. Martin',
    description: 'Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. Clean Code presents a revolutionary paradigm for writing readable, maintainable software.',
    shortDescription: 'The foundational handbook on writing readable, intention-revealing, and maintainable software.',
    summary: 'Divided into principles of meaningful names, small functions, SRP (Single Responsibility Principle), test-driven development, exception handling, and code smells.',
    keyIdeas: [
      'Meaningful Names: Reveal intent and avoid mental mapping.',
      'Functions Should Do One Thing: Keep functions small, focused, and free of side effects.',
      'The Boy Scout Rule: Always leave the code base cleaner than you found it.',
      'Clean Tests: Unit tests must be fast, independent, repeatable, self-validating, and timely (F.I.R.S.T.).',
    ],
    whyRead: 'Transforms how developers look at everyday code, turning messy logic into elegant, self-documenting architectures.',
    importance: 'One of the most cited books in modern software engineering interviews and onboarding curriculums.',
    whoShouldRead: ['Junior and senior software developers', 'Engineering managers', 'Code reviewers'],
    bestFor: ['Clean code', 'Refactoring', 'Unit testing', 'Agile craftsmanship'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Proficiency in object-oriented programming (Java, C#, TypeScript, or C++)'],
    estimatedReadingTime: '10-12 hours',
    pageCount: 464,
    publicationYear: 2008,
    publisher: 'Prentice Hall',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2008,
    editionPublisher: 'Prentice Hall / Pearson',
    editionVerified: true,
    isbn10: '0132350882',
    isbn13: '978-0132350884',
    format: ['Paperback', 'Ebook'],
    category: 'computer-science-technology',
    subcategory: 'programming-software-engineering',
    subjects: ['Software Craftsmanship', 'Clean Code', 'Object-Oriented Design'],
    topics: ['Clean Code', 'Refactoring', 'Unit Testing', 'SOLID Principles'],
    genres: ['Technology', 'Professional Guide'],
    tags: ['clean-code', 'uncle-bob', 'software-engineering', 'best-practices'],
    bookTypes: ['Technical', 'Professional', 'Non Fiction'],
    readingPurposes: ['become-better-developer', 'learn-programming'],
    careers: ['software-engineer', 'college-student'],
    goals: ['become-better-developer'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 96,
    coverImage: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL18047913W/Clean_Code',
    legitimatePurchaseLinks: [{ label: 'Pearson Store', url: 'https://www.pearson.com', storeOrPlatform: 'Pearson' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL18047913W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Pearson / Prentice Hall',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Structure and Interpretation of Computer Programs (SICP)',
    subtitle: 'JavaScript Edition',
    slug: 'structure-and-interpretation-of-computer-programs',
    authors: ['Harold Abelson', 'Gerald Jay Sussman'],
    primaryAuthor: 'Harold Abelson',
    description: 'Structure and Interpretation of Computer Programs has had a dramatic impact on computer science curricula over the past four decades. It teaches computation not through mere syntax, but through fundamental abstraction, state, interpreters, and metalinguistic abstraction.',
    shortDescription: 'The legendary MIT introductory text on computation, abstraction, and interpreters.',
    summary: 'Teaches building abstractions with procedures and data, modularity, objects, state, metalinguistic abstraction, and compilation.',
    keyIdeas: [
      'Programs as Mental Models: Programs must be written for people to read, and only incidentally for machines to execute.',
      'Metalinguistic Abstraction: Solving complex problems by creating specialized domain-specific languages.',
      'Higher-Order Procedures: Treating procedures as first-class citizens enables profound compositional power.',
    ],
    whyRead: 'Forces you to understand the true nature of computation, compilers, evaluation models, and recursion.',
    importance: 'The MIT cornerstone text that trained generations of top computer scientists.',
    whoShouldRead: ['Computer science students', 'Engineers seeking fundamental computational mastery'],
    bestFor: ['Computational thinking', 'Functional programming', 'Interpreter design'],
    readingLevel: 'ADVANCED',
    prerequisites: ['Basic programming comfort and mathematical aptitude'],
    estimatedReadingTime: '25-30 hours',
    pageCount: 657,
    publicationYear: 1984,
    publisher: 'MIT Press',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: 'JavaScript Edition',
    latestEditionYear: 2022,
    editionPublisher: 'MIT Press',
    editionVerified: true,
    isbn10: '0262543230',
    isbn13: '978-0262543231',
    format: ['Paperback', 'Hardcover', 'Open Access Online'],
    category: 'computer-science-technology',
    subcategory: 'computer-science-foundations',
    subjects: ['Computer Science Foundations', 'Functional Programming', 'Interpreters'],
    topics: ['SICP', 'Lisp / Scheme', 'Recursion', 'Interpreters', 'Abstraction'],
    genres: ['Technology', 'Academic Reference', 'Classic'],
    tags: ['mit', 'sicp', 'computer-science', 'foundations', 'legendary'],
    bookTypes: ['Textbook', 'Classic', 'Technical'],
    readingPurposes: ['learn-computer-science', 'become-better-developer'],
    careers: ['software-engineer', 'college-student'],
    goals: ['learn-computer-science'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 95,
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://mitpress.mit.edu/9780262543231/structure-and-interpretation-of-computer-programs/',
    libraryUrl: 'https://openlibrary.org/works/OL3146430W/Structure_and_Interpretation_of_Computer_Programs',
    legitimatePurchaseLinks: [{ label: 'MIT Press', url: 'https://mitpress.mit.edu', storeOrPlatform: 'MIT Press' }],
    legitimateDigitalLinks: [{ label: 'MIT Open Courseware Text', url: 'https://mitpress.mit.edu/sicp/', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'MIT Press',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Introduction to Algorithms (CLRS)',
    subtitle: 'Fourth Edition',
    slug: 'introduction-to-algorithms-clrs',
    authors: ['Thomas H. Cormen', 'Charles E. Leiserson', 'Ronald L. Rivest', 'Clifford Stein'],
    primaryAuthor: 'Thomas H. Cormen',
    description: 'Universally celebrated as the "Bible of Algorithms", CLRS provides a comprehensive and rigorous introduction to modern data structures, asymptotic analysis, dynamic programming, greedy algorithms, and graph theory.',
    shortDescription: 'The definitive worldwide reference on data structures, algorithmic design, and complexity.',
    summary: 'Rigorous mathematical treatments of sorting, order statistics, B-trees, hash tables, dynamic programming, graph algorithms, NP-completeness, and parallel algorithms.',
    keyIdeas: [
      'Asymptotic Notation: Big-O, Big-Theta, and Big-Omega bounds for formal efficiency proof.',
      'Divide and Conquer: Solving problems by recursion and Master Theorem analysis.',
      'Dynamic Programming & Greedy Approaches: Memoization, optimal substructure, and greedy choice property.',
    ],
    whyRead: 'Essential for technical interview mastery and building high-performance systems with provable runtime guarantees.',
    importance: 'Adopted by virtually every major computer science university department across the globe.',
    whoShouldRead: ['Competitive programmers', 'Software engineers preparing for DSA interviews', 'CS students'],
    bestFor: ['Data structures', 'Algorithms', 'DSA interviews', 'Algorithm analysis'],
    readingLevel: 'ADVANCED',
    prerequisites: ['Discrete mathematics and basic programming experience'],
    estimatedReadingTime: '40-50 hours',
    pageCount: 1312,
    publicationYear: 1990,
    publisher: 'MIT Press',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '4th Edition',
    latestEditionYear: 2022,
    editionPublisher: 'MIT Press',
    editionVerified: true,
    isbn10: '026204630X',
    isbn13: '978-0262046305',
    format: ['Hardcover', 'Ebook'],
    category: 'computer-science-technology',
    subcategory: 'computer-science-foundations',
    subjects: ['Algorithms', 'Data Structures', 'Computational Complexity'],
    topics: ['Algorithms', 'Data Structures', 'Graph Theory', 'Dynamic Programming', 'CLRS'],
    genres: ['Technology', 'Textbook', 'Academic Reference'],
    tags: ['algorithms', 'dsa', 'clrs', 'mit-press', 'computer-science'],
    bookTypes: ['Textbook', 'Reference', 'Technical'],
    readingPurposes: ['master-dsa', 'learn-computer-science'],
    careers: ['software-engineer', 'college-student'],
    goals: ['master-dsa'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 98,
    coverImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL1879796W/Introduction_to_Algorithms',
    legitimatePurchaseLinks: [{ label: 'MIT Press', url: 'https://mitpress.mit.edu', storeOrPlatform: 'MIT Press' }],
    legitimateDigitalLinks: [{ label: 'MIT Press Official', url: 'https://mitpress.mit.edu', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'MIT Press',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Artificial Intelligence: A Modern Approach',
    subtitle: '4th Global Edition',
    slug: 'artificial-intelligence-a-modern-approach',
    authors: ['Stuart Russell', 'Peter Norvig'],
    primaryAuthor: 'Stuart Russell',
    description: 'The standard and most widely used AI textbook in the world. Covers rational agents, search algorithms, knowledge representation, probabilistic reasoning, machine learning, deep learning, reinforcement learning, robotics, and safety.',
    shortDescription: 'The global standard textbook for modern artificial intelligence, machine learning, and agents.',
    summary: 'Comprehensive view of AI structured around the unifying theme of intelligent rational agents.',
    keyIdeas: [
      'The Rational Agent Paradigm: Designing systems that act to achieve the best outcome given their objectives.',
      'Probabilistic Reasoning & Uncertainty: Bayesian networks and decision graphs for real-world inference.',
      'Reinforcement Learning & Planning: Markov Decision Processes (MDPs) and reward optimization.',
    ],
    whyRead: 'Provides the complete theoretical foundation for anyone working in modern AI, ML, and robotics.',
    importance: 'Used in over 1,500 universities across 135 countries; universally acknowledged as the definitive AI guide.',
    whoShouldRead: ['AI and ML engineers', 'Data scientists', 'CS researchers and students'],
    bestFor: ['Artificial intelligence', 'Machine learning foundations', 'Probabilistic reasoning', 'Robotics'],
    readingLevel: 'ADVANCED',
    prerequisites: ['Linear algebra, probability, calculus, and programming proficiency'],
    estimatedReadingTime: '35-40 hours',
    pageCount: 1166,
    publicationYear: 1995,
    publisher: 'Pearson',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '4th Global Edition',
    latestEditionYear: 2020,
    editionPublisher: 'Pearson',
    editionVerified: true,
    isbn10: '0134610997',
    isbn13: '978-0134610993',
    format: ['Hardcover', 'Paperback', 'Ebook'],
    category: 'computer-science-technology',
    subcategory: 'ai-machine-learning',
    subjects: ['Artificial Intelligence', 'Machine Learning', 'Robotics', 'Search Algorithms'],
    topics: ['Artificial Intelligence', 'Machine Learning', 'Reinforcement Learning', 'Bayesian Networks'],
    genres: ['Technology', 'Textbook', 'Academic Reference'],
    tags: ['ai', 'machine-learning', 'norvig', 'russell', 'standard-textbook'],
    bookTypes: ['Textbook', 'Technical', 'Reference'],
    readingPurposes: ['learn-ai-ml', 'learn-computer-science'],
    careers: ['software-engineer', 'data-scientist', 'college-student'],
    goals: ['learn-ai-ml'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 97,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'http://aima.cs.berkeley.edu',
    libraryUrl: 'https://openlibrary.org/works/OL262758W/Artificial_Intelligence',
    legitimatePurchaseLinks: [{ label: 'Pearson Education', url: 'https://www.pearson.com', storeOrPlatform: 'Pearson' }],
    legitimateDigitalLinks: [{ label: 'AIMA Official Companion', url: 'http://aima.cs.berkeley.edu', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Pearson',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Atomic Habits',
    subtitle: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones',
    slug: 'atomic-habits',
    authors: ['James Clear'],
    primaryAuthor: 'James Clear',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear, one of the world’s leading experts on habit formation, reveals practical strategies that teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
    shortDescription: 'The global phenomenon on the science of tiny micro-changes and compounding behavioral systems.',
    summary: 'A pragmatic framework based on biology, psychology, and neuroscience that breaks habit loops into Four Laws: Make it Obvious, Make it Attractive, Make it Easy, and Make it Satisfying.',
    keyIdeas: [
      '1% Better Every Day: Habits are the compound interest of self-improvement.',
      'Systems Over Goals: You do not rise to the level of your goals; you fall to the level of your systems.',
      'Identity-Based Habits: True behavior change is identity change; focus on who you wish to become.',
      'The 4 Laws of Behavior Change: Cue (Obvious), Craving (Attractive), Response (Easy), Reward (Satisfying).',
      'Environment Architecture: Design your physical and digital space so cues of good habits are obvious and bad habits friction-heavy.',
    ],
    whyRead: 'A no-nonsense, actionable guide that bypasses fleeting motivation and provides concrete behavioral architecture that anyone can implement immediately.',
    importance: 'Over 15 million copies sold globally, setting the modern benchmark for self-regulation, productivity, and organizational behavior.',
    whoShouldRead: [
      'Students looking to build consistent study and learning habits.',
      'Professionals aiming to overcome procrastination and optimize daily workflows.',
      'Anyone struggling with sustaining New Year resolutions or lifestyle changes.',
    ],
    bestFor: ['Habit formation', 'Personal productivity', 'Behavioral psychology', 'Daily routines'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None — accessible to all readers'],
    estimatedReadingTime: '5-6 hours',
    pageCount: 320,
    publicationYear: 2018,
    publisher: 'Avery (Penguin Random House)',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2018,
    editionPublisher: 'Penguin Random House',
    editionVerified: true,
    isbn10: '0735211299',
    isbn13: '978-0735211292',
    format: ['Hardcover', 'Paperback', 'Ebook', 'Audiobook'],
    category: 'habits-behavioral-science',
    subcategory: 'habit-formation-system-design',
    subjects: ['Self-Improvement', 'Behavioral Psychology', 'Productivity'],
    topics: ['Atomic Habits', 'Cue-Routine-Reward', 'Identity-Based Habits', 'Environment Architecture'],
    genres: ['Non-Fiction', 'Self Help', 'Psychology'],
    tags: ['habits', 'productivity', 'bestseller', 'psychology', 'discipline'],
    bookTypes: ['Self Help', 'Non Fiction', 'Popular Science'],
    readingPurposes: ['build-habits', 'become-productive'],
    careers: ['software-engineer', 'entrepreneur', 'college-student'],
    goals: ['build-habits', 'become-productive'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 97,
    coverImage: 'https://images.unsplash.com/photo-1544717302-de2939b7ef71?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://jamesclear.com/atomic-habits',
    publisherUrl: 'https://www.penguinrandomhouse.com/books/560844/atomic-habits-by-james-clear/',
    libraryUrl: 'https://openlibrary.org/works/OL17930368W/Atomic_Habits',
    legitimatePurchaseLinks: [{ label: 'Penguin Random House Store', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'Author Habit Resources', url: 'https://jamesclear.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Penguin Random House',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Power of Habit',
    subtitle: 'Why We Do What We Do in Life and Business',
    slug: 'the-power-of-habit',
    authors: ['Charles Duhigg'],
    primaryAuthor: 'Charles Duhigg',
    description: 'In The Power of Habit, award-winning business reporter Charles Duhigg takes us to the thrilling edge of scientific discoveries that explain why habits exist and how they can be changed. Distilling vast amounts of neurobiology and organizational research into captivating narratives.',
    shortDescription: 'The classic investigative look into the neurology of habit loops, keystone habits, and organizational routines.',
    summary: 'Explores individual habit loops (Cue, Routine, Reward), keystone habits in organizational turnarounds (like Alcoa under Paul O’Neill), and how social movements build unstoppable momentum.',
    keyIdeas: [
      'The Habit Loop: Every habit consists of a Cue, a Routine, and a Reward.',
      'The Golden Rule of Habit Change: You cannot extinguish a bad habit; you can only change the routine while keeping the cue and reward constant.',
      'Keystone Habits: Changing one core habit creates a cascade of positive routines across life and work.',
    ],
    whyRead: 'Provides the neurological and social evidence behind behavioral patterns in individuals, corporations, and communities.',
    importance: 'Spent over 60 weeks on the New York Times bestseller list, revolutionizing modern business and behavioral thinking.',
    whoShouldRead: ['Leaders and managers', 'Students seeking to reshape daily routines', 'Psychology enthusiasts'],
    bestFor: ['Habit neurology', 'Organizational culture', 'Keystone habits'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '6-8 hours',
    pageCount: 416,
    publicationYear: 2012,
    publisher: 'Random House',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2012,
    editionPublisher: 'Random House',
    editionVerified: true,
    isbn10: '081298160X',
    isbn13: '978-0812981605',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'habits-behavioral-science',
    subcategory: 'habit-formation-system-design',
    subjects: ['Habit Formation', 'Neurology', 'Organizational Psychology'],
    topics: ['Habit Loop', 'Keystone Habits', 'Behavioral Modification', 'Neuroscience'],
    genres: ['Non-Fiction', 'Psychology', 'Business'],
    tags: ['habits', 'psychology', 'charles-duhigg', 'productivity', 'behavioral-science'],
    bookTypes: ['Popular Science', 'Non Fiction', 'Self Help'],
    readingPurposes: ['build-habits', 'become-productive'],
    careers: ['software-engineer', 'entrepreneur', 'college-student'],
    goals: ['build-habits'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 94,
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL16067756W/The_Power_of_Habit',
    legitimatePurchaseLinks: [{ label: 'Random House Store', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'Charles Duhigg Official Resources', url: 'https://charlesduhigg.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Random House',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Zero to One',
    subtitle: 'Notes on Startups, or How to Build the Future',
    slug: 'zero-to-one',
    authors: ['Peter Thiel'],
    primaryAuthor: 'Peter Thiel',
    description: 'The great secret of our time is that there are still uncharted frontiers to explore and new inventions to create. In Zero to One, legendary entrepreneur and investor Peter Thiel shows how we can find singular ways to create those new things, moving from 0 to 1 rather than copying what already exists (1 to n).',
    shortDescription: 'Peter Thiel’s contrarian manifesto on monopolies, technology secrets, and building groundbreaking companies.',
    summary: 'Explores why competition is for losers, how to discover technological secrets, the power law of venture capital, sales and distribution dynamics, and the seven questions every startup must answer.',
    keyIdeas: [
      '0 to 1 vs 1 to n: Creating something genuinely new (vertical progress) vs copying what works (horizontal progress).',
      'Monopoly vs Perfect Competition: Creative monopolists give customers more choices and fund future innovation.',
      'The Power Law: A small fraction of companies or investments generate almost all the returns.',
      'Secrets: Every great business is built on a secret that is true but that almost nobody agrees with you on.',
      'Distribution Matters: Poor distribution—not product deficiency—is the number one cause of startup failure.',
    ],
    whyRead: 'A masterclass in contrarian business philosophy that forces you to challenge conventional startup wisdom and aim for defensible, enduring moats.',
    importance: 'Required reading across global startup accelerators, VC firms, and product leadership programs.',
    whoShouldRead: ['Entrepreneurs, startup founders, and builders', 'Product managers and strategists', 'Investors'],
    bestFor: ['Startup strategy', 'Contrarian thinking', 'Venture capital', 'Product differentiation'],
    readingLevel: 'BEGINNER',
    prerequisites: ['Basic interest in business and technology'],
    estimatedReadingTime: '4-5 hours',
    pageCount: 224,
    publicationYear: 2014,
    publisher: 'Crown Business (Penguin Random House)',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2014,
    editionPublisher: 'Crown Business',
    editionVerified: true,
    isbn10: '0804139296',
    isbn13: '978-0804139298',
    format: ['Hardcover', 'Paperback', 'Ebook'],
    category: 'entrepreneurship-business',
    subcategory: 'startups-venture-creation',
    subjects: ['Startups', 'Venture Capital', 'Business Strategy', 'Innovation'],
    topics: ['Startup Building', 'Business Models', 'Decision Making', 'Positioning'],
    genres: ['Non-Fiction', 'Business', 'Economics'],
    tags: ['startups', 'entrepreneurship', 'peter-thiel', 'venture-capital', 'strategy'],
    bookTypes: ['Business', 'Non Fiction', 'Professional'],
    readingPurposes: ['build-startup', 'become-entrepreneur'],
    careers: ['entrepreneur', 'product-manager', 'software-engineer', 'college-student'],
    goals: ['build-startup', 'become-entrepreneur'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 96,
    coverImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL17075676W/Zero_to_One',
    legitimatePurchaseLinks: [{ label: 'Penguin Random House', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'Founders Fund Essays', url: 'https://foundersfund.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Crown Business',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Lean Startup',
    subtitle: 'How Today’s Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses',
    slug: 'the-lean-startup',
    authors: ['Eric Ries'],
    primaryAuthor: 'Eric Ries',
    description: 'Most startups fail. But many of those failures are preventable. The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched. Rather than wasting time creating elaborate business plans, it offers entrepreneurs in companies of all sizes a way to test their vision continuously.',
    shortDescription: 'The movement that revolutionized entrepreneurship with MVPs, validated learning, and build-measure-learn loops.',
    summary: 'Introduces the Build-Measure-Learn feedback loop, Minimum Viable Product (MVP), pivot vs persevere decisions, and innovation accounting.',
    keyIdeas: [
      'Validated Learning: The unit of progress in a startup is validated learning backed by scientific experimentation.',
      'Build-Measure-Learn: Accelerate the speed of cycling through the core feedback loop.',
      'Minimum Viable Product (MVP): The smallest experiment required to start learning from real customer behavior.',
      'Pivot or Persevere: Making data-driven strategic adjustments without emotional sunk-cost bias.',
    ],
    whyRead: 'Prevents founders and product leaders from building products that nobody wants, saving months of wasted capital.',
    importance: 'The foundational methodology of the modern startup ecosystem and corporate innovation labs.',
    whoShouldRead: ['Startup founders', 'Product managers', 'Innovation executives', 'Engineers'],
    bestFor: ['Lean methodology', 'MVP design', 'Agile product management', 'Rapid prototyping'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '6-7 hours',
    pageCount: 336,
    publicationYear: 2011,
    publisher: 'Crown Business',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2011,
    editionPublisher: 'Crown Business',
    editionVerified: true,
    isbn10: '0307887898',
    isbn13: '978-0307887894',
    format: ['Hardcover', 'Paperback', 'Ebook', 'Audiobook'],
    category: 'entrepreneurship-business',
    subcategory: 'startups-venture-creation',
    subjects: ['Startups', 'Product Management', 'Innovation', 'Lean Management'],
    topics: ['MVP', 'Build-Measure-Learn', 'Startup Iteration', 'Product Market Fit'],
    genres: ['Non-Fiction', 'Business', 'Management'],
    tags: ['lean-startup', 'eric-ries', 'mvp', 'entrepreneurship', 'product-management'],
    bookTypes: ['Business', 'Professional', 'Non Fiction'],
    readingPurposes: ['build-startup', 'become-entrepreneur'],
    careers: ['entrepreneur', 'product-manager', 'software-engineer'],
    goals: ['build-startup'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 95,
    coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'http://theleanstartup.com',
    libraryUrl: 'https://openlibrary.org/works/OL16067746W/The_Lean_Startup',
    legitimatePurchaseLinks: [{ label: 'Crown Business Store', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'The Lean Startup Official', url: 'http://theleanstartup.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Crown Business',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'High Output Management',
    subtitle: 'A Practical Guide for Navigating and Building High-Yield Organizations',
    slug: 'high-output-management',
    authors: ['Andrew S. Grove'],
    primaryAuthor: 'Andrew S. Grove',
    description: 'The essential skill of creating and maintaining a new business—the art of the entrepreneur—can be summed up in a single word: managing. In High Output Management, Andy Grove, former chairman and CEO of Intel, shares his legendary perspective on how to build and run a company.',
    shortDescription: 'Andy Grove’s legendary Intel handbook on managerial leverage, meetings, and organizational output.',
    summary: 'Covers production principles applied to management, managerial leverage, 1-on-1 meetings, OKR foundations, and motivating peak performance.',
    keyIdeas: [
      'Manager’s Output: The output of a manager is the output of the organizational units under their supervision or influence.',
      'Managerial Leverage: Focus your time on activities that yield the highest positive multiplier on team output.',
      'The 1-on-1 Meeting: A dedicated conversation where the subordinate sets the agenda to eliminate blockers and calibrate judgment.',
      'Task-Relevant Maturity: Adapt your management style from directive to delegative based on the team member’s specific task experience.',
    ],
    whyRead: 'Considered by Silicon Valley veterans (including Ben Horowitz and Brian Chesky) as the single best management book ever written.',
    importance: 'Shaped Intel’s rise and laid the foundation for modern tech management and OKRs (Objectives and Key Results).',
    whoShouldRead: ['Engineering managers', 'Founders scaling teams', 'Team leads and executives'],
    bestFor: ['Management leverage', 'Team scaling', '1-on-1 meetings', 'Organizational performance'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Experience working in or leading teams'],
    estimatedReadingTime: '6-8 hours',
    pageCount: 272,
    publicationYear: 1983,
    publisher: 'Random House / Vintage',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: 'Vintage Books Reissue Edition',
    latestEditionYear: 2015,
    editionPublisher: 'Vintage Books',
    editionVerified: true,
    isbn10: '0679762884',
    isbn13: '978-0679762881',
    format: ['Paperback', 'Ebook'],
    category: 'entrepreneurship-business',
    subcategory: 'leadership-management',
    subjects: ['Management', 'Executive Leadership', 'Productivity', 'Intel History'],
    topics: ['Managerial Leverage', '1-on-1s', 'Team Motivation', 'OKRs'],
    genres: ['Business', 'Non-Fiction', 'Management'],
    tags: ['andy-grove', 'intel', 'management', 'leadership', 'silicon-valley'],
    bookTypes: ['Business', 'Professional', 'Classic'],
    readingPurposes: ['develop-leadership', 'become-better-manager'],
    careers: ['entrepreneur', 'product-manager', 'software-engineer'],
    goals: ['develop-leadership'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 95,
    coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL1853610W/High_Output_Management',
    legitimatePurchaseLinks: [{ label: 'Vintage Books Store', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'Open Library Record', url: 'https://openlibrary.org/works/OL1853610W', type: 'LIBRARY' }],
    isPublicDomain: false,
    source: 'Random House / Vintage',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'The Hard Thing About Hard Things',
    subtitle: 'Building a Business When There Are No Easy Answers',
    slug: 'the-hard-thing-about-hard-things',
    authors: ['Ben Horowitz'],
    primaryAuthor: 'Ben Horowitz',
    description: 'Ben Horowitz, cofounder of Andreessen Horowitz and one of Silicon Valley’s most respected and experienced entrepreneurs, offers essential advice on building and running a startup—practical wisdom for managing the toughest problems that business school doesn’t cover.',
    shortDescription: 'Unvarnished, real-world advice on wartime leadership, hiring, layoffs, and navigating startup crisis.',
    summary: 'Shares brutal experiences navigating Loudcloud and Opsware through the dot-com crash, managing psychology during the Struggle, peacetime vs wartime CEOs, and firing executives.',
    keyIdeas: [
      'The Struggle: Every great founder experiences excruciating doubt and near-death business moments.',
      'Peacetime CEO vs Wartime CEO: Different operating environments require radically different management playbooks.',
      'Lead with Truth: In crisis, transparency builds trust; do not hide bad news from your team.',
    ],
    whyRead: 'Unlike typical business books that describe when things go well, this book provides the playbook for when everything goes terribly wrong.',
    importance: 'Widely praised by Marc Andreessen, Peter Thiel, and Larry Page as an essential survival guide for founders.',
    whoShouldRead: ['Startup CEOs and founders', 'Executives and senior leaders', 'Aspiring entrepreneurs'],
    bestFor: ['Crisis leadership', 'Startup survival', 'Executive hiring', 'Wartime CEO tactics'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['Interest in startups or business management'],
    estimatedReadingTime: '6-8 hours',
    pageCount: 304,
    publicationYear: 2014,
    publisher: 'HarperBusiness',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2014,
    editionPublisher: 'HarperBusiness',
    editionVerified: true,
    isbn10: '0062273205',
    isbn13: '978-0062273208',
    format: ['Hardcover', 'Paperback', 'Ebook', 'Audiobook'],
    category: 'entrepreneurship-business',
    subcategory: 'leadership-management',
    subjects: ['Startups', 'Executive Leadership', 'Venture Capital', 'Crisis Management'],
    topics: ['Wartime CEO', 'The Struggle', 'Executive Hiring', 'Startup Psychology'],
    genres: ['Business', 'Memoir', 'Non-Fiction'],
    tags: ['ben-horowitz', 'a16z', 'startups', 'leadership', 'crisis-management'],
    bookTypes: ['Business', 'Professional', 'Memoir'],
    readingPurposes: ['build-startup', 'develop-leadership'],
    careers: ['entrepreneur', 'product-manager'],
    goals: ['build-startup'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 94,
    coverImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://a16z.com',
    libraryUrl: 'https://openlibrary.org/works/OL17075677W/The_Hard_Thing_About_Hard_Things',
    legitimatePurchaseLinks: [{ label: 'HarperCollins Store', url: 'https://www.harpercollins.com', storeOrPlatform: 'HarperCollins' }],
    legitimateDigitalLinks: [{ label: 'Andreessen Horowitz Blog', url: 'https://a16z.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'HarperBusiness',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Deep Work',
    subtitle: 'Rules for Focused Success in a Distracted World',
    slug: 'deep-work',
    authors: ['Cal Newport'],
    primaryAuthor: 'Cal Newport',
    description: 'Deep work is the ability to focus without distraction on a cognitively demanding task. It’s a skill that allows you to quickly master complicated information and produce better results in less time. Cal Newport makes the case that deep work is becoming increasingly rare and valuable in our economy.',
    shortDescription: 'Cal Newport’s manifesto on achieving extreme cognitive focus in an age of constant digital distraction.',
    summary: 'Establishes the four rules of deep work: Work Deeply, Embrace Boredom, Quit Social Media, and Drain the Shallows.',
    keyIdeas: [
      'The Deep Work Hypothesis: The ability to perform deep work is becoming increasingly rare at exactly the same time it is becoming increasingly valuable.',
      'Attention Residue: When you switch tasks, a fragment of attention remains stuck on the previous task, degrading cognitive performance.',
      'Drain the Shallows: Ruthlessly eliminate low-value administrative tasks and meetings to protect uninterrupted creative blocks.',
    ],
    whyRead: 'Provides the concrete methodology needed to produce rare, high-value creative and technical output in a distracted world.',
    importance: 'The definitive text on cognitive productivity for programmers, researchers, and writers.',
    whoShouldRead: ['Knowledge workers', 'Developers and researchers', 'Students studying for competitive exams'],
    bestFor: ['Focus', 'Cognitive stamina', 'Time management', 'Deep concentration'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '5-6 hours',
    pageCount: 304,
    publicationYear: 2016,
    publisher: 'Grand Central Publishing',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2016,
    editionPublisher: 'Grand Central Publishing',
    editionVerified: true,
    isbn10: '1455586692',
    isbn13: '978-1455586691',
    format: ['Hardcover', 'Paperback', 'Ebook', 'Audiobook'],
    category: 'personal-development',
    subcategory: 'focus-deep-work',
    subjects: ['Productivity', 'Focus', 'Time Management', 'Digital Well-Being'],
    topics: ['Deep Work', 'Attention Residue', 'Focus Rituals', 'Shallow Work'],
    genres: ['Non-Fiction', 'Self Help', 'Productivity'],
    tags: ['deep-work', 'cal-newport', 'focus', 'productivity', 'study-habits'],
    bookTypes: ['Self Help', 'Non Fiction', 'Popular Science'],
    readingPurposes: ['become-productive', 'build-habits'],
    careers: ['software-engineer', 'college-student', 'data-scientist'],
    goals: ['become-productive'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 96,
    coverImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://calnewport.com/books/deep-work/',
    libraryUrl: 'https://openlibrary.org/works/OL17377598W/Deep_Work',
    legitimatePurchaseLinks: [{ label: 'Grand Central Store', url: 'https://www.hachettebookgroup.com', storeOrPlatform: 'Hachette' }],
    legitimateDigitalLinks: [{ label: 'Cal Newport Study Hacks Blog', url: 'https://calnewport.com/blog', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Grand Central Publishing',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Mindset: The New Psychology of Success',
    subtitle: 'How We Can Learn to Fulfill Our Potential',
    slug: 'mindset-carol-dweck',
    authors: ['Carol S. Dweck'],
    primaryAuthor: 'Carol S. Dweck',
    description: 'After decades of research, world-renowned Stanford University psychologist Carol S. Dweck, Ph.D., discovered a groundbreaking idea: the power of mindset. She shows how success in school, work, sports, the arts, and almost every area of human endeavor can be dramatically influenced by how we think about our talents and abilities.',
    shortDescription: 'Stanford psychologist Carol Dweck’s landmark research on Fixed vs Growth mindsets.',
    summary: 'Explains how believing talents can be developed through dedication and hard work (Growth Mindset) fosters a love of learning and resilience essential for great accomplishment.',
    keyIdeas: [
      'Fixed vs Growth Mindset: Believing ability is static vs believing capability can be developed with effort and strategy.',
      'The Meaning of Effort: In a growth mindset, effort is what makes you smart and capable.',
      'Embracing Failure: Setbacks are opportunities to learn and calibrate, not evidence of permanent limitation.',
    ],
    whyRead: 'Helps overcome fear of failure, perfectionism, and imposter syndrome across academic and professional pursuits.',
    importance: 'Foundational text in modern developmental psychology, education policy, and sports coaching.',
    whoShouldRead: ['Students and educators', 'Parents and coaches', 'Professionals facing career transitions'],
    bestFor: ['Growth mindset', 'Resilience', 'Overcoming failure', 'Lifelong learning'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '5-6 hours',
    pageCount: 320,
    publicationYear: 2006,
    publisher: 'Ballantine Books (Penguin Random House)',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: 'Updated Edition',
    latestEditionYear: 2016,
    editionPublisher: 'Ballantine Books',
    editionVerified: true,
    isbn10: '0345472322',
    isbn13: '978-0345472328',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'personal-development',
    subcategory: 'mindset-resilience',
    subjects: ['Psychology', 'Education', 'Self-Improvement', 'Mindset'],
    topics: ['Growth Mindset', 'Fixed Mindset', 'Resilience', 'Effort'],
    genres: ['Non-Fiction', 'Psychology', 'Self Help'],
    tags: ['carol-dweck', 'growth-mindset', 'psychology', 'resilience', 'learning'],
    bookTypes: ['Popular Science', 'Self Help', 'Non Fiction'],
    readingPurposes: ['develop-mindset', 'learn-psychology'],
    careers: ['college-student', 'software-engineer', 'entrepreneur'],
    goals: ['develop-mindset'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 93,
    coverImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL8160078W/Mindset',
    legitimatePurchaseLinks: [{ label: 'Ballantine Books Store', url: 'https://www.penguinrandomhouse.com', storeOrPlatform: 'Penguin' }],
    legitimateDigitalLinks: [{ label: 'Stanford Mindset Research', url: 'https://psychology.stanford.edu', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Ballantine Books',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Thinking, Fast and Slow',
    subtitle: 'The Landmark Exploration of Human Judgment and Decision Making',
    slug: 'thinking-fast-and-slow',
    authors: ['Daniel Kahneman'],
    primaryAuthor: 'Daniel Kahneman',
    description: 'In the international bestseller Thinking, Fast and Slow, Daniel Kahneman, the renowned psychologist and winner of the Nobel Memorial Prize in Economic Sciences, takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think.',
    shortDescription: 'Nobel laureate Daniel Kahneman’s masterwork on System 1 intuition vs System 2 deliberative thought.',
    summary: 'Examines cognitive biases, heuristics (availability, representativeness), prospect theory, loss aversion, and the tension between the experiencing self and the remembering self.',
    keyIdeas: [
      'System 1 & System 2: System 1 is fast, intuitive, and emotional; System 2 is slower, deliberative, and logical.',
      'Loss Aversion: The psychological pain of losing $100 is roughly twice as intense as the pleasure of gaining $100.',
      'Overconfidence & Hindsight Bias: Humans systematically overestimate their ability to predict outcomes in complex environments.',
    ],
    whyRead: 'The single most authoritative examination of human irrationality and decision making ever published.',
    importance: 'Awarded the National Academies Best Book Award and shaped behavioral economics globally.',
    whoShouldRead: ['Investors and financial analysts', 'Product managers and data scientists', 'Anyone interested in human behavior'],
    bestFor: ['Cognitive biases', 'Decision making', 'Behavioral economics', 'Critical thinking'],
    readingLevel: 'INTERMEDIATE',
    prerequisites: ['None, though comfort with basic statistics is helpful'],
    estimatedReadingTime: '12-15 hours',
    pageCount: 512,
    publicationYear: 2011,
    publisher: 'Farrar, Straus and Giroux',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: '1st Edition',
    latestEditionYear: 2011,
    editionPublisher: 'Farrar, Straus and Giroux',
    editionVerified: true,
    isbn10: '0374275637',
    isbn13: '978-0374275631',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'psychology-cognitive-science',
    subcategory: 'cognitive-biases-heuristics',
    subjects: ['Cognitive Psychology', 'Behavioral Economics', 'Decision Science'],
    topics: ['System 1 and System 2', 'Loss Aversion', 'Cognitive Biases', 'Prospect Theory'],
    genres: ['Non-Fiction', 'Psychology', 'Economics', 'Science'],
    tags: ['kahneman', 'nobel-laureate', 'psychology', 'behavioral-economics', 'decision-making'],
    bookTypes: ['Popular Science', 'Non Fiction', 'Academic'],
    readingPurposes: ['learn-psychology', 'make-better-decisions'],
    careers: ['investor-finance', 'product-manager', 'software-engineer', 'college-student'],
    goals: ['learn-psychology'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: true,
    popularityScore: 98,
    coverImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    libraryUrl: 'https://openlibrary.org/works/OL16067757W/Thinking_Fast_and_Slow',
    legitimatePurchaseLinks: [{ label: 'Macmillan Store', url: 'https://us.macmillan.com', storeOrPlatform: 'Macmillan' }],
    legitimateDigitalLinks: [{ label: 'Nobel Prize Lecture', url: 'https://www.nobelprize.org', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Farrar, Straus and Giroux',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
  {
    title: 'Influence: The Psychology of Persuasion',
    subtitle: 'New and Expanded Edition',
    slug: 'influence-the-psychology-of-persuasion',
    authors: ['Robert B. Cialdini'],
    primaryAuthor: 'Robert B. Cialdini',
    description: 'Influence, the classic book on persuasion, explains the psychology of why people say "yes"—and how to apply these understandings. Dr. Robert Cialdini is the seminal expert in the rapidly expanding field of influence and persuasion.',
    shortDescription: 'The foundational scientific study on the 7 universal principles of persuasion and human compliance.',
    summary: 'Unpacks the seven universal psychological weapons of influence: Reciprocation, Commitment & Consistency, Social Proof, Liking, Authority, Scarcity, and Unity.',
    keyIdeas: [
      'Reciprocation: People feel an overwhelming psychological obligation to return favors and concessions.',
      'Social Proof: When uncertain, humans look to the actions and behaviors of others to guide their own decisions.',
      'Scarcity: Opportunities seem vastly more valuable to us when their availability is limited.',
    ],
    whyRead: 'Essential for ethical communication, marketing, negotiation, and defending yourself against manipulative sales tactics.',
    importance: 'Over 5 million copies sold globally; foundational text in business schools and behavioral psychology.',
    whoShouldRead: ['Marketers and founders', 'Sales leaders and negotiators', 'Anyone curious about social psychology'],
    bestFor: ['Persuasion', 'Social influence', 'Negotiation', 'Consumer psychology'],
    readingLevel: 'BEGINNER',
    prerequisites: ['None'],
    estimatedReadingTime: '7-9 hours',
    pageCount: 592,
    publicationYear: 1984,
    publisher: 'Harper Business',
    countryOfOrigin: 'United States',
    language: 'English',
    latestKnownEdition: 'New and Expanded Edition',
    latestEditionYear: 2021,
    editionPublisher: 'Harper Business',
    editionVerified: true,
    isbn10: '0062937650',
    isbn13: '978-0062937650',
    format: ['Paperback', 'Hardcover', 'Ebook', 'Audiobook'],
    category: 'psychology-cognitive-science',
    subcategory: 'social-influence-persuasion',
    subjects: ['Social Psychology', 'Persuasion', 'Negotiation', 'Behavioral Science'],
    topics: ['Reciprocity', 'Social Proof', 'Scarcity', 'Authority', 'Commitment'],
    genres: ['Non-Fiction', 'Psychology', 'Business'],
    tags: ['cialdini', 'influence', 'persuasion', 'psychology', 'negotiation'],
    bookTypes: ['Popular Science', 'Business', 'Non Fiction'],
    readingPurposes: ['learn-psychology', 'become-entrepreneur'],
    careers: ['entrepreneur', 'product-manager', 'college-student'],
    goals: ['learn-psychology'],
    country: 'United States',
    isIndianAuthor: false,
    isIndianPublication: false,
    featured: true,
    editorPick: true,
    recommended: true,
    trending: false,
    popularityScore: 95,
    coverImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&auto=format&fit=crop&q=80',
    officialWebsite: 'https://www.influenceatwork.com',
    libraryUrl: 'https://openlibrary.org/works/OL18193860W/Influence',
    legitimatePurchaseLinks: [{ label: 'HarperCollins Store', url: 'https://www.harpercollins.com', storeOrPlatform: 'HarperCollins' }],
    legitimateDigitalLinks: [{ label: 'Influence at Work Portal', url: 'https://www.influenceatwork.com', type: 'OFFICIAL' }],
    isPublicDomain: false,
    source: 'Harper Business',
    sourceType: 'PUBLISHER',
    lastVerified: new Date('2026-08-20'),
    freshnessStatus: 'Fully Verified Metadata',
    status: 'PUBLISHED',
  },
];
