import { Category } from '../types';

export const POPULAR_CATEGORIES: Category[] = [
  {
    _id: 'food-dining',
    id: 'food-dining',
    name: 'Food & Cafes',
    slug: 'food-and-cafes',
    icon: 'Utensils',
    iconName: 'Utensils',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    type: 'ROOT',
    isActive: true,
    order: 1,
    description: 'Fine dining, aesthetic cafes, street momos & bakeries',
    countLabel: '1.2k+ Spots',
    color: 'orange',
    gradient: 'bg-orange-100 text-orange-600',
    searchPhrases: ['Best cafes in Delhi', 'Best momos in Majnu Ka Tilla', 'Rooftop cafes CP'],
  },
  {
    _id: 'stays-living',
    id: 'stays-living',
    name: 'Hotels & PGs',
    slug: 'hotels-and-pgs',
    icon: 'Building2',
    iconName: 'Building2',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
    type: 'ROOT',
    isActive: true,
    order: 2,
    description: 'Student PGs, budget hostels, boutique stays & coliving',
    countLabel: '450+ Properties',
    color: 'emerald',
    gradient: 'bg-emerald-100 text-emerald-600',
    searchPhrases: ['Best PGs near JNU', 'Hostels in South Delhi', 'Hotels near Aerocity'],
  },
  {
    _id: 'services-repairs',
    id: 'services-repairs',
    name: 'Repair & Services',
    slug: 'repair-and-services',
    icon: 'Wrench',
    iconName: 'Wrench',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    type: 'ROOT',
    isActive: true,
    order: 3,
    description: 'Laptop/mobile repair, electronics, emergency health & pet care',
    countLabel: '890+ Listings',
    color: 'blue',
    gradient: 'bg-blue-100 text-blue-600',
    searchPhrases: ['Laptop repair near me', 'Apple repair Nehru Place', '24/7 Veterinary clinic'],
  },
  {
    _id: 'shopping-markets',
    id: 'shopping-markets',
    name: 'Shopping & Malls',
    slug: 'shopping-and-retail',
    icon: 'ShoppingBag',
    iconName: 'ShoppingBag',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
    type: 'ROOT',
    isActive: true,
    order: 4,
    description: 'Thrift markets, designer boutiques, bookshops & malls',
    countLabel: '620+ Markets',
    color: 'purple',
    gradient: 'bg-purple-100 text-purple-600',
    searchPhrases: ['Best markets in Delhi', 'Sarojini Nagar thrifting', 'Khan Market bookstores'],
  },
  {
    _id: 'places-heritage',
    id: 'places-heritage',
    name: 'Heritage & Places',
    slug: 'places-and-heritage',
    icon: 'Landmark',
    iconName: 'Landmark',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80',
    type: 'ROOT',
    isActive: true,
    order: 5,
    description: 'Historical monuments, art galleries, museums & serene parks',
    countLabel: '320+ Sights',
    color: 'indigo',
    gradient: 'bg-indigo-100 text-indigo-600',
    searchPhrases: ['Historical places in Delhi', 'Best parks in Delhi', 'Art galleries in Lutyens'],
  },
  {
    _id: 'nightlife-dates',
    id: 'nightlife-dates',
    name: 'Nightlife & Dates',
    slug: 'nightlife-and-clubs',
    icon: 'Sparkles',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    type: 'ROOT',
    isActive: true,
    order: 6,
    description: 'Romantic couple spots, live music bars & weekend clubs',
    countLabel: '410+ Venues',
    color: 'rose',
    gradient: 'bg-rose-100 text-rose-600',
    searchPhrases: ['Best date places in Delhi', 'Hauz Khas bars', 'Live gig cafes'],
  },
  {
    _id: 'fitness-wellness',
    id: 'fitness-wellness',
    name: 'Fitness & Salons',
    slug: 'fitness-and-wellness',
    icon: 'Dumbbell',
    iconName: 'Dumbbell',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    type: 'ROOT',
    isActive: true,
    order: 7,
    description: 'Elite gyms, crossfit studios, luxury spas & barbershops',
    countLabel: '520+ Studios',
    color: 'cyan',
    gradient: 'bg-cyan-100 text-cyan-600',
    searchPhrases: ['24/7 Gyms in Delhi', 'Luxury hair salons', 'Yoga centers South Delhi'],
  },
  {
    _id: 'education-coaching',
    id: 'education-coaching',
    name: 'Coaching & Courses',
    slug: 'education-and-coaching',
    icon: 'GraduationCap',
    iconName: 'GraduationCap',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    type: 'ROOT',
    isActive: true,
    order: 8,
    description: 'UPSC/IIT coaching, creative workshops & colleges',
    countLabel: '380+ Institutes',
    color: 'amber',
    gradient: 'bg-amber-100 text-amber-600',
    searchPhrases: ['Best coaching in Mukherjee Nagar', 'Coding bootcamps', 'Music institutes'],
  },
];

export const MAIN_CATEGORIES = POPULAR_CATEGORIES;
