export const ROUTES = {
  HOME: '/',
  EXPLORE: '/explore',
  CATEGORIES: '/categories',
  CATEGORY_DETAILS: '/category/:slug',
  LOCATIONS: '/locations',
  LOCATION_DETAILS: '/location/:slug',
  BUSINESSES: '/businesses',
  BUSINESS_DETAILS: '/business/:slug',
  SPOT_DETAILS: '/spot/:slug',
  SEARCH: '/search',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  SAVED: '/saved',
  COLLECTIONS: '/collections',
  ADMIN: '/admin',
  BUSINESS_DASHBOARD: '/business/dashboard',
  NOT_FOUND: '*',
} as const;
