export interface SeedCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  image: string;
  parentSlug?: string | null;
  type: 'ROOT' | 'SUBCATEGORY' | 'LEAF';
  order: number;
  seoTitle?: string;
  seoDescription?: string;
}

export interface SeedLocation {
  id: string;
  name: string;
  slug: string;
  type: 'COUNTRY' | 'STATE' | 'CITY' | 'LOCALITY';
  parentSlug?: string | null;
  country: string;
  state: string;
  city: string;
  latitude: number;
  longitude: number;
  pincode: string;
  description?: string;
  image?: string;
}

export interface SeedBusiness {
  id: string;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  categorySlug: string;
  categorySlugs: string[];
  address: string;
  locality: string;
  city: string;
  state: string;
  country: string;
  pincode: string;
  latitude: number;
  longitude: number;
  phone: string;
  email: string;
  website: string;
  images: string[];
  logo: string;
  priceRange: 'BUDGET' | 'MODERATE' | 'PREMIUM' | 'LUXURY';
  rating: number;
  reviewCount: number;
  tags: string[];
  amenities: string[];
  features: string[];
  openingHours: Record<string, string>;
  verified: boolean;
  claimed: boolean;
  status: 'ACTIVE' | 'PENDING' | 'REJECTED' | 'ARCHIVED';
}

export const SEED_TAGS = [
  'authentic-taste',
  'wifi-enabled',
  'student-friendly',
  'metro-accessible',
  'outdoor-seating',
  'budget-friendly',
  'organic',
  'laptop-repair',
  'ac-rooms',
  'heritage',
  'street-food',
  'live-music',
  'pet-friendly',
  'rooftop',
  'quick-service',
  'cashless',
  'apple-certified',
  'couple-friendly',
  'hygienic-mess',
  'family-dining',
  'power-backup',
  '24x7-access',
];

export const SEED_CATEGORIES: SeedCategory[] = [
  // 1. Root: Food & Dining
  {
    id: 'cat_food',
    name: 'Food & Dining',
    slug: 'food-dining',
    description: 'Explore Delhi culinary heritage, street food legends, cafes, and rooftop dining.',
    icon: 'Utensils',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    parentSlug: null,
    type: 'ROOT',
    order: 1,
    seoTitle: 'Best Food & Dining in Delhi NCR - SpotPicks',
    seoDescription: 'Find top restaurants, cafes, and street food in Delhi.',
  },
  {
    id: 'cat_cafes',
    name: 'Cafes & Bakeries',
    slug: 'cafes-bakeries',
    description: 'Artisanal roasteries, work-friendly coffee bars, and European style patisseries.',
    icon: 'Coffee',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'food-dining',
    type: 'SUBCATEGORY',
    order: 2,
  },
  {
    id: 'cat_street_food',
    name: 'Street Food & Chaat',
    slug: 'street-food',
    description: 'Crispy golgappas, sizzling tikkis, spicy chole bhature, and Tibetan momos.',
    icon: 'Flame',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'food-dining',
    type: 'SUBCATEGORY',
    order: 3,
  },
  {
    id: 'cat_restaurants',
    name: 'Fine Dining & Mughlai',
    slug: 'restaurants',
    description: 'Royal Mughlai curries, fragrant biryanis, and premier multicuisine restaurants.',
    icon: 'Soup',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'food-dining',
    type: 'SUBCATEGORY',
    order: 4,
  },
  {
    id: 'cat_nightlife',
    name: 'Nightlife & Bars',
    slug: 'nightlife-bars',
    description: 'Cocktail lounges, live gig spaces, craft beer taprooms, and late-night spots.',
    icon: 'Wine',
    image: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'food-dining',
    type: 'SUBCATEGORY',
    order: 5,
  },

  // 2. Root: Stays & Living
  {
    id: 'cat_stays',
    name: 'Stays & Living',
    slug: 'stays-living',
    description: 'Verified student PGs, luxury hostels, budget hotels, and serviced apartments.',
    icon: 'Building2',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80',
    parentSlug: null,
    type: 'ROOT',
    order: 6,
    seoTitle: 'Verified PGs, Hostels & Hotels in Delhi - SpotPicks',
    seoDescription: 'Find student housing, working professional PGs, and verified hotels.',
  },
  {
    id: 'cat_pgs',
    name: 'PGs & Student Hostels',
    slug: 'pgs-hostels',
    description: 'Safe, AC accommodations with mess food near North Campus, South Campus, and coaching hubs.',
    icon: 'Home',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'stays-living',
    type: 'SUBCATEGORY',
    order: 7,
  },
  {
    id: 'cat_hotels',
    name: 'Boutique & Business Hotels',
    slug: 'hotels',
    description: 'Comfortable staycations, business transit suites, and budget friendly guest houses.',
    icon: 'BedDouble',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'stays-living',
    type: 'SUBCATEGORY',
    order: 8,
  },

  // 3. Root: Shopping & Markets
  {
    id: 'cat_shopping',
    name: 'Shopping & Markets',
    slug: 'shopping-markets',
    description: 'Famous bazaars, flea markets, modern retail complexes, and boutique stores.',
    icon: 'ShoppingBag',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&auto=format&fit=crop&q=80',
    parentSlug: null,
    type: 'ROOT',
    order: 9,
  },
  {
    id: 'cat_electronics',
    name: 'Electronics & Gadgets',
    slug: 'electronics-gadgets',
    description: 'Computer hardware, custom PC builders, mobile stores, and camera equipment.',
    icon: 'Laptop',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'shopping-markets',
    type: 'SUBCATEGORY',
    order: 10,
  },
  {
    id: 'cat_clothing',
    name: 'Apparel & Ethnic Wear',
    slug: 'apparel-ethnic',
    description: 'Bridal lehengas, street fashion, custom tailoring, and contemporary designer wear.',
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'shopping-markets',
    type: 'SUBCATEGORY',
    order: 11,
  },
  {
    id: 'cat_books',
    name: 'Books & Stationery',
    slug: 'books-stationery',
    description: 'Iconic secondhand book markets, university supplies, and rare literature collections.',
    icon: 'BookOpen',
    image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'shopping-markets',
    type: 'SUBCATEGORY',
    order: 12,
  },

  // 4. Root: Places to Visit
  {
    id: 'cat_places',
    name: 'Places to Visit',
    slug: 'places-visit',
    description: 'Monuments, UNESCO world heritage sites, art galleries, and lush urban parks.',
    icon: 'Landmark',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80',
    parentSlug: null,
    type: 'ROOT',
    order: 13,
  },
  {
    id: 'cat_monuments',
    name: 'Historical Monuments',
    slug: 'historical-monuments',
    description: 'Centuries of architecture from Mughal forts to British Raj colonial heritage.',
    icon: 'Castle',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'places-visit',
    type: 'SUBCATEGORY',
    order: 14,
  },
  {
    id: 'cat_parks',
    name: 'Parks & Biodiversity Gardens',
    slug: 'parks-gardens',
    description: 'Serene morning walk trails, floral conservatories, and picnic spots.',
    icon: 'Trees',
    image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'places-visit',
    type: 'SUBCATEGORY',
    order: 15,
  },

  // 5. Root: Services & Repairs
  {
    id: 'cat_services',
    name: 'Services & Repairs',
    slug: 'services-repairs',
    description: 'Trusted technicians, salon specialists, healthcare professionals, and fit-out experts.',
    icon: 'Wrench',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    parentSlug: null,
    type: 'ROOT',
    order: 16,
  },
  {
    id: 'cat_tech_repair',
    name: 'Laptop & Mobile Repair',
    slug: 'laptop-mobile-repair',
    description: 'Same day screen replacements, MacBook logic board repairs, and chip diagnostics.',
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'services-repairs',
    type: 'SUBCATEGORY',
    order: 17,
  },
  {
    id: 'cat_salons',
    name: 'Salons, Barbers & Spa',
    slug: 'salons-spas',
    description: 'Hair styling studios, luxury grooming bars, organic spas, and nail art lounges.',
    icon: 'Scissors',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'services-repairs',
    type: 'SUBCATEGORY',
    order: 18,
  },
  {
    id: 'cat_fitness',
    name: 'Gyms & Sports Arenas',
    slug: 'gyms-fitness',
    description: 'CrossFit boxes, 24/7 fitness gyms, turf badminton arenas, and swimming pools.',
    icon: 'Dumbbell',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'services-repairs',
    type: 'SUBCATEGORY',
    order: 19,
  },

  // 6. Root: Education & Coaching
  {
    id: 'cat_education',
    name: 'Education & Coaching',
    slug: 'education-coaching',
    description: 'Colleges, competitive exam coaching institutes, and design/coding academies.',
    icon: 'GraduationCap',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    parentSlug: null,
    type: 'ROOT',
    order: 20,
  },
  {
    id: 'cat_coaching',
    name: 'UPSC & Entrance Coaching',
    slug: 'coaching-institutes',
    description: 'Top study centers and test preparation academies in Karol Bagh and Mukherjee Nagar.',
    icon: 'BookMarked',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    parentSlug: 'education-coaching',
    type: 'SUBCATEGORY',
    order: 21,
  },
];

export const SEED_LOCATIONS: SeedLocation[] = [
  {
    id: 'loc_delhi_city',
    name: 'Delhi NCR',
    slug: 'delhi',
    type: 'CITY',
    parentSlug: null,
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.6139,
    longitude: 77.209,
    pincode: '110001',
    description: 'National Capital Territory of India and cultural discovery heart.',
  },
  {
    id: 'loc_mkt',
    name: 'Majnu Ka Tilla',
    slug: 'majnu-ka-tilla',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.7028,
    longitude: 77.2274,
    pincode: '110054',
    description: 'Delhi Little Tibet famous for laphing, steamed momos, chic cafes, and Tibetan crafts.',
  },
  {
    id: 'loc_hkv',
    name: 'Hauz Khas Village',
    slug: 'hauz-khas-village',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.5535,
    longitude: 77.1944,
    pincode: '110016',
    description: 'Historic reservoir ruins alongside bohemian coffee shops, art galleries, and nightlife.',
  },
  {
    id: 'loc_cp',
    name: 'Connaught Place',
    slug: 'connaught-place',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.6315,
    longitude: 77.2167,
    pincode: '110001',
    description: 'Iconic Georgian colonnade rings with classic restaurants, bookshops, and central metro access.',
  },
  {
    id: 'loc_nehru_place',
    name: 'Nehru Place',
    slug: 'nehru-place',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.5494,
    longitude: 77.2536,
    pincode: '110019',
    description: 'Asia largest IT hardware, laptop motherboard rework, and electronics market.',
  },
  {
    id: 'loc_chandni_chowk',
    name: 'Chandni Chowk',
    slug: 'chandni-chowk',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.6506,
    longitude: 77.2303,
    pincode: '110006',
    description: 'Historic Old Delhi labyrinth of heritage paranthas, jalebis, spice bazaars, and jewelry.',
  },
  {
    id: 'loc_gtb_nagar',
    name: 'GTB Nagar (North Campus)',
    slug: 'gtb-nagar',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.6983,
    longitude: 77.2064,
    pincode: '110009',
    description: 'Youthful university epicenter packed with student PGs, cafes on Hudson Lane, and study lounges.',
  },
  {
    id: 'loc_south_ext',
    name: 'South Extension',
    slug: 'south-extension',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.5714,
    longitude: 77.2215,
    pincode: '110049',
    description: 'Premier shopping avenues for designer wedding fashion, luxury jewelry, and upscale dining.',
  },
  {
    id: 'loc_saket',
    name: 'Saket',
    slug: 'saket',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.5244,
    longitude: 77.2177,
    pincode: '110017',
    description: 'Modern lifestyle malls, Champa Gali bohemian alleys, and upscale residences.',
  },
  {
    id: 'loc_karol_bagh',
    name: 'Karol Bagh',
    slug: 'karol-bagh',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.6514,
    longitude: 77.1907,
    pincode: '110005',
    description: 'Commercial hub for electronics, wedding apparel, and UPSC civil service coaching centers.',
  },
  {
    id: 'loc_lajpat_nagar',
    name: 'Lajpat Nagar',
    slug: 'lajpat-nagar',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.5677,
    longitude: 77.2433,
    pincode: '110024',
    description: 'Famous Central Market for fabrics, Afghan food enclave, and street fashion.',
  },
  {
    id: 'loc_dwarka',
    name: 'Dwarka',
    slug: 'dwarka',
    type: 'LOCALITY',
    parentSlug: 'delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    latitude: 28.5921,
    longitude: 77.046,
    pincode: '110075',
    description: 'Planned sub-city with broad avenues, sports complexes, and family food plazas.',
  },
];

// Comprehensive 52 Demo Businesses across categories and localities
export const SEED_BUSINESSES: SeedBusiness[] = [
  // 1. Majnu Ka Tilla - Cafes & Food
  {
    id: 'biz_01',
    name: 'AMA Cafe & Bakery',
    slug: 'ama-cafe-bakery',
    description: 'Iconic Himalayan-themed cafe serving artisanal espresso, blueberry cheesecakes, fluffy American pancakes, and fresh breakfast platters in the heart of Tibetan Colony.',
    shortDescription: 'Multi-story Himalayan cafe famous for cheesecakes & mountain coffee.',
    categorySlug: 'cafes-bakeries',
    categorySlugs: ['cafes-bakeries', 'food-dining'],
    address: 'House 38, New Tibetan Colony, Majnu Ka Tilla',
    locality: 'Majnu Ka Tilla',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110054',
    latitude: 28.7029,
    longitude: 77.2275,
    phone: '+91 11 2381 2345',
    email: 'hello@amacafe.demo.in',
    website: 'https://amacafe.demo.in',
    images: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=200&auto=format&fit=crop&q=80',
    priceRange: 'MODERATE',
    rating: 4.8,
    reviewCount: 3840,
    tags: ['authentic-taste', 'wifi-enabled', 'student-friendly', 'metro-accessible', 'couple-friendly'],
    amenities: ['High-speed WiFi', 'Air Conditioned', 'Vegan Options', 'Card Payments', 'Bakery Counter'],
    features: ['Mountain Roasts', 'Signature Cheesecakes', 'Breakfast All Day'],
    openingHours: {
      Monday: '07:30 AM - 10:00 PM',
      Tuesday: '07:30 AM - 10:00 PM',
      Wednesday: '07:30 AM - 10:00 PM',
      Thursday: '07:30 AM - 10:00 PM',
      Friday: '07:30 AM - 10:30 PM',
      Saturday: '07:30 AM - 10:30 PM',
      Sunday: '07:30 AM - 10:30 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_02',
    name: 'Tee Dee Tibetan Kitchen',
    slug: 'tee-dee-tibetan-kitchen',
    description: 'Family-run heritage Tibetan restaurant known for soupy Thukpa, Tingmo with chilli pork, crispy fried shabalay, and Tibetan butter tea.',
    shortDescription: 'Legendary spot for authentic Tibetan thukpa and steamed momos.',
    categorySlug: 'street-food',
    categorySlugs: ['street-food', 'food-dining'],
    address: 'Block 32, Aruna Nagar, Majnu Ka Tilla',
    locality: 'Majnu Ka Tilla',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110054',
    latitude: 28.7025,
    longitude: 77.2272,
    phone: '+91 11 2381 5678',
    email: 'teedee@kitchen.demo.in',
    website: '',
    images: [
      'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'BUDGET',
    rating: 4.7,
    reviewCount: 2150,
    tags: ['street-food', 'authentic-taste', 'budget-friendly', 'student-friendly'],
    amenities: ['Seating Available', 'UPI Accepted', 'Takeaway'],
    features: ['Handmade Noodles', 'Authentic Laphing', 'Herbal Soups'],
    openingHours: {
      Monday: '11:00 AM - 10:00 PM',
      Tuesday: '11:00 AM - 10:00 PM',
      Wednesday: '11:00 AM - 10:00 PM',
      Thursday: '11:00 AM - 10:00 PM',
      Friday: '11:00 AM - 10:00 PM',
      Saturday: '11:00 AM - 10:30 PM',
      Sunday: '11:00 AM - 10:30 PM',
    },
    verified: true,
    claimed: false,
    status: 'ACTIVE',
  },

  // 2. Hauz Khas Village - Cafes, Stays & Boutiques
  {
    id: 'biz_03',
    name: 'Social Offline Hauz Khas',
    slug: 'social-offline-hkv',
    description: 'Iconic multi-level workspace and vibrant cafe overlooking the serene 13th-century Hauz Khas monument tank. Serves innovative fusion cocktails and gourmet comfort food.',
    shortDescription: 'Lakeside co-working cafe & energetic evening lounge.',
    categorySlug: 'nightlife-bars',
    categorySlugs: ['nightlife-bars', 'cafes-bakeries', 'food-dining'],
    address: '9A & 12, Hauz Khas Village',
    locality: 'Hauz Khas Village',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110016',
    latitude: 28.5538,
    longitude: 77.1947,
    phone: '+91 78386 52814',
    email: 'hkv@socialoffline.demo.in',
    website: 'https://socialoffline.demo.in',
    images: [
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'MODERATE',
    rating: 4.6,
    reviewCount: 5600,
    tags: ['wifi-enabled', 'live-music', 'rooftop', 'couple-friendly'],
    amenities: ['Monument View', 'Fast WiFi', 'Cocktail Bar', 'Live DJs', 'Valet Parking'],
    features: ['Craft Cocktails', 'Lake View Seating', 'Work Desks'],
    openingHours: {
      Monday: '11:00 AM - 12:30 AM',
      Tuesday: '11:00 AM - 12:30 AM',
      Wednesday: '11:00 AM - 12:30 AM',
      Thursday: '11:00 AM - 12:30 AM',
      Friday: '11:00 AM - 01:00 AM',
      Saturday: '11:00 AM - 01:00 AM',
      Sunday: '11:00 AM - 12:30 AM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_04',
    name: 'Hauz Khas Fort & Reservoir Ruins',
    slug: 'hauz-khas-fort-ruins',
    description: 'Historic complex built by Alauddin Khilji featuring a medieval madrasa, tomb of Firoz Shah Tughlaq, and tranquil sunset views over the deer park lake.',
    shortDescription: '13th-century stone heritage complex with panoramic reservoir views.',
    categorySlug: 'historical-monuments',
    categorySlugs: ['historical-monuments', 'places-visit'],
    address: 'Deer Park, Hauz Khas Village',
    locality: 'Hauz Khas Village',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110016',
    latitude: 28.5528,
    longitude: 77.1942,
    phone: '',
    email: '',
    website: '',
    images: [
      'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'BUDGET',
    rating: 4.8,
    reviewCount: 9200,
    tags: ['heritage', 'outdoor-seating', 'couple-friendly'],
    amenities: ['Public Walking Track', 'ASI Ticket Counter', 'Photography Allowed'],
    features: ['Archaeological Heritage', 'Sunset Point', 'Green Park Gardens'],
    openingHours: {
      Monday: '06:00 AM - 06:30 PM',
      Tuesday: '06:00 AM - 06:30 PM',
      Wednesday: '06:00 AM - 06:30 PM',
      Thursday: '06:00 AM - 06:30 PM',
      Friday: '06:00 AM - 06:30 PM',
      Saturday: '06:00 AM - 06:30 PM',
      Sunday: '06:00 AM - 06:30 PM',
    },
    verified: true,
    claimed: false,
    status: 'ACTIVE',
  },

  // 3. Nehru Place - IT & Laptop Repairs
  {
    id: 'biz_05',
    name: 'MacRework Apple Tech Hub',
    slug: 'macrework-apple-tech-hub',
    description: 'Premier Apple and gaming laptop repair center specializing in MacBook logic board chip rework, GPU reballing, Retina screen replacement, and liquid damage recovery.',
    shortDescription: 'Certified MacBook & laptop motherboard chip-level repair lab.',
    categorySlug: 'laptop-mobile-repair',
    categorySlugs: ['laptop-mobile-repair', 'electronics-gadgets', 'services-repairs'],
    address: 'G-14, Deepali Building, 92 Nehru Place',
    locality: 'Nehru Place',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110019',
    latitude: 28.5498,
    longitude: 77.2539,
    phone: '+91 11 4160 8899',
    email: 'support@macrework.demo.in',
    website: 'https://macrework.demo.in',
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'MODERATE',
    rating: 4.9,
    reviewCount: 1420,
    tags: ['laptop-repair', 'apple-certified', 'quick-service', 'metro-accessible'],
    amenities: ['Same Day Service', 'Warranty on Repairs', 'Original Spare Parts', 'Diagnostic Lab'],
    features: ['Logic Board Rework', 'Instant Screen Swap', 'Data Recovery'],
    openingHours: {
      Monday: '10:30 AM - 08:30 PM',
      Tuesday: '10:30 AM - 08:30 PM',
      Wednesday: '10:30 AM - 08:30 PM',
      Thursday: '10:30 AM - 08:30 PM',
      Friday: '10:30 AM - 08:30 PM',
      Saturday: '10:30 AM - 08:30 PM',
      Sunday: 'Closed',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_06',
    name: 'Cost to Cost Hardware Store',
    slug: 'cost-to-cost-hardware',
    description: 'Renowned destination for high performance custom gaming rigs, NVIDIA graphics cards, processors, monitors, and wholesale priced computer components.',
    shortDescription: 'Legendary PC hardware & custom gaming rig building outlet.',
    categorySlug: 'electronics-gadgets',
    categorySlugs: ['electronics-gadgets', 'shopping-markets'],
    address: 'Farm Bhawan, 14 Nehru Place',
    locality: 'Nehru Place',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110019',
    latitude: 28.5492,
    longitude: 77.2532,
    phone: '+91 11 2648 4000',
    email: 'sales@costtocost.demo.in',
    website: 'https://costtocost.demo.in',
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'MODERATE',
    rating: 4.5,
    reviewCount: 4200,
    tags: ['budget-friendly', 'metro-accessible', 'cashless'],
    amenities: ['On-site PC Assembly', 'GST Invoicing', 'Brand Warranty'],
    features: ['Wholesale Rates', 'Custom Liquid Cooling', 'Gaming Accessories'],
    openingHours: {
      Monday: '11:00 AM - 08:00 PM',
      Tuesday: '11:00 AM - 08:00 PM',
      Wednesday: '11:00 AM - 08:00 PM',
      Thursday: '11:00 AM - 08:00 PM',
      Friday: '11:00 AM - 08:00 PM',
      Saturday: '11:00 AM - 08:00 PM',
      Sunday: 'Closed',
    },
    verified: true,
    claimed: false,
    status: 'ACTIVE',
  },

  // 4. GTB Nagar / North Campus - Student PGs & Hudson Lane Cafes
  {
    id: 'biz_07',
    name: 'North Campus Scholar Residency (Girls & Boys PG)',
    slug: 'north-campus-scholar-residency',
    description: 'Modern student living with fully furnished air-conditioned single & twin sharing rooms, high-speed fiber internet, 4-time hygienic home meals, biometric entry, and study lounges near DU North Campus colleges.',
    shortDescription: 'Premium AC student accommodation with meals & biometric security.',
    categorySlug: 'pgs-hostels',
    categorySlugs: ['pgs-hostels', 'stays-living'],
    address: 'F-14/2, Vijay Nagar, near GTB Nagar Metro Station',
    locality: 'GTB Nagar',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110009',
    latitude: 28.6985,
    longitude: 77.2067,
    phone: '+91 98110 54321',
    email: 'stay@scholarsresidency.demo.in',
    website: 'https://scholarsresidency.demo.in',
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'MODERATE',
    rating: 4.8,
    reviewCount: 310,
    tags: ['student-friendly', 'ac-rooms', 'wifi-enabled', 'hygienic-mess', 'power-backup', '24x7-access'],
    amenities: ['4-Time Meals Included', '100 Mbps WiFi', 'Laundry Service', '24/7 CCTV & Security', 'Power Backup'],
    features: ['Attached Bathrooms', 'Daily Housekeeping', 'Walking Distance to Metro'],
    openingHours: {
      Monday: 'Open 24 Hours',
      Tuesday: 'Open 24 Hours',
      Wednesday: 'Open 24 Hours',
      Thursday: 'Open 24 Hours',
      Friday: 'Open 24 Hours',
      Saturday: 'Open 24 Hours',
      Sunday: 'Open 24 Hours',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_08',
    name: 'Hudson Cafe & Eatery',
    slug: 'hudson-cafe-eatery',
    description: 'Vibrant student hub on Hudson Lane featuring quirky wall art, loaded monster shakes, cheesy baked pastas, thin crust pizzas, and pocket-friendly combos.',
    shortDescription: 'Lively student favorite for loaded shakes and artisan pizzas.',
    categorySlug: 'cafes-bakeries',
    categorySlugs: ['cafes-bakeries', 'food-dining'],
    address: '2524, 1st Floor, Hudson Lane, Kingsway Camp',
    locality: 'GTB Nagar',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110009',
    latitude: 28.6991,
    longitude: 77.2059,
    phone: '+91 11 4702 9999',
    email: 'info@hudsoncafe.demo.in',
    website: '',
    images: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'BUDGET',
    rating: 4.6,
    reviewCount: 3100,
    tags: ['student-friendly', 'budget-friendly', 'wifi-enabled', 'couple-friendly'],
    amenities: ['Air Conditioned', 'Student Discounts', 'Board Games', 'Takeaway'],
    features: ['Monster Shakes', 'Wood-fired Pizza', 'Group Platter Deals'],
    openingHours: {
      Monday: '11:00 AM - 11:00 PM',
      Tuesday: '11:00 AM - 11:00 PM',
      Wednesday: '11:00 AM - 11:00 PM',
      Thursday: '11:00 AM - 11:00 PM',
      Friday: '11:00 AM - 11:00 PM',
      Saturday: '11:00 AM - 11:00 PM',
      Sunday: '11:00 AM - 11:00 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },

  // 5. Connaught Place - Fine Dining, Heritage & Books
  {
    id: 'biz_09',
    name: 'United Coffee House',
    slug: 'united-coffee-house',
    description: 'Heritage culinary institution established in 1942, boasting grand crystal chandeliers, Victorian decor, signature Cona coffee, Keema Samosas, and classic Continental dishes.',
    shortDescription: 'Legendary 1942 colonial dining institution in Inner Circle CP.',
    categorySlug: 'restaurants',
    categorySlugs: ['restaurants', 'food-dining'],
    address: 'E-15, Inner Circle, Connaught Place',
    locality: 'Connaught Place',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110001',
    latitude: 28.6325,
    longitude: 77.2185,
    phone: '+91 11 2341 6075',
    email: 'contact@uchdelhi.demo.in',
    website: 'https://uchdelhi.demo.in',
    images: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'PREMIUM',
    rating: 4.7,
    reviewCount: 4800,
    tags: ['heritage', 'family-dining', 'authentic-taste'],
    amenities: ['Valet Parking', 'Cocktail Bar', 'Private Dining', 'Wheelchair Accessible'],
    features: ['Classic Cona Coffee', 'Vintage Ambience', 'Heritage Recipes'],
    openingHours: {
      Monday: '09:30 AM - 11:30 PM',
      Tuesday: '09:30 AM - 11:30 PM',
      Wednesday: '09:30 AM - 11:30 PM',
      Thursday: '09:30 AM - 11:30 PM',
      Friday: '09:30 AM - 11:30 PM',
      Saturday: '09:30 AM - 11:30 PM',
      Sunday: '09:30 AM - 11:30 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_10',
    name: 'Oxford Bookstore & Cha Bar',
    slug: 'oxford-bookstore-cha-bar',
    description: 'Iconic intellectual sanctuary stocking curated world literature, Indian philosophy, and design tomes alongside over 60 varieties of tea from Darjeeling to Nilgiris.',
    shortDescription: 'Famous bookstore with serene tea lounge in CP.',
    categorySlug: 'books-stationery',
    categorySlugs: ['books-stationery', 'cafes-bakeries', 'shopping-markets'],
    address: 'N-81, Barakhamba Road, Connaught Place',
    locality: 'Connaught Place',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110001',
    latitude: 28.6305,
    longitude: 77.2205,
    phone: '+91 11 3350 4919',
    email: 'chabar@oxfordbookstore.demo.in',
    website: 'https://oxfordbookstore.demo.in',
    images: [
      'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'MODERATE',
    rating: 4.8,
    reviewCount: 3900,
    tags: ['wifi-enabled', 'student-friendly', 'quiet-workspace', 'metro-accessible'],
    amenities: ['Tea Bar', 'Author Signings', 'Reading Corners', 'Air Conditioned'],
    features: ['60+ Specialty Teas', 'Rare Book Selection', 'Work Friendly'],
    openingHours: {
      Monday: '10:00 AM - 09:00 PM',
      Tuesday: '10:00 AM - 09:00 PM',
      Wednesday: '10:00 AM - 09:00 PM',
      Thursday: '10:00 AM - 09:00 PM',
      Friday: '10:00 AM - 09:00 PM',
      Saturday: '10:00 AM - 09:00 PM',
      Sunday: '10:00 AM - 09:00 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },

  // 6. Chandni Chowk - Street Food & Heritage
  {
    id: 'biz_11',
    name: 'Old Famous Jalebi Wala (Est. 1884)',
    slug: 'old-famous-jalebi-wala',
    description: 'Century-old sweet shop frying giant golden jalebis in pure desi ghee over charcoal fire, served hot with thick creamy rabri at Dariba Kalan corner.',
    shortDescription: 'Legendary 1884 shop for charcoal-fried pure desi ghee jalebis.',
    categorySlug: 'street-food',
    categorySlugs: ['street-food', 'food-dining'],
    address: 'Corner Dariba Kalan, Chandni Chowk',
    locality: 'Chandni Chowk',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110006',
    latitude: 28.6565,
    longitude: 77.2315,
    phone: '+91 11 2325 6976',
    email: '',
    website: '',
    images: [
      'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'BUDGET',
    rating: 4.8,
    reviewCount: 7800,
    tags: ['heritage', 'authentic-taste', 'street-food', 'budget-friendly'],
    amenities: ['Takeaway', 'UPI Accepted', 'Fresh Batch Every 15 mins'],
    features: ['Charcoal Fired Desi Ghee', 'Thick Malai Rabri', 'Historic 1884 Legacy'],
    openingHours: {
      Monday: '08:00 AM - 10:00 PM',
      Tuesday: '08:00 AM - 10:00 PM',
      Wednesday: '08:00 AM - 10:00 PM',
      Thursday: '08:00 AM - 10:00 PM',
      Friday: '08:00 AM - 10:00 PM',
      Saturday: '08:00 AM - 10:00 PM',
      Sunday: '08:00 AM - 10:00 PM',
    },
    verified: true,
    claimed: false,
    status: 'ACTIVE',
  },
  {
    id: 'biz_12',
    name: 'Pt. Kanhaiyalal Durgaprasad Paranthe Wale (1875)',
    slug: 'paranthe-wali-gali-kanhaiyalal',
    description: 'Centuries-old heritage eatery in Paranthe Wali Gali frying stuffed paranthas (rabri, papad, kaju, paneer, and mirchi) served with sweet tamarind dip and spicy pumpkin subzi.',
    shortDescription: '1875 iconic Paranthe Wali Gali institution with 30+ stuffing varieties.',
    categorySlug: 'street-food',
    categorySlugs: ['street-food', 'food-dining'],
    address: '1984, Gali Paranthe Wali, Chandni Chowk',
    locality: 'Chandni Chowk',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110006',
    latitude: 28.6558,
    longitude: 77.2309,
    phone: '+91 98112 34567',
    email: '',
    website: '',
    images: [
      'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'BUDGET',
    rating: 4.6,
    reviewCount: 6500,
    tags: ['heritage', 'street-food', 'authentic-taste'],
    amenities: ['Air Cooled Dining', 'Vegetarian Only', 'Quick Service'],
    features: ['Kaju & Rabri Paranthas', 'Sweet Saunth Chutney', 'Historic Walk'],
    openingHours: {
      Monday: '09:00 AM - 11:00 PM',
      Tuesday: '09:00 AM - 11:00 PM',
      Wednesday: '09:00 AM - 11:00 PM',
      Thursday: '09:00 AM - 11:00 PM',
      Friday: '09:00 AM - 11:00 PM',
      Saturday: '09:00 AM - 11:00 PM',
      Sunday: '09:00 AM - 11:00 PM',
    },
    verified: true,
    claimed: false,
    status: 'ACTIVE',
  },

  // 7. Karol Bagh - UPSC Coaching & Electronics
  {
    id: 'biz_13',
    name: 'Vajiram & Ravi IAS Institute',
    slug: 'vajiram-and-ravi-ias',
    description: 'Pioneering civil service examination preparation academy with distinguished faculty, comprehensive study materials, test series, and mentorship programs for UPSC aspirants.',
    shortDescription: 'Premier UPSC Civil Services test preparation academy in Karol Bagh.',
    categorySlug: 'coaching-institutes',
    categorySlugs: ['coaching-institutes', 'education-coaching'],
    address: '9-B, Bada Bazaar Road, Old Rajinder Nagar, Karol Bagh',
    locality: 'Karol Bagh',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110060',
    latitude: 28.6415,
    longitude: 77.1852,
    phone: '+91 11 4100 7400',
    email: 'admissions@vajiramandravi.demo.in',
    website: 'https://vajiramandravi.demo.in',
    images: [
      'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'PREMIUM',
    rating: 4.8,
    reviewCount: 3800,
    tags: ['student-friendly', 'metro-accessible'],
    amenities: ['Library Access', 'Online Portal', 'Air Conditioned Lecture Halls', 'Doubt Clearing Cells'],
    features: ['Top UPSC Rankers Mentorship', 'Comprehensive Test Series', 'Current Affairs Hub'],
    openingHours: {
      Monday: '08:00 AM - 07:00 PM',
      Tuesday: '08:00 AM - 07:00 PM',
      Wednesday: '08:00 AM - 07:00 PM',
      Thursday: '08:00 AM - 07:00 PM',
      Friday: '08:00 AM - 07:00 PM',
      Saturday: '08:00 AM - 07:00 PM',
      Sunday: '09:00 AM - 02:00 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_14',
    name: 'Gaffar Market Mobile & Gadget Care',
    slug: 'gaffar-market-mobile-care',
    description: 'Renowned electronic technician collective offering instant iPhone screen replacements, OLED displays, camera lens replacements, and micro-soldering for all smartphone brands.',
    shortDescription: 'High-speed smartphone repairs & gadget accessories in Gaffar Market.',
    categorySlug: 'laptop-mobile-repair',
    categorySlugs: ['laptop-mobile-repair', 'electronics-gadgets', 'services-repairs'],
    address: 'Shop 42, Main Gaffar Market, Karol Bagh',
    locality: 'Karol Bagh',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110005',
    latitude: 28.6525,
    longitude: 77.1912,
    phone: '+91 98990 11223',
    email: 'info@gaffarmobile.demo.in',
    website: '',
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'BUDGET',
    rating: 4.6,
    reviewCount: 2900,
    tags: ['budget-friendly', 'quick-service', 'metro-accessible'],
    amenities: ['15-Minute Screen Swap', 'Water Damage Restoration', 'Tempered Glass Fitting'],
    features: ['Original OEM Panels', 'Transparent Pricing', 'Wholesale Covers'],
    openingHours: {
      Monday: 'Closed',
      Tuesday: '10:30 AM - 08:30 PM',
      Wednesday: '10:30 AM - 08:30 PM',
      Thursday: '10:30 AM - 08:30 PM',
      Friday: '10:30 AM - 08:30 PM',
      Saturday: '10:30 AM - 08:30 PM',
      Sunday: '10:30 AM - 08:30 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },

  // 8. Saket & Champa Gali - Cafes & Spas
  {
    id: 'biz_15',
    name: 'Blue Tokai Coffee Roasters (Champa Gali)',
    slug: 'blue-tokai-champa-gali',
    description: 'Rustic artisanal coffee house tucked in the fairy-lit alleys of Champa Gali, serving single estate pour-overs, nitro cold brews, freshly baked sourdough croissants, and vegan treats.',
    shortDescription: 'Bohemian cafe with fairy-light lane & single-origin coffee roasts.',
    categorySlug: 'cafes-bakeries',
    categorySlugs: ['cafes-bakeries', 'food-dining'],
    address: 'Khasra 258, Lane 3, Champa Gali, Saidulajab, Saket',
    locality: 'Saket',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110017',
    latitude: 28.5185,
    longitude: 77.2025,
    phone: '+91 98211 26015',
    email: 'champagali@bluetokaicoffee.demo.in',
    website: 'https://bluetokaicoffee.demo.in',
    images: [
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'MODERATE',
    rating: 4.8,
    reviewCount: 4100,
    tags: ['wifi-enabled', 'pet-friendly', 'outdoor-seating', 'couple-friendly', 'organic'],
    amenities: ['Pet Friendly Patio', 'Pour Over Bar', 'Fast WiFi', 'Art Displays'],
    features: ['Single-Estate Indian Beans', 'Artisan Sourdough', 'Fairy Light Garden'],
    openingHours: {
      Monday: '08:30 AM - 10:30 PM',
      Tuesday: '08:30 AM - 10:30 PM',
      Wednesday: '08:30 AM - 10:30 PM',
      Thursday: '08:30 AM - 10:30 PM',
      Friday: '08:30 AM - 11:00 PM',
      Saturday: '08:30 AM - 11:00 PM',
      Sunday: '08:30 AM - 11:00 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_16',
    name: 'Aroma Sanctuary Luxury Day Spa',
    slug: 'aroma-sanctuary-spa-saket',
    description: 'Holistic wellness and rejuvenation spa offering Balinese massages, Ayurvedic potli therapies, Swedish body scrubs, and detox facial rituals by certified therapists.',
    shortDescription: 'Premier wellness retreat offering authentic Balinese & Ayurvedic therapies.',
    categorySlug: 'salons-spas',
    categorySlugs: ['salons-spas', 'services-repairs'],
    address: 'Level 2, District Centre, Saket',
    locality: 'Saket',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110017',
    latitude: 28.5275,
    longitude: 77.2185,
    phone: '+91 11 4655 8800',
    email: 'wellness@aromasanctuary.demo.in',
    website: 'https://aromasanctuary.demo.in',
    images: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'PREMIUM',
    rating: 4.9,
    reviewCount: 880,
    tags: ['couple-friendly', 'organic', 'cashless'],
    amenities: ['Steam & Sauna', 'Couple Massage Suites', 'Organic Herbal Oils', 'Valet Parking'],
    features: ['Deep Tissue Therapy', 'Balinese Massage', 'Ayurvedic Detox'],
    openingHours: {
      Monday: '10:00 AM - 09:00 PM',
      Tuesday: '10:00 AM - 09:00 PM',
      Wednesday: '10:00 AM - 09:00 PM',
      Thursday: '10:00 AM - 09:00 PM',
      Friday: '10:00 AM - 09:00 PM',
      Saturday: '10:00 AM - 09:30 PM',
      Sunday: '10:00 AM - 09:30 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },

  // 9. South Extension - Gyms & Salons & Jewelry
  {
    id: 'biz_17',
    name: 'IronCore CrossFit & 24/7 Fitness',
    slug: 'ironcore-crossfit-south-ext',
    description: 'State-of-the-art strength conditioning facility featuring Olympic lifting platforms, Eleiko weights, turf tracks, functional HIIT classes, and personalized sports nutrition coaching.',
    shortDescription: '24/7 high performance gym with Olympic lifting & CrossFit boxes.',
    categorySlug: 'gyms-fitness',
    categorySlugs: ['gyms-fitness', 'services-repairs'],
    address: 'E-28, South Extension Part 2',
    locality: 'South Extension',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110049',
    latitude: 28.5695,
    longitude: 77.2195,
    phone: '+91 11 4164 5500',
    email: 'info@ironcorefitness.demo.in',
    website: 'https://ironcorefitness.demo.in',
    images: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'PREMIUM',
    rating: 4.9,
    reviewCount: 1120,
    tags: ['24x7-access', 'power-backup', 'metro-accessible'],
    amenities: ['24/7 Access with Keycard', 'Certified Trainers', 'Shower & Sauna', 'Protein Bar'],
    features: ['Olympic Lifting Racks', 'Calisthenics Rig', 'Nutritional Counseling'],
    openingHours: {
      Monday: 'Open 24 Hours',
      Tuesday: 'Open 24 Hours',
      Wednesday: 'Open 24 Hours',
      Thursday: 'Open 24 Hours',
      Friday: 'Open 24 Hours',
      Saturday: 'Open 24 Hours',
      Sunday: 'Open 24 Hours',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_18',
    name: 'Geetanjali Salon & Studio',
    slug: 'geetanjali-salon-south-ext',
    description: 'Award-winning hair and beauty salon offering precision styling by senior creative directors, Balayage color transformations, Keratin treatments, and bridal makeovers.',
    shortDescription: 'Luxury hair couture, bespoke coloring & professional skin salon.',
    categorySlug: 'salons-spas',
    categorySlugs: ['salons-spas', 'services-repairs'],
    address: 'F-41, South Extension Part 1',
    locality: 'South Extension',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110049',
    latitude: 28.5722,
    longitude: 77.2218,
    phone: '+91 11 2469 8811',
    email: 'southext@geetanjalisalon.demo.in',
    website: 'https://geetanjalisalon.demo.in',
    images: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'PREMIUM',
    rating: 4.8,
    reviewCount: 2300,
    tags: ['metro-accessible', 'cashless'],
    amenities: ['L’Oreal & Kerastase Care', 'Private Bridal Suite', 'Beverage Bar'],
    features: ['Balayage Masters', 'Olaplex Treatments', 'Airbrush Makeup'],
    openingHours: {
      Monday: '10:00 AM - 08:30 PM',
      Tuesday: '10:00 AM - 08:30 PM',
      Wednesday: '10:00 AM - 08:30 PM',
      Thursday: '10:00 AM - 08:30 PM',
      Friday: '10:00 AM - 08:30 PM',
      Saturday: '10:00 AM - 08:30 PM',
      Sunday: '10:00 AM - 08:30 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },

  // 10. Lajpat Nagar - Food & Markets
  {
    id: 'biz_19',
    name: 'Dolma Aunty Momos (Est. 1994)',
    slug: 'dolma-aunty-momos-lajpat-nagar',
    description: 'Delhi legendary momo pioneer stall in Central Market, famous for thin-skinned juicy steamed momos served with signature fiery garlic red chilli sauce.',
    shortDescription: 'Delhi original street momo destination since 1994.',
    categorySlug: 'street-food',
    categorySlugs: ['street-food', 'food-dining'],
    address: 'Shop 39-B, Central Market, Lajpat Nagar 2',
    locality: 'Lajpat Nagar',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110024',
    latitude: 28.5682,
    longitude: 77.2441,
    phone: '+91 98118 76543',
    email: '',
    website: '',
    images: [
      'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'BUDGET',
    rating: 4.7,
    reviewCount: 9400,
    tags: ['street-food', 'authentic-taste', 'budget-friendly', 'quick-service'],
    amenities: ['Takeaway', 'Quick Service', 'UPI Accepted'],
    features: ['Original 1994 Recipe', 'Fiery Red Sauce', 'Steamed & Fried Momos'],
    openingHours: {
      Monday: '01:00 PM - 10:00 PM',
      Tuesday: '01:00 PM - 10:00 PM',
      Wednesday: '01:00 PM - 10:00 PM',
      Thursday: '01:00 PM - 10:00 PM',
      Friday: '01:00 PM - 10:00 PM',
      Saturday: '01:00 PM - 10:00 PM',
      Sunday: '01:00 PM - 10:00 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_20',
    name: 'Kabul Delhi Afghan Restaurant',
    slug: 'kabul-delhi-afghan-restaurant',
    description: 'Authentic Afghan food enclave dining featuring aromatic Kabuli Uzbeki pulao with raisins and carrots, charcoal-smoked lamb tikka kebabs, and warm borani banjan.',
    shortDescription: 'Traditional Afghan cuisine with authentic Kabuli pulao & tender kebabs.',
    categorySlug: 'restaurants',
    categorySlugs: ['restaurants', 'food-dining'],
    address: 'E-42, Ground Floor, Central Market, Lajpat Nagar 2',
    locality: 'Lajpat Nagar',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110024',
    latitude: 28.5672,
    longitude: 77.2435,
    phone: '+91 11 2984 3322',
    email: 'info@kabuldelhi.demo.in',
    website: '',
    images: [
      'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'MODERATE',
    rating: 4.8,
    reviewCount: 3400,
    tags: ['authentic-taste', 'family-dining', 'budget-friendly'],
    amenities: ['Floor Seating & Tables', 'Halal Certified', 'Family Rooms', 'Takeaway'],
    features: ['Uzbeki Kabuli Pulao', 'Afghan Naan', 'Qabuli Mutton Tandoor'],
    openingHours: {
      Monday: '12:00 PM - 11:00 PM',
      Tuesday: '12:00 PM - 11:00 PM',
      Wednesday: '12:00 PM - 11:00 PM',
      Thursday: '12:00 PM - 11:00 PM',
      Friday: '12:00 PM - 11:00 PM',
      Saturday: '12:00 PM - 11:00 PM',
      Sunday: '12:00 PM - 11:00 PM',
    },
    verified: true,
    claimed: false,
    status: 'ACTIVE',
  },

  // 11. Dwarka & Vasant Kunj - Stays & Parks
  {
    id: 'biz_21',
    name: 'Dwarka Sports & Badminton Arena',
    slug: 'dwarka-sports-badminton-arena',
    description: 'Premier multi-sport complex offering BWF-standard wooden badminton courts, synthetic turf football fields, tennis courts, and certified coaching academies.',
    shortDescription: 'Tournament grade indoor badminton courts & turf football ground.',
    categorySlug: 'gyms-fitness',
    categorySlugs: ['gyms-fitness', 'services-repairs'],
    address: 'Sector 11, near Metro Station, Dwarka',
    locality: 'Dwarka',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110075',
    latitude: 28.5885,
    longitude: 77.0515,
    phone: '+91 11 2808 6677',
    email: 'play@dwarkasports.demo.in',
    website: 'https://dwarkasports.demo.in',
    images: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'BUDGET',
    rating: 4.7,
    reviewCount: 1650,
    tags: ['student-friendly', 'metro-accessible', 'power-backup'],
    amenities: ['Floodlit Courts', 'Locker Rooms', 'Equipment Rental', 'Parking'],
    features: ['6 BWF Wooden Courts', 'Turf Football 7v7', 'Weekend Tournaments'],
    openingHours: {
      Monday: '06:00 AM - 11:00 PM',
      Tuesday: '06:00 AM - 11:00 PM',
      Wednesday: '06:00 AM - 11:00 PM',
      Thursday: '06:00 AM - 11:00 PM',
      Friday: '06:00 AM - 11:00 PM',
      Saturday: '06:00 AM - 11:00 PM',
      Sunday: '06:00 AM - 11:00 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  {
    id: 'biz_22',
    name: 'Sunder Nursery Heritage Park',
    slug: 'sunder-nursery-heritage-park',
    description: 'Delhi breathtaking 16th-century Mughal garden spread across 90 acres with restored UNESCO monuments, tranquil lotus ponds, artisan weekend farmers markets, and rare botanical trees.',
    shortDescription: '90-acre Mughal botanical park with restored heritage monuments & lakes.',
    categorySlug: 'parks-gardens',
    categorySlugs: ['parks-gardens', 'places-visit', 'historical-monuments'],
    address: 'Bharat Scouts and Guides Marg, Nizamuddin East',
    locality: 'Connaught Place',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110013',
    latitude: 28.5945,
    longitude: 77.2485,
    phone: '+91 11 4070 0700',
    email: 'info@sundernursery.demo.in',
    website: 'https://sundernursery.demo.in',
    images: [
      'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800&auto=format&fit=crop&q=80',
    ],
    logo: '',
    priceRange: 'BUDGET',
    rating: 4.9,
    reviewCount: 14500,
    tags: ['heritage', 'pet-friendly', 'outdoor-seating', 'family-dining', 'organic'],
    amenities: ['Botanical Nursery', 'Lakeside Seating', 'Weekend Organic Market', 'Clean Restrooms'],
    features: ['15 Restored Monuments', 'Lotus Pond Walkway', 'Birdwatching Sanctuary'],
    openingHours: {
      Monday: '07:00 AM - 10:00 PM',
      Tuesday: '07:00 AM - 10:00 PM',
      Wednesday: '07:00 AM - 10:00 PM',
      Thursday: '07:00 AM - 10:00 PM',
      Friday: '07:00 AM - 10:00 PM',
      Saturday: '07:00 AM - 10:00 PM',
      Sunday: '07:00 AM - 10:00 PM',
    },
    verified: true,
    claimed: true,
    status: 'ACTIVE',
  },
  // Additional 30 items dynamically augmented in seed generator to reach 52+ verified records
];

// Helper to generate the remaining structured demo businesses to achieve 52+ complete spots
export const generateFullDemoBusinesses = (): SeedBusiness[] => {
  const result: SeedBusiness[] = [...SEED_BUSINESSES];
  const prefixes = [
    { name: 'Heritage Haveli Kitchen', cat: 'restaurants', price: 'PREMIUM' as const, loc: 'Chandni Chowk', tag: 'authentic-taste', rating: 4.8 },
    { name: 'Keventers Classic Milkshakes', cat: 'street-food', price: 'BUDGET' as const, loc: 'Connaught Place', tag: 'quick-service', rating: 4.7 },
    { name: 'CyberLogic Apple Repair Specialist', cat: 'laptop-mobile-repair', price: 'MODERATE' as const, loc: 'Nehru Place', tag: 'laptop-repair', rating: 4.9 },
    { name: 'Tenzin Laphing & Momo Corner', cat: 'street-food', price: 'BUDGET' as const, loc: 'Majnu Ka Tilla', tag: 'street-food', rating: 4.8 },
    { name: 'North Campus Elite Girls PG', cat: 'pgs-hostels', price: 'MODERATE' as const, loc: 'GTB Nagar', tag: 'ac-rooms', rating: 4.8 },
    { name: 'Vintage Vault Antique Furniture', cat: 'shopping-markets', price: 'PREMIUM' as const, loc: 'Hauz Khas Village', tag: 'heritage', rating: 4.6 },
    { name: 'Drishti IAS Study Circle', cat: 'coaching-institutes', price: 'PREMIUM' as const, loc: 'Karol Bagh', tag: 'student-friendly', rating: 4.9 },
    { name: 'The Potbelly Rooftop Bihari Kitchen', cat: 'restaurants', price: 'MODERATE' as const, loc: 'Saket', tag: 'rooftop', rating: 4.7 },
    { name: 'FabIndia Experience Centre & Cafe', cat: 'shopping-markets', price: 'MODERATE' as const, loc: 'Lajpat Nagar', tag: 'family-dining', rating: 4.7 },
    { name: 'Anytime Fitness South Ext 2', cat: 'gyms-fitness', price: 'MODERATE' as const, loc: 'South Extension', tag: '24x7-access', rating: 4.8 },
    { name: 'Qutub Minar Complex & Garden', cat: 'historical-monuments', price: 'BUDGET' as const, loc: 'Saket', tag: 'heritage', rating: 4.9 },
    { name: 'DigiWorld Component Matrix', cat: 'electronics-gadgets', price: 'MODERATE' as const, loc: 'Nehru Place', tag: 'metro-accessible', rating: 4.6 },
    { name: 'Lodhi Art District Street Murals', cat: 'places-visit', price: 'BUDGET' as const, loc: 'South Extension', tag: 'outdoor-seating', rating: 4.8 },
    { name: 'Chai Point Campus Express', cat: 'cafes-bakeries', price: 'BUDGET' as const, loc: 'GTB Nagar', tag: 'wifi-enabled', rating: 4.5 },
    { name: 'Shri Ram Center Art & Theatre', cat: 'places-visit', price: 'BUDGET' as const, loc: 'Connaught Place', tag: 'live-music', rating: 4.7 },
    { name: 'South Delhi Stays & Serviced Suites', cat: 'hotels', price: 'PREMIUM' as const, loc: 'Saket', tag: 'ac-rooms', rating: 4.8 },
    { name: 'Karol Bagh Wedding Saree Emporium', cat: 'apparel-ethnic', price: 'MODERATE' as const, loc: 'Karol Bagh', tag: 'cashless', rating: 4.6 },
    { name: 'Wenger Deli & Bakery (1926)', cat: 'cafes-bakeries', price: 'MODERATE' as const, loc: 'Connaught Place', tag: 'heritage', rating: 4.9 },
    { name: 'Dwarka International Badminton Club', cat: 'gyms-fitness', price: 'BUDGET' as const, loc: 'Dwarka', tag: 'student-friendly', rating: 4.7 },
    { name: 'The Big Chill Cafe', cat: 'cafes-bakeries', price: 'MODERATE' as const, loc: 'South Extension', tag: 'couple-friendly', rating: 4.8 },
    { name: 'Lajpat Afghan Shawl & Carpet Bazaar', cat: 'shopping-markets', price: 'MODERATE' as const, loc: 'Lajpat Nagar', tag: 'authentic-taste', rating: 4.7 },
    { name: 'Delhi School of Music & Performing Arts', cat: 'education-coaching', price: 'PREMIUM' as const, loc: 'Connaught Place', tag: 'student-friendly', rating: 4.8 },
    { name: 'Rigo Restaurant Tibetan Special', cat: 'street-food', price: 'BUDGET' as const, loc: 'Majnu Ka Tilla', tag: 'street-food', rating: 4.6 },
    { name: 'Bailamore Specialty Coffee', cat: 'cafes-bakeries', price: 'MODERATE' as const, loc: 'Hauz Khas Village', tag: 'wifi-enabled', rating: 4.8 },
    { name: 'Nehru Planetarium & Nehru Park', cat: 'places-visit', price: 'BUDGET' as const, loc: 'Connaught Place', tag: 'outdoor-seating', rating: 4.7 },
    { name: 'Kingsway Boys Luxury Residency PG', cat: 'pgs-hostels', price: 'MODERATE' as const, loc: 'GTB Nagar', tag: 'hygienic-mess', rating: 4.7 },
    { name: 'Shankar Market Famous Book Depot', cat: 'books-stationery', price: 'BUDGET' as const, loc: 'Connaught Place', tag: 'budget-friendly', rating: 4.6 },
    { name: 'LookWell Salon & Grooming Studio', cat: 'salons-spas', price: 'MODERATE' as const, loc: 'Karol Bagh', tag: 'metro-accessible', rating: 4.7 },
    { name: 'Moti Mahal Deluxe Daryaganj', cat: 'restaurants', price: 'MODERATE' as const, loc: 'Chandni Chowk', tag: 'authentic-taste', rating: 4.8 },
    { name: 'Green Park Lotus Wellness Hub', cat: 'salons-spas', price: 'PREMIUM' as const, loc: 'Hauz Khas Village', tag: 'organic', rating: 4.9 },
  ];

  let idCounter = 23;
  for (const item of prefixes) {
    const slug = item.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    result.push({
      id: `biz_${idCounter++}`,
      name: item.name,
      slug,
      description: `${item.name} is a premier verified listing in ${item.loc}, Delhi NCR offering top-rated ${item.cat} services with authentic quality and verified amenities.`,
      shortDescription: `Verified ${item.cat} destination in ${item.loc}, Delhi.`,
      categorySlug: item.cat,
      categorySlugs: [item.cat],
      address: `Main Boulevard, ${item.loc}`,
      locality: item.loc,
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      pincode: '110001',
      latitude: 28.6139 + (Math.random() - 0.5) * 0.1,
      longitude: 77.209 + (Math.random() - 0.5) * 0.1,
      phone: `+91 11 ${Math.floor(10000000 + Math.random() * 90000000)}`,
      email: `contact@${slug}.demo.in`,
      website: `https://${slug}.demo.in`,
      images: [
        'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
      ],
      logo: '',
      priceRange: item.price,
      rating: item.rating,
      reviewCount: Math.floor(200 + Math.random() * 2500),
      tags: [item.tag, 'verified-community', 'delhi-pick', 'metro-accessible'],
      amenities: ['Air Conditioned', 'Card & UPI Accepted', 'Verified Staff'],
      features: ['Top Rated in Locality', 'Specialty Service', 'Clean Environment'],
      openingHours: {
        Monday: '09:00 AM - 09:30 PM',
        Tuesday: '09:00 AM - 09:30 PM',
        Wednesday: '09:00 AM - 09:30 PM',
        Thursday: '09:00 AM - 09:30 PM',
        Friday: '09:00 AM - 09:30 PM',
        Saturday: '09:00 AM - 10:00 PM',
        Sunday: '09:00 AM - 10:00 PM',
      },
      verified: true,
      claimed: Math.random() > 0.5,
      status: 'ACTIVE',
    });
  }

  return result;
};
